// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"mailvault/domain/entities"
	"sync"
)

// SendUseCaseMock is a mock implementation of v1.SendUseCase.
//
//	func TestSomethingThatUsesSendUseCase(t *testing.T) {
//
//		// make and configure a mocked v1.SendUseCase
//		mockedSendUseCase := &SendUseCaseMock{
//			GetDomainByAPIKeyFunc: func(ctx context.Context, apiKey string) (*entities.Domain, error) {
//				panic("mock out the GetDomainByAPIKey method")
//			},
//		}
//
//		// use mockedSendUseCase in code that requires v1.SendUseCase
//		// and then make assertions.
//
//	}
type SendUseCaseMock struct {
	// GetDomainByAPIKeyFunc mocks the GetDomainByAPIKey method.
	GetDomainByAPIKeyFunc func(ctx context.Context, apiKey string) (*entities.Domain, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetDomainByAPIKey holds details about calls to the GetDomainByAPIKey method.
		GetDomainByAPIKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ApiKey is the apiKey argument value.
			ApiKey string
		}
	}
	lockGetDomainByAPIKey sync.RWMutex
}

// GetDomainByAPIKey calls GetDomainByAPIKeyFunc.
func (mock *SendUseCaseMock) GetDomainByAPIKey(ctx context.Context, apiKey string) (*entities.Domain, error) {
	callInfo := struct {
		Ctx    context.Context
		ApiKey string
	}{
		Ctx:    ctx,
		ApiKey: apiKey,
	}
	mock.lockGetDomainByAPIKey.Lock()
	mock.calls.GetDomainByAPIKey = append(mock.calls.GetDomainByAPIKey, callInfo)
	mock.lockGetDomainByAPIKey.Unlock()
	if mock.GetDomainByAPIKeyFunc == nil {
		var (
			domainOut *entities.Domain
			errOut    error
		)
		return domainOut, errOut
	}
	return mock.GetDomainByAPIKeyFunc(ctx, apiKey)
}

// GetDomainByAPIKeyCalls gets all the calls that were made to GetDomainByAPIKey.
// Check the length with:
//
//	len(mockedSendUseCase.GetDomainByAPIKeyCalls())
func (mock *SendUseCaseMock) GetDomainByAPIKeyCalls() []struct {
	Ctx    context.Context
	ApiKey string
} {
	var calls []struct {
		Ctx    context.Context
		ApiKey string
	}
	mock.lockGetDomainByAPIKey.RLock()
	calls = mock.calls.GetDomainByAPIKey
	mock.lockGetDomainByAPIKey.RUnlock()
	return calls
}
