FROM golang:1.26-alpine

WORKDIR /app

RUN apk add --no-cache git make bash

COPY Makefile ./
COPY gateways/repository/pg/migrations ./gateways/repository/pg/migrations/

# Install migrate tool
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

ENV PATH="${PATH}:/go/bin"

CMD ["make", "migration/up"]

