// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"mailvault/domain/auth"
	"mailvault/domain/entities"
	"sync"
)

// ProviderMock is a mock implementation of auth.Provider.
//
//	func TestSomethingThatUsesProvider(t *testing.T) {
//
//		// make and configure a mocked auth.Provider
//		mockedProvider := &ProviderMock{
//			ConfirmEmailFunc: func(ctx context.Context, token string, email string) (string, error) {
//				panic("mock out the ConfirmEmail method")
//			},
//			CreateUserFunc: func(ctx context.Context, email string, password string) (*auth.CreateUserResponse, error) {
//				panic("mock out the CreateUser method")
//			},
//			GetUserByIDFunc: func(ctx context.Context, id string) (*entities.User, error) {
//				panic("mock out the GetUserByID method")
//			},
//			LoginFunc: func(ctx context.Context, email string, password string) (string, error) {
//				panic("mock out the Login method")
//			},
//			ProviderFunc: func() string {
//				panic("mock out the Provider method")
//			},
//			ResendConfirmationFunc: func(ctx context.Context, email string) error {
//				panic("mock out the ResendConfirmation method")
//			},
//			ValidateTokenFunc: func(ctx context.Context, token string) (*entities.User, error) {
//				panic("mock out the ValidateToken method")
//			},
//		}
//
//		// use mockedProvider in code that requires auth.Provider
//		// and then make assertions.
//
//	}
type ProviderMock struct {
	// ConfirmEmailFunc mocks the ConfirmEmail method.
	ConfirmEmailFunc func(ctx context.Context, token string, email string) (string, error)

	// CreateUserFunc mocks the CreateUser method.
	CreateUserFunc func(ctx context.Context, email string, password string) (*auth.CreateUserResponse, error)

	// GetUserByIDFunc mocks the GetUserByID method.
	GetUserByIDFunc func(ctx context.Context, id string) (*entities.User, error)

	// LoginFunc mocks the Login method.
	LoginFunc func(ctx context.Context, email string, password string) (string, error)

	// ProviderFunc mocks the Provider method.
	ProviderFunc func() string

	// ResendConfirmationFunc mocks the ResendConfirmation method.
	ResendConfirmationFunc func(ctx context.Context, email string) error

	// ValidateTokenFunc mocks the ValidateToken method.
	ValidateTokenFunc func(ctx context.Context, token string) (*entities.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// ConfirmEmail holds details about calls to the ConfirmEmail method.
		ConfirmEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
			// Email is the email argument value.
			Email string
		}
		// CreateUser holds details about calls to the CreateUser method.
		CreateUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
			// Password is the password argument value.
			Password string
		}
		// GetUserByID holds details about calls to the GetUserByID method.
		GetUserByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Login holds details about calls to the Login method.
		Login []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
			// Password is the password argument value.
			Password string
		}
		// Provider holds details about calls to the Provider method.
		Provider []struct {
		}
		// ResendConfirmation holds details about calls to the ResendConfirmation method.
		ResendConfirmation []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// ValidateToken holds details about calls to the ValidateToken method.
		ValidateToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
		}
	}
	lockConfirmEmail       sync.RWMutex
	lockCreateUser         sync.RWMutex
	lockGetUserByID        sync.RWMutex
	lockLogin              sync.RWMutex
	lockProvider           sync.RWMutex
	lockResendConfirmation sync.RWMutex
	lockValidateToken      sync.RWMutex
}

// ConfirmEmail calls ConfirmEmailFunc.
func (mock *ProviderMock) ConfirmEmail(ctx context.Context, token string, email string) (string, error) {
	callInfo := struct {
		Ctx   context.Context
		Token string
		Email string
	}{
		Ctx:   ctx,
		Token: token,
		Email: email,
	}
	mock.lockConfirmEmail.Lock()
	mock.calls.ConfirmEmail = append(mock.calls.ConfirmEmail, callInfo)
	mock.lockConfirmEmail.Unlock()
	if mock.ConfirmEmailFunc == nil {
		var (
			sOut   string
			errOut error
		)
		return sOut, errOut
	}
	return mock.ConfirmEmailFunc(ctx, token, email)
}

// ConfirmEmailCalls gets all the calls that were made to ConfirmEmail.
// Check the length with:
//
//	len(mockedProvider.ConfirmEmailCalls())
func (mock *ProviderMock) ConfirmEmailCalls() []struct {
	Ctx   context.Context
	Token string
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
		Email string
	}
	mock.lockConfirmEmail.RLock()
	calls = mock.calls.ConfirmEmail
	mock.lockConfirmEmail.RUnlock()
	return calls
}

// CreateUser calls CreateUserFunc.
func (mock *ProviderMock) CreateUser(ctx context.Context, email string, password string) (*auth.CreateUserResponse, error) {
	callInfo := struct {
		Ctx      context.Context
		Email    string
		Password string
	}{
		Ctx:      ctx,
		Email:    email,
		Password: password,
	}
	mock.lockCreateUser.Lock()
	mock.calls.CreateUser = append(mock.calls.CreateUser, callInfo)
	mock.lockCreateUser.Unlock()
	if mock.CreateUserFunc == nil {
		var (
			createUserResponseOut *auth.CreateUserResponse
			errOut                error
		)
		return createUserResponseOut, errOut
	}
	return mock.CreateUserFunc(ctx, email, password)
}

// CreateUserCalls gets all the calls that were made to CreateUser.
// Check the length with:
//
//	len(mockedProvider.CreateUserCalls())
func (mock *ProviderMock) CreateUserCalls() []struct {
	Ctx      context.Context
	Email    string
	Password string
} {
	var calls []struct {
		Ctx      context.Context
		Email    string
		Password string
	}
	mock.lockCreateUser.RLock()
	calls = mock.calls.CreateUser
	mock.lockCreateUser.RUnlock()
	return calls
}

// GetUserByID calls GetUserByIDFunc.
func (mock *ProviderMock) GetUserByID(ctx context.Context, id string) (*entities.User, error) {
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetUserByID.Lock()
	mock.calls.GetUserByID = append(mock.calls.GetUserByID, callInfo)
	mock.lockGetUserByID.Unlock()
	if mock.GetUserByIDFunc == nil {
		var (
			userOut *entities.User
			errOut  error
		)
		return userOut, errOut
	}
	return mock.GetUserByIDFunc(ctx, id)
}

// GetUserByIDCalls gets all the calls that were made to GetUserByID.
// Check the length with:
//
//	len(mockedProvider.GetUserByIDCalls())
func (mock *ProviderMock) GetUserByIDCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGetUserByID.RLock()
	calls = mock.calls.GetUserByID
	mock.lockGetUserByID.RUnlock()
	return calls
}

// Login calls LoginFunc.
func (mock *ProviderMock) Login(ctx context.Context, email string, password string) (string, error) {
	callInfo := struct {
		Ctx      context.Context
		Email    string
		Password string
	}{
		Ctx:      ctx,
		Email:    email,
		Password: password,
	}
	mock.lockLogin.Lock()
	mock.calls.Login = append(mock.calls.Login, callInfo)
	mock.lockLogin.Unlock()
	if mock.LoginFunc == nil {
		var (
			sOut   string
			errOut error
		)
		return sOut, errOut
	}
	return mock.LoginFunc(ctx, email, password)
}

// LoginCalls gets all the calls that were made to Login.
// Check the length with:
//
//	len(mockedProvider.LoginCalls())
func (mock *ProviderMock) LoginCalls() []struct {
	Ctx      context.Context
	Email    string
	Password string
} {
	var calls []struct {
		Ctx      context.Context
		Email    string
		Password string
	}
	mock.lockLogin.RLock()
	calls = mock.calls.Login
	mock.lockLogin.RUnlock()
	return calls
}

// Provider calls ProviderFunc.
func (mock *ProviderMock) Provider() string {
	callInfo := struct {
	}{}
	mock.lockProvider.Lock()
	mock.calls.Provider = append(mock.calls.Provider, callInfo)
	mock.lockProvider.Unlock()
	if mock.ProviderFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.ProviderFunc()
}

// ProviderCalls gets all the calls that were made to Provider.
// Check the length with:
//
//	len(mockedProvider.ProviderCalls())
func (mock *ProviderMock) ProviderCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockProvider.RLock()
	calls = mock.calls.Provider
	mock.lockProvider.RUnlock()
	return calls
}

// ResendConfirmation calls ResendConfirmationFunc.
func (mock *ProviderMock) ResendConfirmation(ctx context.Context, email string) error {
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockResendConfirmation.Lock()
	mock.calls.ResendConfirmation = append(mock.calls.ResendConfirmation, callInfo)
	mock.lockResendConfirmation.Unlock()
	if mock.ResendConfirmationFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.ResendConfirmationFunc(ctx, email)
}

// ResendConfirmationCalls gets all the calls that were made to ResendConfirmation.
// Check the length with:
//
//	len(mockedProvider.ResendConfirmationCalls())
func (mock *ProviderMock) ResendConfirmationCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockResendConfirmation.RLock()
	calls = mock.calls.ResendConfirmation
	mock.lockResendConfirmation.RUnlock()
	return calls
}

// ValidateToken calls ValidateTokenFunc.
func (mock *ProviderMock) ValidateToken(ctx context.Context, token string) (*entities.User, error) {
	callInfo := struct {
		Ctx   context.Context
		Token string
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockValidateToken.Lock()
	mock.calls.ValidateToken = append(mock.calls.ValidateToken, callInfo)
	mock.lockValidateToken.Unlock()
	if mock.ValidateTokenFunc == nil {
		var (
			userOut *entities.User
			errOut  error
		)
		return userOut, errOut
	}
	return mock.ValidateTokenFunc(ctx, token)
}

// ValidateTokenCalls gets all the calls that were made to ValidateToken.
// Check the length with:
//
//	len(mockedProvider.ValidateTokenCalls())
func (mock *ProviderMock) ValidateTokenCalls() []struct {
	Ctx   context.Context
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
	}
	mock.lockValidateToken.RLock()
	calls = mock.calls.ValidateToken
	mock.lockValidateToken.RUnlock()
	return calls
}
