// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/mailvault/mailvault/domain/entities"
	"sync"

	"github.com/gofrs/uuid/v5"
)

// UseCaseMock is a mock implementation of auth.UseCase.
//
//	func TestSomethingThatUsesUseCase(t *testing.T) {
//
//		// make and configure a mocked auth.UseCase
//		mockedUseCase := &UseCaseMock{
//			GetOrCreateUserByAuthProviderFunc: func(ctx context.Context, provider string, providerID string, email string) (*entities.User, error) {
//				panic("mock out the GetOrCreateUserByAuthProvider method")
//			},
//			GetUserByEmailFunc: func(ctx context.Context, email string) (*entities.User, error) {
//				panic("mock out the GetUserByEmail method")
//			},
//			GetUserByIDFunc: func(ctx context.Context, id uuid.UUID) (*entities.User, error) {
//				panic("mock out the GetUserByID method")
//			},
//		}
//
//		// use mockedUseCase in code that requires auth.UseCase
//		// and then make assertions.
//
//	}
type UseCaseMock struct {
	// GetOrCreateUserByAuthProviderFunc mocks the GetOrCreateUserByAuthProvider method.
	GetOrCreateUserByAuthProviderFunc func(ctx context.Context, provider string, providerID string, email string) (*entities.User, error)

	// GetUserByEmailFunc mocks the GetUserByEmail method.
	GetUserByEmailFunc func(ctx context.Context, email string) (*entities.User, error)

	// GetUserByIDFunc mocks the GetUserByID method.
	GetUserByIDFunc func(ctx context.Context, id uuid.UUID) (*entities.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetOrCreateUserByAuthProvider holds details about calls to the GetOrCreateUserByAuthProvider method.
		GetOrCreateUserByAuthProvider []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Provider is the provider argument value.
			Provider string
			// ProviderID is the providerID argument value.
			ProviderID string
			// Email is the email argument value.
			Email string
		}
		// GetUserByEmail holds details about calls to the GetUserByEmail method.
		GetUserByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// GetUserByID holds details about calls to the GetUserByID method.
		GetUserByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
	}
	lockGetOrCreateUserByAuthProvider sync.RWMutex
	lockGetUserByEmail                sync.RWMutex
	lockGetUserByID                   sync.RWMutex
}

// GetOrCreateUserByAuthProvider calls GetOrCreateUserByAuthProviderFunc.
func (mock *UseCaseMock) GetOrCreateUserByAuthProvider(ctx context.Context, provider string, providerID string, email string) (*entities.User, error) {
	callInfo := struct {
		Ctx        context.Context
		Provider   string
		ProviderID string
		Email      string
	}{
		Ctx:        ctx,
		Provider:   provider,
		ProviderID: providerID,
		Email:      email,
	}
	mock.lockGetOrCreateUserByAuthProvider.Lock()
	mock.calls.GetOrCreateUserByAuthProvider = append(mock.calls.GetOrCreateUserByAuthProvider, callInfo)
	mock.lockGetOrCreateUserByAuthProvider.Unlock()
	if mock.GetOrCreateUserByAuthProviderFunc == nil {
		var (
			userOut *entities.User
			errOut  error
		)
		return userOut, errOut
	}
	return mock.GetOrCreateUserByAuthProviderFunc(ctx, provider, providerID, email)
}

// GetOrCreateUserByAuthProviderCalls gets all the calls that were made to GetOrCreateUserByAuthProvider.
// Check the length with:
//
//	len(mockedUseCase.GetOrCreateUserByAuthProviderCalls())
func (mock *UseCaseMock) GetOrCreateUserByAuthProviderCalls() []struct {
	Ctx        context.Context
	Provider   string
	ProviderID string
	Email      string
} {
	var calls []struct {
		Ctx        context.Context
		Provider   string
		ProviderID string
		Email      string
	}
	mock.lockGetOrCreateUserByAuthProvider.RLock()
	calls = mock.calls.GetOrCreateUserByAuthProvider
	mock.lockGetOrCreateUserByAuthProvider.RUnlock()
	return calls
}

// GetUserByEmail calls GetUserByEmailFunc.
func (mock *UseCaseMock) GetUserByEmail(ctx context.Context, email string) (*entities.User, error) {
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockGetUserByEmail.Lock()
	mock.calls.GetUserByEmail = append(mock.calls.GetUserByEmail, callInfo)
	mock.lockGetUserByEmail.Unlock()
	if mock.GetUserByEmailFunc == nil {
		var (
			userOut *entities.User
			errOut  error
		)
		return userOut, errOut
	}
	return mock.GetUserByEmailFunc(ctx, email)
}

// GetUserByEmailCalls gets all the calls that were made to GetUserByEmail.
// Check the length with:
//
//	len(mockedUseCase.GetUserByEmailCalls())
func (mock *UseCaseMock) GetUserByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockGetUserByEmail.RLock()
	calls = mock.calls.GetUserByEmail
	mock.lockGetUserByEmail.RUnlock()
	return calls
}

// GetUserByID calls GetUserByIDFunc.
func (mock *UseCaseMock) GetUserByID(ctx context.Context, id uuid.UUID) (*entities.User, error) {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetUserByID.Lock()
	mock.calls.GetUserByID = append(mock.calls.GetUserByID, callInfo)
	mock.lockGetUserByID.Unlock()
	if mock.GetUserByIDFunc == nil {
		var (
			userOut *entities.User
			errOut  error
		)
		return userOut, errOut
	}
	return mock.GetUserByIDFunc(ctx, id)
}

// GetUserByIDCalls gets all the calls that were made to GetUserByID.
// Check the length with:
//
//	len(mockedUseCase.GetUserByIDCalls())
func (mock *UseCaseMock) GetUserByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetUserByID.RLock()
	calls = mock.calls.GetUserByID
	mock.lockGetUserByID.RUnlock()
	return calls
}
