// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/gofrs/uuid/v5"
	domainpkg "mailsafe/domain/domain"
	"mailsafe/domain/entities"
	"sync"
)

// DomainUseCaseMock is a mock implementation of v1.DomainUseCase.
//
//	func TestSomethingThatUsesDomainUseCase(t *testing.T) {
//
//		// make and configure a mocked v1.DomainUseCase
//		mockedDomainUseCase := &DomainUseCaseMock{
//			CreateDomainFunc: func(ctx context.Context, req domainpkg.CreateDomainInput) (*entities.Domain, error) {
//				panic("mock out the CreateDomain method")
//			},
//			DeleteDomainFunc: func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
//				panic("mock out the DeleteDomain method")
//			},
//			GetDomainByAPIKeyFunc: func(ctx context.Context, apiKey string) (*entities.Domain, error) {
//				panic("mock out the GetDomainByAPIKey method")
//			},
//			GetDomainByIDFunc: func(ctx context.Context, id uuid.UUID) (*entities.Domain, error) {
//				panic("mock out the GetDomainByID method")
//			},
//			GetDomainByNameFunc: func(ctx context.Context, domainName string) (*entities.Domain, error) {
//				panic("mock out the GetDomainByName method")
//			},
//			GetDomainsByUserIDFunc: func(ctx context.Context, userID uuid.UUID) ([]*entities.Domain, error) {
//				panic("mock out the GetDomainsByUserID method")
//			},
//			UpdateDomainFunc: func(ctx context.Context, id uuid.UUID, req domainpkg.UpdateDomainInput) (*entities.Domain, error) {
//				panic("mock out the UpdateDomain method")
//			},
//		}
//
//		// use mockedDomainUseCase in code that requires v1.DomainUseCase
//		// and then make assertions.
//
//	}
type DomainUseCaseMock struct {
	// CreateDomainFunc mocks the CreateDomain method.
	CreateDomainFunc func(ctx context.Context, req domainpkg.CreateDomainInput) (*entities.Domain, error)

	// DeleteDomainFunc mocks the DeleteDomain method.
	DeleteDomainFunc func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error

	// GetDomainByAPIKeyFunc mocks the GetDomainByAPIKey method.
	GetDomainByAPIKeyFunc func(ctx context.Context, apiKey string) (*entities.Domain, error)

	// GetDomainByIDFunc mocks the GetDomainByID method.
	GetDomainByIDFunc func(ctx context.Context, id uuid.UUID) (*entities.Domain, error)

	// GetDomainByNameFunc mocks the GetDomainByName method.
	GetDomainByNameFunc func(ctx context.Context, domainName string) (*entities.Domain, error)

	// GetDomainsByUserIDFunc mocks the GetDomainsByUserID method.
	GetDomainsByUserIDFunc func(ctx context.Context, userID uuid.UUID) ([]*entities.Domain, error)

	// UpdateDomainFunc mocks the UpdateDomain method.
	UpdateDomainFunc func(ctx context.Context, id uuid.UUID, req domainpkg.UpdateDomainInput) (*entities.Domain, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateDomain holds details about calls to the CreateDomain method.
		CreateDomain []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req domainpkg.CreateDomainInput
		}
		// DeleteDomain holds details about calls to the DeleteDomain method.
		DeleteDomain []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// GetDomainByAPIKey holds details about calls to the GetDomainByAPIKey method.
		GetDomainByAPIKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ApiKey is the apiKey argument value.
			ApiKey string
		}
		// GetDomainByID holds details about calls to the GetDomainByID method.
		GetDomainByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetDomainByName holds details about calls to the GetDomainByName method.
		GetDomainByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DomainName is the domainName argument value.
			DomainName string
		}
		// GetDomainsByUserID holds details about calls to the GetDomainsByUserID method.
		GetDomainsByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// UpdateDomain holds details about calls to the UpdateDomain method.
		UpdateDomain []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// Req is the req argument value.
			Req domainpkg.UpdateDomainInput
		}
	}
	lockCreateDomain       sync.RWMutex
	lockDeleteDomain       sync.RWMutex
	lockGetDomainByAPIKey  sync.RWMutex
	lockGetDomainByID      sync.RWMutex
	lockGetDomainByName    sync.RWMutex
	lockGetDomainsByUserID sync.RWMutex
	lockUpdateDomain       sync.RWMutex
}

// CreateDomain calls CreateDomainFunc.
func (mock *DomainUseCaseMock) CreateDomain(ctx context.Context, req domainpkg.CreateDomainInput) (*entities.Domain, error) {
	callInfo := struct {
		Ctx context.Context
		Req domainpkg.CreateDomainInput
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreateDomain.Lock()
	mock.calls.CreateDomain = append(mock.calls.CreateDomain, callInfo)
	mock.lockCreateDomain.Unlock()
	if mock.CreateDomainFunc == nil {
		var (
			domainOut *entities.Domain
			errOut    error
		)
		return domainOut, errOut
	}
	return mock.CreateDomainFunc(ctx, req)
}

// CreateDomainCalls gets all the calls that were made to CreateDomain.
// Check the length with:
//
//	len(mockedDomainUseCase.CreateDomainCalls())
func (mock *DomainUseCaseMock) CreateDomainCalls() []struct {
	Ctx context.Context
	Req domainpkg.CreateDomainInput
} {
	var calls []struct {
		Ctx context.Context
		Req domainpkg.CreateDomainInput
	}
	mock.lockCreateDomain.RLock()
	calls = mock.calls.CreateDomain
	mock.lockCreateDomain.RUnlock()
	return calls
}

// DeleteDomain calls DeleteDomainFunc.
func (mock *DomainUseCaseMock) DeleteDomain(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	callInfo := struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		ID:     id,
		UserID: userID,
	}
	mock.lockDeleteDomain.Lock()
	mock.calls.DeleteDomain = append(mock.calls.DeleteDomain, callInfo)
	mock.lockDeleteDomain.Unlock()
	if mock.DeleteDomainFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteDomainFunc(ctx, id, userID)
}

// DeleteDomainCalls gets all the calls that were made to DeleteDomain.
// Check the length with:
//
//	len(mockedDomainUseCase.DeleteDomainCalls())
func (mock *DomainUseCaseMock) DeleteDomainCalls() []struct {
	Ctx    context.Context
	ID     uuid.UUID
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}
	mock.lockDeleteDomain.RLock()
	calls = mock.calls.DeleteDomain
	mock.lockDeleteDomain.RUnlock()
	return calls
}

// GetDomainByAPIKey calls GetDomainByAPIKeyFunc.
func (mock *DomainUseCaseMock) GetDomainByAPIKey(ctx context.Context, apiKey string) (*entities.Domain, error) {
	callInfo := struct {
		Ctx    context.Context
		ApiKey string
	}{
		Ctx:    ctx,
		ApiKey: apiKey,
	}
	mock.lockGetDomainByAPIKey.Lock()
	mock.calls.GetDomainByAPIKey = append(mock.calls.GetDomainByAPIKey, callInfo)
	mock.lockGetDomainByAPIKey.Unlock()
	if mock.GetDomainByAPIKeyFunc == nil {
		var (
			domainOut *entities.Domain
			errOut    error
		)
		return domainOut, errOut
	}
	return mock.GetDomainByAPIKeyFunc(ctx, apiKey)
}

// GetDomainByAPIKeyCalls gets all the calls that were made to GetDomainByAPIKey.
// Check the length with:
//
//	len(mockedDomainUseCase.GetDomainByAPIKeyCalls())
func (mock *DomainUseCaseMock) GetDomainByAPIKeyCalls() []struct {
	Ctx    context.Context
	ApiKey string
} {
	var calls []struct {
		Ctx    context.Context
		ApiKey string
	}
	mock.lockGetDomainByAPIKey.RLock()
	calls = mock.calls.GetDomainByAPIKey
	mock.lockGetDomainByAPIKey.RUnlock()
	return calls
}

// GetDomainByID calls GetDomainByIDFunc.
func (mock *DomainUseCaseMock) GetDomainByID(ctx context.Context, id uuid.UUID) (*entities.Domain, error) {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetDomainByID.Lock()
	mock.calls.GetDomainByID = append(mock.calls.GetDomainByID, callInfo)
	mock.lockGetDomainByID.Unlock()
	if mock.GetDomainByIDFunc == nil {
		var (
			domainOut *entities.Domain
			errOut    error
		)
		return domainOut, errOut
	}
	return mock.GetDomainByIDFunc(ctx, id)
}

// GetDomainByIDCalls gets all the calls that were made to GetDomainByID.
// Check the length with:
//
//	len(mockedDomainUseCase.GetDomainByIDCalls())
func (mock *DomainUseCaseMock) GetDomainByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetDomainByID.RLock()
	calls = mock.calls.GetDomainByID
	mock.lockGetDomainByID.RUnlock()
	return calls
}

// GetDomainByName calls GetDomainByNameFunc.
func (mock *DomainUseCaseMock) GetDomainByName(ctx context.Context, domainName string) (*entities.Domain, error) {
	callInfo := struct {
		Ctx        context.Context
		DomainName string
	}{
		Ctx:        ctx,
		DomainName: domainName,
	}
	mock.lockGetDomainByName.Lock()
	mock.calls.GetDomainByName = append(mock.calls.GetDomainByName, callInfo)
	mock.lockGetDomainByName.Unlock()
	if mock.GetDomainByNameFunc == nil {
		var (
			domainOut *entities.Domain
			errOut    error
		)
		return domainOut, errOut
	}
	return mock.GetDomainByNameFunc(ctx, domainName)
}

// GetDomainByNameCalls gets all the calls that were made to GetDomainByName.
// Check the length with:
//
//	len(mockedDomainUseCase.GetDomainByNameCalls())
func (mock *DomainUseCaseMock) GetDomainByNameCalls() []struct {
	Ctx        context.Context
	DomainName string
} {
	var calls []struct {
		Ctx        context.Context
		DomainName string
	}
	mock.lockGetDomainByName.RLock()
	calls = mock.calls.GetDomainByName
	mock.lockGetDomainByName.RUnlock()
	return calls
}

// GetDomainsByUserID calls GetDomainsByUserIDFunc.
func (mock *DomainUseCaseMock) GetDomainsByUserID(ctx context.Context, userID uuid.UUID) ([]*entities.Domain, error) {
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetDomainsByUserID.Lock()
	mock.calls.GetDomainsByUserID = append(mock.calls.GetDomainsByUserID, callInfo)
	mock.lockGetDomainsByUserID.Unlock()
	if mock.GetDomainsByUserIDFunc == nil {
		var (
			domainsOut []*entities.Domain
			errOut     error
		)
		return domainsOut, errOut
	}
	return mock.GetDomainsByUserIDFunc(ctx, userID)
}

// GetDomainsByUserIDCalls gets all the calls that were made to GetDomainsByUserID.
// Check the length with:
//
//	len(mockedDomainUseCase.GetDomainsByUserIDCalls())
func (mock *DomainUseCaseMock) GetDomainsByUserIDCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockGetDomainsByUserID.RLock()
	calls = mock.calls.GetDomainsByUserID
	mock.lockGetDomainsByUserID.RUnlock()
	return calls
}

// UpdateDomain calls UpdateDomainFunc.
func (mock *DomainUseCaseMock) UpdateDomain(ctx context.Context, id uuid.UUID, req domainpkg.UpdateDomainInput) (*entities.Domain, error) {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
		Req domainpkg.UpdateDomainInput
	}{
		Ctx: ctx,
		ID:  id,
		Req: req,
	}
	mock.lockUpdateDomain.Lock()
	mock.calls.UpdateDomain = append(mock.calls.UpdateDomain, callInfo)
	mock.lockUpdateDomain.Unlock()
	if mock.UpdateDomainFunc == nil {
		var (
			domainOut *entities.Domain
			errOut    error
		)
		return domainOut, errOut
	}
	return mock.UpdateDomainFunc(ctx, id, req)
}

// UpdateDomainCalls gets all the calls that were made to UpdateDomain.
// Check the length with:
//
//	len(mockedDomainUseCase.UpdateDomainCalls())
func (mock *DomainUseCaseMock) UpdateDomainCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
	Req domainpkg.UpdateDomainInput
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
		Req domainpkg.UpdateDomainInput
	}
	mock.lockUpdateDomain.RLock()
	calls = mock.calls.UpdateDomain
	mock.lockUpdateDomain.RUnlock()
	return calls
}
