// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"mailsafe/domain/entities"
	"sync"
)

// DomainRepositoryMock is a mock implementation of email.DomainRepository.
//
//	func TestSomethingThatUsesDomainRepository(t *testing.T) {
//
//		// make and configure a mocked email.DomainRepository
//		mockedDomainRepository := &DomainRepositoryMock{
//			GetByDomainFunc: func(ctx context.Context, domain string) (*entities.Domain, error) {
//				panic("mock out the GetByDomain method")
//			},
//		}
//
//		// use mockedDomainRepository in code that requires email.DomainRepository
//		// and then make assertions.
//
//	}
type DomainRepositoryMock struct {
	// GetByDomainFunc mocks the GetByDomain method.
	GetByDomainFunc func(ctx context.Context, domain string) (*entities.Domain, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetByDomain holds details about calls to the GetByDomain method.
		GetByDomain []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Domain is the domain argument value.
			Domain string
		}
	}
	lockGetByDomain sync.RWMutex
}

// GetByDomain calls GetByDomainFunc.
func (mock *DomainRepositoryMock) GetByDomain(ctx context.Context, domain string) (*entities.Domain, error) {
	callInfo := struct {
		Ctx    context.Context
		Domain string
	}{
		Ctx:    ctx,
		Domain: domain,
	}
	mock.lockGetByDomain.Lock()
	mock.calls.GetByDomain = append(mock.calls.GetByDomain, callInfo)
	mock.lockGetByDomain.Unlock()
	if mock.GetByDomainFunc == nil {
		var (
			domainOut *entities.Domain
			errOut    error
		)
		return domainOut, errOut
	}
	return mock.GetByDomainFunc(ctx, domain)
}

// GetByDomainCalls gets all the calls that were made to GetByDomain.
// Check the length with:
//
//	len(mockedDomainRepository.GetByDomainCalls())
func (mock *DomainRepositoryMock) GetByDomainCalls() []struct {
	Ctx    context.Context
	Domain string
} {
	var calls []struct {
		Ctx    context.Context
		Domain string
	}
	mock.lockGetByDomain.RLock()
	calls = mock.calls.GetByDomain
	mock.lockGetByDomain.RUnlock()
	return calls
}
