// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/gofrs/uuid/v5"
	"mailsafe/domain/entities"
	"sync"
)

// EmailAddressRepositoryMock is a mock implementation of email.EmailAddressRepository.
//
//	func TestSomethingThatUsesEmailAddressRepository(t *testing.T) {
//
//		// make and configure a mocked email.EmailAddressRepository
//		mockedEmailAddressRepository := &EmailAddressRepositoryMock{
//			CreateFunc: func(ctx context.Context, emailAddress *entities.EmailAddress) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the Delete method")
//			},
//			GetByDomainIDFunc: func(ctx context.Context, domainID uuid.UUID) ([]*entities.EmailAddress, error) {
//				panic("mock out the GetByDomainID method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*entities.EmailAddress, error) {
//				panic("mock out the GetByID method")
//			},
//			GetByLocalPartAndDomainFunc: func(ctx context.Context, localPart string, domainID uuid.UUID) (*entities.EmailAddress, error) {
//				panic("mock out the GetByLocalPartAndDomain method")
//			},
//			GetCatchAllByDomainIDFunc: func(ctx context.Context, domainID uuid.UUID) (*entities.EmailAddress, error) {
//				panic("mock out the GetCatchAllByDomainID method")
//			},
//			UpdateFunc: func(ctx context.Context, emailAddress *entities.EmailAddress) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedEmailAddressRepository in code that requires email.EmailAddressRepository
//		// and then make assertions.
//
//	}
type EmailAddressRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, emailAddress *entities.EmailAddress) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id uuid.UUID) error

	// GetByDomainIDFunc mocks the GetByDomainID method.
	GetByDomainIDFunc func(ctx context.Context, domainID uuid.UUID) ([]*entities.EmailAddress, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*entities.EmailAddress, error)

	// GetByLocalPartAndDomainFunc mocks the GetByLocalPartAndDomain method.
	GetByLocalPartAndDomainFunc func(ctx context.Context, localPart string, domainID uuid.UUID) (*entities.EmailAddress, error)

	// GetCatchAllByDomainIDFunc mocks the GetCatchAllByDomainID method.
	GetCatchAllByDomainIDFunc func(ctx context.Context, domainID uuid.UUID) (*entities.EmailAddress, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, emailAddress *entities.EmailAddress) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// EmailAddress is the emailAddress argument value.
			EmailAddress *entities.EmailAddress
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetByDomainID holds details about calls to the GetByDomainID method.
		GetByDomainID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DomainID is the domainID argument value.
			DomainID uuid.UUID
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetByLocalPartAndDomain holds details about calls to the GetByLocalPartAndDomain method.
		GetByLocalPartAndDomain []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// LocalPart is the localPart argument value.
			LocalPart string
			// DomainID is the domainID argument value.
			DomainID uuid.UUID
		}
		// GetCatchAllByDomainID holds details about calls to the GetCatchAllByDomainID method.
		GetCatchAllByDomainID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DomainID is the domainID argument value.
			DomainID uuid.UUID
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// EmailAddress is the emailAddress argument value.
			EmailAddress *entities.EmailAddress
		}
	}
	lockCreate                  sync.RWMutex
	lockDelete                  sync.RWMutex
	lockGetByDomainID           sync.RWMutex
	lockGetByID                 sync.RWMutex
	lockGetByLocalPartAndDomain sync.RWMutex
	lockGetCatchAllByDomainID   sync.RWMutex
	lockUpdate                  sync.RWMutex
}

// Create calls CreateFunc.
func (mock *EmailAddressRepositoryMock) Create(ctx context.Context, emailAddress *entities.EmailAddress) error {
	callInfo := struct {
		Ctx          context.Context
		EmailAddress *entities.EmailAddress
	}{
		Ctx:          ctx,
		EmailAddress: emailAddress,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CreateFunc(ctx, emailAddress)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedEmailAddressRepository.CreateCalls())
func (mock *EmailAddressRepositoryMock) CreateCalls() []struct {
	Ctx          context.Context
	EmailAddress *entities.EmailAddress
} {
	var calls []struct {
		Ctx          context.Context
		EmailAddress *entities.EmailAddress
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *EmailAddressRepositoryMock) Delete(ctx context.Context, id uuid.UUID) error {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedEmailAddressRepository.DeleteCalls())
func (mock *EmailAddressRepositoryMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetByDomainID calls GetByDomainIDFunc.
func (mock *EmailAddressRepositoryMock) GetByDomainID(ctx context.Context, domainID uuid.UUID) ([]*entities.EmailAddress, error) {
	callInfo := struct {
		Ctx      context.Context
		DomainID uuid.UUID
	}{
		Ctx:      ctx,
		DomainID: domainID,
	}
	mock.lockGetByDomainID.Lock()
	mock.calls.GetByDomainID = append(mock.calls.GetByDomainID, callInfo)
	mock.lockGetByDomainID.Unlock()
	if mock.GetByDomainIDFunc == nil {
		var (
			emailAddresssOut []*entities.EmailAddress
			errOut           error
		)
		return emailAddresssOut, errOut
	}
	return mock.GetByDomainIDFunc(ctx, domainID)
}

// GetByDomainIDCalls gets all the calls that were made to GetByDomainID.
// Check the length with:
//
//	len(mockedEmailAddressRepository.GetByDomainIDCalls())
func (mock *EmailAddressRepositoryMock) GetByDomainIDCalls() []struct {
	Ctx      context.Context
	DomainID uuid.UUID
} {
	var calls []struct {
		Ctx      context.Context
		DomainID uuid.UUID
	}
	mock.lockGetByDomainID.RLock()
	calls = mock.calls.GetByDomainID
	mock.lockGetByDomainID.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *EmailAddressRepositoryMock) GetByID(ctx context.Context, id uuid.UUID) (*entities.EmailAddress, error) {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	if mock.GetByIDFunc == nil {
		var (
			emailAddressOut *entities.EmailAddress
			errOut          error
		)
		return emailAddressOut, errOut
	}
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedEmailAddressRepository.GetByIDCalls())
func (mock *EmailAddressRepositoryMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetByLocalPartAndDomain calls GetByLocalPartAndDomainFunc.
func (mock *EmailAddressRepositoryMock) GetByLocalPartAndDomain(ctx context.Context, localPart string, domainID uuid.UUID) (*entities.EmailAddress, error) {
	callInfo := struct {
		Ctx       context.Context
		LocalPart string
		DomainID  uuid.UUID
	}{
		Ctx:       ctx,
		LocalPart: localPart,
		DomainID:  domainID,
	}
	mock.lockGetByLocalPartAndDomain.Lock()
	mock.calls.GetByLocalPartAndDomain = append(mock.calls.GetByLocalPartAndDomain, callInfo)
	mock.lockGetByLocalPartAndDomain.Unlock()
	if mock.GetByLocalPartAndDomainFunc == nil {
		var (
			emailAddressOut *entities.EmailAddress
			errOut          error
		)
		return emailAddressOut, errOut
	}
	return mock.GetByLocalPartAndDomainFunc(ctx, localPart, domainID)
}

// GetByLocalPartAndDomainCalls gets all the calls that were made to GetByLocalPartAndDomain.
// Check the length with:
//
//	len(mockedEmailAddressRepository.GetByLocalPartAndDomainCalls())
func (mock *EmailAddressRepositoryMock) GetByLocalPartAndDomainCalls() []struct {
	Ctx       context.Context
	LocalPart string
	DomainID  uuid.UUID
} {
	var calls []struct {
		Ctx       context.Context
		LocalPart string
		DomainID  uuid.UUID
	}
	mock.lockGetByLocalPartAndDomain.RLock()
	calls = mock.calls.GetByLocalPartAndDomain
	mock.lockGetByLocalPartAndDomain.RUnlock()
	return calls
}

// GetCatchAllByDomainID calls GetCatchAllByDomainIDFunc.
func (mock *EmailAddressRepositoryMock) GetCatchAllByDomainID(ctx context.Context, domainID uuid.UUID) (*entities.EmailAddress, error) {
	callInfo := struct {
		Ctx      context.Context
		DomainID uuid.UUID
	}{
		Ctx:      ctx,
		DomainID: domainID,
	}
	mock.lockGetCatchAllByDomainID.Lock()
	mock.calls.GetCatchAllByDomainID = append(mock.calls.GetCatchAllByDomainID, callInfo)
	mock.lockGetCatchAllByDomainID.Unlock()
	if mock.GetCatchAllByDomainIDFunc == nil {
		var (
			emailAddressOut *entities.EmailAddress
			errOut          error
		)
		return emailAddressOut, errOut
	}
	return mock.GetCatchAllByDomainIDFunc(ctx, domainID)
}

// GetCatchAllByDomainIDCalls gets all the calls that were made to GetCatchAllByDomainID.
// Check the length with:
//
//	len(mockedEmailAddressRepository.GetCatchAllByDomainIDCalls())
func (mock *EmailAddressRepositoryMock) GetCatchAllByDomainIDCalls() []struct {
	Ctx      context.Context
	DomainID uuid.UUID
} {
	var calls []struct {
		Ctx      context.Context
		DomainID uuid.UUID
	}
	mock.lockGetCatchAllByDomainID.RLock()
	calls = mock.calls.GetCatchAllByDomainID
	mock.lockGetCatchAllByDomainID.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *EmailAddressRepositoryMock) Update(ctx context.Context, emailAddress *entities.EmailAddress) error {
	callInfo := struct {
		Ctx          context.Context
		EmailAddress *entities.EmailAddress
	}{
		Ctx:          ctx,
		EmailAddress: emailAddress,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateFunc(ctx, emailAddress)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedEmailAddressRepository.UpdateCalls())
func (mock *EmailAddressRepositoryMock) UpdateCalls() []struct {
	Ctx          context.Context
	EmailAddress *entities.EmailAddress
} {
	var calls []struct {
		Ctx          context.Context
		EmailAddress *entities.EmailAddress
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
