// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
)

// EmailForwarderMock is a mock implementation of email.EmailForwarder.
//
//	func TestSomethingThatUsesEmailForwarder(t *testing.T) {
//
//		// make and configure a mocked email.EmailForwarder
//		mockedEmailForwarder := &EmailForwarderMock{
//			ForwardEmailFunc: func(ctx context.Context, fromAddr string, originalRecipient string, subject string, forwardTo []string) error {
//				panic("mock out the ForwardEmail method")
//			},
//		}
//
//		// use mockedEmailForwarder in code that requires email.EmailForwarder
//		// and then make assertions.
//
//	}
type EmailForwarderMock struct {
	// ForwardEmailFunc mocks the ForwardEmail method.
	ForwardEmailFunc func(ctx context.Context, fromAddr string, originalRecipient string, subject string, forwardTo []string) error

	// calls tracks calls to the methods.
	calls struct {
		// ForwardEmail holds details about calls to the ForwardEmail method.
		ForwardEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FromAddr is the fromAddr argument value.
			FromAddr string
			// OriginalRecipient is the originalRecipient argument value.
			OriginalRecipient string
			// Subject is the subject argument value.
			Subject string
			// ForwardTo is the forwardTo argument value.
			ForwardTo []string
		}
	}
	lockForwardEmail sync.RWMutex
}

// ForwardEmail calls ForwardEmailFunc.
func (mock *EmailForwarderMock) ForwardEmail(ctx context.Context, fromAddr string, originalRecipient string, subject string, forwardTo []string) error {
	callInfo := struct {
		Ctx               context.Context
		FromAddr          string
		OriginalRecipient string
		Subject           string
		ForwardTo         []string
	}{
		Ctx:               ctx,
		FromAddr:          fromAddr,
		OriginalRecipient: originalRecipient,
		Subject:           subject,
		ForwardTo:         forwardTo,
	}
	mock.lockForwardEmail.Lock()
	mock.calls.ForwardEmail = append(mock.calls.ForwardEmail, callInfo)
	mock.lockForwardEmail.Unlock()
	if mock.ForwardEmailFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.ForwardEmailFunc(ctx, fromAddr, originalRecipient, subject, forwardTo)
}

// ForwardEmailCalls gets all the calls that were made to ForwardEmail.
// Check the length with:
//
//	len(mockedEmailForwarder.ForwardEmailCalls())
func (mock *EmailForwarderMock) ForwardEmailCalls() []struct {
	Ctx               context.Context
	FromAddr          string
	OriginalRecipient string
	Subject           string
	ForwardTo         []string
} {
	var calls []struct {
		Ctx               context.Context
		FromAddr          string
		OriginalRecipient string
		Subject           string
		ForwardTo         []string
	}
	mock.lockForwardEmail.RLock()
	calls = mock.calls.ForwardEmail
	mock.lockForwardEmail.RUnlock()
	return calls
}
