// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/mailvault/mailvault/domain/email"
	"github.com/mailvault/mailvault/domain/entities"
	"sync"

	"github.com/gofrs/uuid/v5"
)

// ReceivedEmailRepositoryMock is a mock implementation of email.ReceivedEmailRepository.
//
//	func TestSomethingThatUsesReceivedEmailRepository(t *testing.T) {
//
//		// make and configure a mocked email.ReceivedEmailRepository
//		mockedReceivedEmailRepository := &ReceivedEmailRepositoryMock{
//			CountFunc: func(ctx context.Context, emailAddressID uuid.UUID) (int64, error) {
//				panic("mock out the Count method")
//			},
//			CreateFunc: func(ctx context.Context, email *entities.ReceivedEmail) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the Delete method")
//			},
//			GetByEmailAddressIDFunc: func(ctx context.Context, emailAddressID uuid.UUID, limit int, offset int) ([]*entities.ReceivedEmail, error) {
//				panic("mock out the GetByEmailAddressID method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*entities.ReceivedEmail, error) {
//				panic("mock out the GetByID method")
//			},
//			GetByUserIDFunc: func(ctx context.Context, userID uuid.UUID, limit int, offset int, domain string) ([]*entities.ReceivedEmail, int, error) {
//				panic("mock out the GetByUserID method")
//			},
//			GetByUserIDWithFilterFunc: func(ctx context.Context, userID uuid.UUID, limit int, offset int, filter email.GetReceivedEmailsFilter) ([]*entities.ReceivedEmail, int, error) {
//				panic("mock out the GetByUserIDWithFilter method")
//			},
//		}
//
//		// use mockedReceivedEmailRepository in code that requires email.ReceivedEmailRepository
//		// and then make assertions.
//
//	}
type ReceivedEmailRepositoryMock struct {
	// CountFunc mocks the Count method.
	CountFunc func(ctx context.Context, emailAddressID uuid.UUID) (int64, error)

	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, email *entities.ReceivedEmail) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id uuid.UUID) error

	// GetByEmailAddressIDFunc mocks the GetByEmailAddressID method.
	GetByEmailAddressIDFunc func(ctx context.Context, emailAddressID uuid.UUID, limit int, offset int) ([]*entities.ReceivedEmail, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*entities.ReceivedEmail, error)

	// GetByUserIDFunc mocks the GetByUserID method.
	GetByUserIDFunc func(ctx context.Context, userID uuid.UUID, limit int, offset int, domain string) ([]*entities.ReceivedEmail, int, error)

	// GetByUserIDWithFilterFunc mocks the GetByUserIDWithFilter method.
	GetByUserIDWithFilterFunc func(ctx context.Context, userID uuid.UUID, limit int, offset int, filter email.GetReceivedEmailsFilter) ([]*entities.ReceivedEmail, int, error)

	// calls tracks calls to the methods.
	calls struct {
		// Count holds details about calls to the Count method.
		Count []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// EmailAddressID is the emailAddressID argument value.
			EmailAddressID uuid.UUID
		}
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email *entities.ReceivedEmail
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetByEmailAddressID holds details about calls to the GetByEmailAddressID method.
		GetByEmailAddressID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// EmailAddressID is the emailAddressID argument value.
			EmailAddressID uuid.UUID
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetByUserID holds details about calls to the GetByUserID method.
		GetByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
			// Domain is the domain argument value.
			Domain string
		}
		// GetByUserIDWithFilter holds details about calls to the GetByUserIDWithFilter method.
		GetByUserIDWithFilter []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
			// Filter is the filter argument value.
			Filter email.GetReceivedEmailsFilter
		}
	}
	lockCount                 sync.RWMutex
	lockCreate                sync.RWMutex
	lockDelete                sync.RWMutex
	lockGetByEmailAddressID   sync.RWMutex
	lockGetByID               sync.RWMutex
	lockGetByUserID           sync.RWMutex
	lockGetByUserIDWithFilter sync.RWMutex
}

// Count calls CountFunc.
func (mock *ReceivedEmailRepositoryMock) Count(ctx context.Context, emailAddressID uuid.UUID) (int64, error) {
	callInfo := struct {
		Ctx            context.Context
		EmailAddressID uuid.UUID
	}{
		Ctx:            ctx,
		EmailAddressID: emailAddressID,
	}
	mock.lockCount.Lock()
	mock.calls.Count = append(mock.calls.Count, callInfo)
	mock.lockCount.Unlock()
	if mock.CountFunc == nil {
		var (
			nOut   int64
			errOut error
		)
		return nOut, errOut
	}
	return mock.CountFunc(ctx, emailAddressID)
}

// CountCalls gets all the calls that were made to Count.
// Check the length with:
//
//	len(mockedReceivedEmailRepository.CountCalls())
func (mock *ReceivedEmailRepositoryMock) CountCalls() []struct {
	Ctx            context.Context
	EmailAddressID uuid.UUID
} {
	var calls []struct {
		Ctx            context.Context
		EmailAddressID uuid.UUID
	}
	mock.lockCount.RLock()
	calls = mock.calls.Count
	mock.lockCount.RUnlock()
	return calls
}

// Create calls CreateFunc.
func (mock *ReceivedEmailRepositoryMock) Create(ctx context.Context, email *entities.ReceivedEmail) error {
	callInfo := struct {
		Ctx   context.Context
		Email *entities.ReceivedEmail
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CreateFunc(ctx, email)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedReceivedEmailRepository.CreateCalls())
func (mock *ReceivedEmailRepositoryMock) CreateCalls() []struct {
	Ctx   context.Context
	Email *entities.ReceivedEmail
} {
	var calls []struct {
		Ctx   context.Context
		Email *entities.ReceivedEmail
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *ReceivedEmailRepositoryMock) Delete(ctx context.Context, id uuid.UUID) error {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedReceivedEmailRepository.DeleteCalls())
func (mock *ReceivedEmailRepositoryMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetByEmailAddressID calls GetByEmailAddressIDFunc.
func (mock *ReceivedEmailRepositoryMock) GetByEmailAddressID(ctx context.Context, emailAddressID uuid.UUID, limit int, offset int) ([]*entities.ReceivedEmail, error) {
	callInfo := struct {
		Ctx            context.Context
		EmailAddressID uuid.UUID
		Limit          int
		Offset         int
	}{
		Ctx:            ctx,
		EmailAddressID: emailAddressID,
		Limit:          limit,
		Offset:         offset,
	}
	mock.lockGetByEmailAddressID.Lock()
	mock.calls.GetByEmailAddressID = append(mock.calls.GetByEmailAddressID, callInfo)
	mock.lockGetByEmailAddressID.Unlock()
	if mock.GetByEmailAddressIDFunc == nil {
		var (
			receivedEmailsOut []*entities.ReceivedEmail
			errOut            error
		)
		return receivedEmailsOut, errOut
	}
	return mock.GetByEmailAddressIDFunc(ctx, emailAddressID, limit, offset)
}

// GetByEmailAddressIDCalls gets all the calls that were made to GetByEmailAddressID.
// Check the length with:
//
//	len(mockedReceivedEmailRepository.GetByEmailAddressIDCalls())
func (mock *ReceivedEmailRepositoryMock) GetByEmailAddressIDCalls() []struct {
	Ctx            context.Context
	EmailAddressID uuid.UUID
	Limit          int
	Offset         int
} {
	var calls []struct {
		Ctx            context.Context
		EmailAddressID uuid.UUID
		Limit          int
		Offset         int
	}
	mock.lockGetByEmailAddressID.RLock()
	calls = mock.calls.GetByEmailAddressID
	mock.lockGetByEmailAddressID.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *ReceivedEmailRepositoryMock) GetByID(ctx context.Context, id uuid.UUID) (*entities.ReceivedEmail, error) {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	if mock.GetByIDFunc == nil {
		var (
			receivedEmailOut *entities.ReceivedEmail
			errOut           error
		)
		return receivedEmailOut, errOut
	}
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedReceivedEmailRepository.GetByIDCalls())
func (mock *ReceivedEmailRepositoryMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetByUserID calls GetByUserIDFunc.
func (mock *ReceivedEmailRepositoryMock) GetByUserID(ctx context.Context, userID uuid.UUID, limit int, offset int, domain string) ([]*entities.ReceivedEmail, int, error) {
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
		Limit  int
		Offset int
		Domain string
	}{
		Ctx:    ctx,
		UserID: userID,
		Limit:  limit,
		Offset: offset,
		Domain: domain,
	}
	mock.lockGetByUserID.Lock()
	mock.calls.GetByUserID = append(mock.calls.GetByUserID, callInfo)
	mock.lockGetByUserID.Unlock()
	if mock.GetByUserIDFunc == nil {
		var (
			receivedEmailsOut []*entities.ReceivedEmail
			nOut              int
			errOut            error
		)
		return receivedEmailsOut, nOut, errOut
	}
	return mock.GetByUserIDFunc(ctx, userID, limit, offset, domain)
}

// GetByUserIDCalls gets all the calls that were made to GetByUserID.
// Check the length with:
//
//	len(mockedReceivedEmailRepository.GetByUserIDCalls())
func (mock *ReceivedEmailRepositoryMock) GetByUserIDCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
	Limit  int
	Offset int
	Domain string
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
		Limit  int
		Offset int
		Domain string
	}
	mock.lockGetByUserID.RLock()
	calls = mock.calls.GetByUserID
	mock.lockGetByUserID.RUnlock()
	return calls
}

// GetByUserIDWithFilter calls GetByUserIDWithFilterFunc.
func (mock *ReceivedEmailRepositoryMock) GetByUserIDWithFilter(ctx context.Context, userID uuid.UUID, limit int, offset int, filter email.GetReceivedEmailsFilter) ([]*entities.ReceivedEmail, int, error) {
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
		Limit  int
		Offset int
		Filter email.GetReceivedEmailsFilter
	}{
		Ctx:    ctx,
		UserID: userID,
		Limit:  limit,
		Offset: offset,
		Filter: filter,
	}
	mock.lockGetByUserIDWithFilter.Lock()
	mock.calls.GetByUserIDWithFilter = append(mock.calls.GetByUserIDWithFilter, callInfo)
	mock.lockGetByUserIDWithFilter.Unlock()
	if mock.GetByUserIDWithFilterFunc == nil {
		var (
			receivedEmailsOut []*entities.ReceivedEmail
			nOut              int
			errOut            error
		)
		return receivedEmailsOut, nOut, errOut
	}
	return mock.GetByUserIDWithFilterFunc(ctx, userID, limit, offset, filter)
}

// GetByUserIDWithFilterCalls gets all the calls that were made to GetByUserIDWithFilter.
// Check the length with:
//
//	len(mockedReceivedEmailRepository.GetByUserIDWithFilterCalls())
func (mock *ReceivedEmailRepositoryMock) GetByUserIDWithFilterCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
	Limit  int
	Offset int
	Filter email.GetReceivedEmailsFilter
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
		Limit  int
		Offset int
		Filter email.GetReceivedEmailsFilter
	}
	mock.lockGetByUserIDWithFilter.RLock()
	calls = mock.calls.GetByUserIDWithFilter
	mock.lockGetByUserIDWithFilter.RUnlock()
	return calls
}
