// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/mailvault/mailvault/app/smtp/verification"
	"github.com/mailvault/mailvault/domain/entities"
	"sync"
)

// WebhookNotifierMock is a mock implementation of email.WebhookNotifier.
//
//	func TestSomethingThatUsesWebhookNotifier(t *testing.T) {
//
//		// make and configure a mocked email.WebhookNotifier
//		mockedWebhookNotifier := &WebhookNotifierMock{
//			NotifyIncomingEmailFunc: func(ctx context.Context, receivedEmail *entities.ReceivedEmail, domain *entities.Domain, emailAddress *entities.EmailAddress, verificationResult *verification.VerificationResult, autoCreated bool) error {
//				panic("mock out the NotifyIncomingEmail method")
//			},
//		}
//
//		// use mockedWebhookNotifier in code that requires email.WebhookNotifier
//		// and then make assertions.
//
//	}
type WebhookNotifierMock struct {
	// NotifyIncomingEmailFunc mocks the NotifyIncomingEmail method.
	NotifyIncomingEmailFunc func(ctx context.Context, receivedEmail *entities.ReceivedEmail, domain *entities.Domain, emailAddress *entities.EmailAddress, verificationResult *verification.VerificationResult, autoCreated bool) error

	// calls tracks calls to the methods.
	calls struct {
		// NotifyIncomingEmail holds details about calls to the NotifyIncomingEmail method.
		NotifyIncomingEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReceivedEmail is the receivedEmail argument value.
			ReceivedEmail *entities.ReceivedEmail
			// Domain is the domain argument value.
			Domain *entities.Domain
			// EmailAddress is the emailAddress argument value.
			EmailAddress *entities.EmailAddress
			// VerificationResult is the verificationResult argument value.
			VerificationResult *verification.VerificationResult
			// AutoCreated is the autoCreated argument value.
			AutoCreated bool
		}
	}
	lockNotifyIncomingEmail sync.RWMutex
}

// NotifyIncomingEmail calls NotifyIncomingEmailFunc.
func (mock *WebhookNotifierMock) NotifyIncomingEmail(ctx context.Context, receivedEmail *entities.ReceivedEmail, domain *entities.Domain, emailAddress *entities.EmailAddress, verificationResult *verification.VerificationResult, autoCreated bool) error {
	callInfo := struct {
		Ctx                context.Context
		ReceivedEmail      *entities.ReceivedEmail
		Domain             *entities.Domain
		EmailAddress       *entities.EmailAddress
		VerificationResult *verification.VerificationResult
		AutoCreated        bool
	}{
		Ctx:                ctx,
		ReceivedEmail:      receivedEmail,
		Domain:             domain,
		EmailAddress:       emailAddress,
		VerificationResult: verificationResult,
		AutoCreated:        autoCreated,
	}
	mock.lockNotifyIncomingEmail.Lock()
	mock.calls.NotifyIncomingEmail = append(mock.calls.NotifyIncomingEmail, callInfo)
	mock.lockNotifyIncomingEmail.Unlock()
	if mock.NotifyIncomingEmailFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.NotifyIncomingEmailFunc(ctx, receivedEmail, domain, emailAddress, verificationResult, autoCreated)
}

// NotifyIncomingEmailCalls gets all the calls that were made to NotifyIncomingEmail.
// Check the length with:
//
//	len(mockedWebhookNotifier.NotifyIncomingEmailCalls())
func (mock *WebhookNotifierMock) NotifyIncomingEmailCalls() []struct {
	Ctx                context.Context
	ReceivedEmail      *entities.ReceivedEmail
	Domain             *entities.Domain
	EmailAddress       *entities.EmailAddress
	VerificationResult *verification.VerificationResult
	AutoCreated        bool
} {
	var calls []struct {
		Ctx                context.Context
		ReceivedEmail      *entities.ReceivedEmail
		Domain             *entities.Domain
		EmailAddress       *entities.EmailAddress
		VerificationResult *verification.VerificationResult
		AutoCreated        bool
	}
	mock.lockNotifyIncomingEmail.RLock()
	calls = mock.calls.NotifyIncomingEmail
	mock.lockNotifyIncomingEmail.RUnlock()
	return calls
}
