// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/gofrs/uuid/v5"
	"mailvault/domain/email_sending"
	"mailvault/domain/entities"
	"sync"
	"time"
)

// RepositoryMock is a mock implementation of email_sending.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked email_sending.Repository
//		mockedRepository := &RepositoryMock{
//			BulkUpdateStatusFunc: func(ctx context.Context, emailIDs []uuid.UUID, status entities.EmailSendStatus) error {
//				panic("mock out the BulkUpdateStatus method")
//			},
//			CountSentEmailsByDomainFunc: func(ctx context.Context, domainID uuid.UUID) (int64, error) {
//				panic("mock out the CountSentEmailsByDomain method")
//			},
//			CreateSentEmailFunc: func(ctx context.Context, sentEmail *entities.SentEmail) error {
//				panic("mock out the CreateSentEmail method")
//			},
//			DeleteOldSentEmailsFunc: func(ctx context.Context, olderThan time.Time) (int64, error) {
//				panic("mock out the DeleteOldSentEmails method")
//			},
//			DeleteSentEmailFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the DeleteSentEmail method")
//			},
//			GetSentEmailFunc: func(ctx context.Context, id uuid.UUID) (*entities.SentEmail, error) {
//				panic("mock out the GetSentEmail method")
//			},
//			GetSentEmailByMessageIDFunc: func(ctx context.Context, messageID string) (*entities.SentEmail, error) {
//				panic("mock out the GetSentEmailByMessageID method")
//			},
//			GetSentEmailStatsFunc: func(ctx context.Context, filters *email_sending.SentEmailStatsFilters) (*email_sending.SentEmailStats, error) {
//				panic("mock out the GetSentEmailStats method")
//			},
//			GetSentEmailsByDomainFunc: func(ctx context.Context, domainID uuid.UUID, limit int, offset int) ([]*entities.SentEmail, error) {
//				panic("mock out the GetSentEmailsByDomain method")
//			},
//			GetSentEmailsForRetryFunc: func(ctx context.Context, limit int) ([]*entities.SentEmail, error) {
//				panic("mock out the GetSentEmailsForRetry method")
//			},
//			GetSentEmailsNeedingWebhookFunc: func(ctx context.Context, limit int) ([]*entities.SentEmail, error) {
//				panic("mock out the GetSentEmailsNeedingWebhook method")
//			},
//			GetSentEmailsOlderThanFunc: func(ctx context.Context, duration time.Duration, limit int) ([]*entities.SentEmail, error) {
//				panic("mock out the GetSentEmailsOlderThan method")
//			},
//			GetSentEmailsPendingSendFunc: func(ctx context.Context, limit int) ([]*entities.SentEmail, error) {
//				panic("mock out the GetSentEmailsPendingSend method")
//			},
//			ListSentEmailsFunc: func(ctx context.Context, filters *email_sending.SentEmailFilters) ([]*entities.SentEmail, int64, error) {
//				panic("mock out the ListSentEmails method")
//			},
//			UpdateSentEmailFunc: func(ctx context.Context, sentEmail *entities.SentEmail) error {
//				panic("mock out the UpdateSentEmail method")
//			},
//			UpdateSentEmailStatusFunc: func(ctx context.Context, id uuid.UUID, status entities.EmailSendStatus, smtpResponse *string, smtpMessageID *string, errorMessage *string) error {
//				panic("mock out the UpdateSentEmailStatus method")
//			},
//			UpdateWebhookDeliveryFunc: func(ctx context.Context, id uuid.UUID, delivered bool, attempts int) error {
//				panic("mock out the UpdateWebhookDelivery method")
//			},
//		}
//
//		// use mockedRepository in code that requires email_sending.Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// BulkUpdateStatusFunc mocks the BulkUpdateStatus method.
	BulkUpdateStatusFunc func(ctx context.Context, emailIDs []uuid.UUID, status entities.EmailSendStatus) error

	// CountSentEmailsByDomainFunc mocks the CountSentEmailsByDomain method.
	CountSentEmailsByDomainFunc func(ctx context.Context, domainID uuid.UUID) (int64, error)

	// CreateSentEmailFunc mocks the CreateSentEmail method.
	CreateSentEmailFunc func(ctx context.Context, sentEmail *entities.SentEmail) error

	// DeleteOldSentEmailsFunc mocks the DeleteOldSentEmails method.
	DeleteOldSentEmailsFunc func(ctx context.Context, olderThan time.Time) (int64, error)

	// DeleteSentEmailFunc mocks the DeleteSentEmail method.
	DeleteSentEmailFunc func(ctx context.Context, id uuid.UUID) error

	// GetSentEmailFunc mocks the GetSentEmail method.
	GetSentEmailFunc func(ctx context.Context, id uuid.UUID) (*entities.SentEmail, error)

	// GetSentEmailByMessageIDFunc mocks the GetSentEmailByMessageID method.
	GetSentEmailByMessageIDFunc func(ctx context.Context, messageID string) (*entities.SentEmail, error)

	// GetSentEmailStatsFunc mocks the GetSentEmailStats method.
	GetSentEmailStatsFunc func(ctx context.Context, filters *email_sending.SentEmailStatsFilters) (*email_sending.SentEmailStats, error)

	// GetSentEmailsByDomainFunc mocks the GetSentEmailsByDomain method.
	GetSentEmailsByDomainFunc func(ctx context.Context, domainID uuid.UUID, limit int, offset int) ([]*entities.SentEmail, error)

	// GetSentEmailsForRetryFunc mocks the GetSentEmailsForRetry method.
	GetSentEmailsForRetryFunc func(ctx context.Context, limit int) ([]*entities.SentEmail, error)

	// GetSentEmailsNeedingWebhookFunc mocks the GetSentEmailsNeedingWebhook method.
	GetSentEmailsNeedingWebhookFunc func(ctx context.Context, limit int) ([]*entities.SentEmail, error)

	// GetSentEmailsOlderThanFunc mocks the GetSentEmailsOlderThan method.
	GetSentEmailsOlderThanFunc func(ctx context.Context, duration time.Duration, limit int) ([]*entities.SentEmail, error)

	// GetSentEmailsPendingSendFunc mocks the GetSentEmailsPendingSend method.
	GetSentEmailsPendingSendFunc func(ctx context.Context, limit int) ([]*entities.SentEmail, error)

	// ListSentEmailsFunc mocks the ListSentEmails method.
	ListSentEmailsFunc func(ctx context.Context, filters *email_sending.SentEmailFilters) ([]*entities.SentEmail, int64, error)

	// UpdateSentEmailFunc mocks the UpdateSentEmail method.
	UpdateSentEmailFunc func(ctx context.Context, sentEmail *entities.SentEmail) error

	// UpdateSentEmailStatusFunc mocks the UpdateSentEmailStatus method.
	UpdateSentEmailStatusFunc func(ctx context.Context, id uuid.UUID, status entities.EmailSendStatus, smtpResponse *string, smtpMessageID *string, errorMessage *string) error

	// UpdateWebhookDeliveryFunc mocks the UpdateWebhookDelivery method.
	UpdateWebhookDeliveryFunc func(ctx context.Context, id uuid.UUID, delivered bool, attempts int) error

	// calls tracks calls to the methods.
	calls struct {
		// BulkUpdateStatus holds details about calls to the BulkUpdateStatus method.
		BulkUpdateStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// EmailIDs is the emailIDs argument value.
			EmailIDs []uuid.UUID
			// Status is the status argument value.
			Status entities.EmailSendStatus
		}
		// CountSentEmailsByDomain holds details about calls to the CountSentEmailsByDomain method.
		CountSentEmailsByDomain []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DomainID is the domainID argument value.
			DomainID uuid.UUID
		}
		// CreateSentEmail holds details about calls to the CreateSentEmail method.
		CreateSentEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SentEmail is the sentEmail argument value.
			SentEmail *entities.SentEmail
		}
		// DeleteOldSentEmails holds details about calls to the DeleteOldSentEmails method.
		DeleteOldSentEmails []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OlderThan is the olderThan argument value.
			OlderThan time.Time
		}
		// DeleteSentEmail holds details about calls to the DeleteSentEmail method.
		DeleteSentEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetSentEmail holds details about calls to the GetSentEmail method.
		GetSentEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetSentEmailByMessageID holds details about calls to the GetSentEmailByMessageID method.
		GetSentEmailByMessageID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// MessageID is the messageID argument value.
			MessageID string
		}
		// GetSentEmailStats holds details about calls to the GetSentEmailStats method.
		GetSentEmailStats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filters is the filters argument value.
			Filters *email_sending.SentEmailStatsFilters
		}
		// GetSentEmailsByDomain holds details about calls to the GetSentEmailsByDomain method.
		GetSentEmailsByDomain []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DomainID is the domainID argument value.
			DomainID uuid.UUID
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// GetSentEmailsForRetry holds details about calls to the GetSentEmailsForRetry method.
		GetSentEmailsForRetry []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
		}
		// GetSentEmailsNeedingWebhook holds details about calls to the GetSentEmailsNeedingWebhook method.
		GetSentEmailsNeedingWebhook []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
		}
		// GetSentEmailsOlderThan holds details about calls to the GetSentEmailsOlderThan method.
		GetSentEmailsOlderThan []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Duration is the duration argument value.
			Duration time.Duration
			// Limit is the limit argument value.
			Limit int
		}
		// GetSentEmailsPendingSend holds details about calls to the GetSentEmailsPendingSend method.
		GetSentEmailsPendingSend []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
		}
		// ListSentEmails holds details about calls to the ListSentEmails method.
		ListSentEmails []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filters is the filters argument value.
			Filters *email_sending.SentEmailFilters
		}
		// UpdateSentEmail holds details about calls to the UpdateSentEmail method.
		UpdateSentEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SentEmail is the sentEmail argument value.
			SentEmail *entities.SentEmail
		}
		// UpdateSentEmailStatus holds details about calls to the UpdateSentEmailStatus method.
		UpdateSentEmailStatus []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// Status is the status argument value.
			Status entities.EmailSendStatus
			// SmtpResponse is the smtpResponse argument value.
			SmtpResponse *string
			// SmtpMessageID is the smtpMessageID argument value.
			SmtpMessageID *string
			// ErrorMessage is the errorMessage argument value.
			ErrorMessage *string
		}
		// UpdateWebhookDelivery holds details about calls to the UpdateWebhookDelivery method.
		UpdateWebhookDelivery []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// Delivered is the delivered argument value.
			Delivered bool
			// Attempts is the attempts argument value.
			Attempts int
		}
	}
	lockBulkUpdateStatus            sync.RWMutex
	lockCountSentEmailsByDomain     sync.RWMutex
	lockCreateSentEmail             sync.RWMutex
	lockDeleteOldSentEmails         sync.RWMutex
	lockDeleteSentEmail             sync.RWMutex
	lockGetSentEmail                sync.RWMutex
	lockGetSentEmailByMessageID     sync.RWMutex
	lockGetSentEmailStats           sync.RWMutex
	lockGetSentEmailsByDomain       sync.RWMutex
	lockGetSentEmailsForRetry       sync.RWMutex
	lockGetSentEmailsNeedingWebhook sync.RWMutex
	lockGetSentEmailsOlderThan      sync.RWMutex
	lockGetSentEmailsPendingSend    sync.RWMutex
	lockListSentEmails              sync.RWMutex
	lockUpdateSentEmail             sync.RWMutex
	lockUpdateSentEmailStatus       sync.RWMutex
	lockUpdateWebhookDelivery       sync.RWMutex
}

// BulkUpdateStatus calls BulkUpdateStatusFunc.
func (mock *RepositoryMock) BulkUpdateStatus(ctx context.Context, emailIDs []uuid.UUID, status entities.EmailSendStatus) error {
	callInfo := struct {
		Ctx      context.Context
		EmailIDs []uuid.UUID
		Status   entities.EmailSendStatus
	}{
		Ctx:      ctx,
		EmailIDs: emailIDs,
		Status:   status,
	}
	mock.lockBulkUpdateStatus.Lock()
	mock.calls.BulkUpdateStatus = append(mock.calls.BulkUpdateStatus, callInfo)
	mock.lockBulkUpdateStatus.Unlock()
	if mock.BulkUpdateStatusFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.BulkUpdateStatusFunc(ctx, emailIDs, status)
}

// BulkUpdateStatusCalls gets all the calls that were made to BulkUpdateStatus.
// Check the length with:
//
//	len(mockedRepository.BulkUpdateStatusCalls())
func (mock *RepositoryMock) BulkUpdateStatusCalls() []struct {
	Ctx      context.Context
	EmailIDs []uuid.UUID
	Status   entities.EmailSendStatus
} {
	var calls []struct {
		Ctx      context.Context
		EmailIDs []uuid.UUID
		Status   entities.EmailSendStatus
	}
	mock.lockBulkUpdateStatus.RLock()
	calls = mock.calls.BulkUpdateStatus
	mock.lockBulkUpdateStatus.RUnlock()
	return calls
}

// CountSentEmailsByDomain calls CountSentEmailsByDomainFunc.
func (mock *RepositoryMock) CountSentEmailsByDomain(ctx context.Context, domainID uuid.UUID) (int64, error) {
	callInfo := struct {
		Ctx      context.Context
		DomainID uuid.UUID
	}{
		Ctx:      ctx,
		DomainID: domainID,
	}
	mock.lockCountSentEmailsByDomain.Lock()
	mock.calls.CountSentEmailsByDomain = append(mock.calls.CountSentEmailsByDomain, callInfo)
	mock.lockCountSentEmailsByDomain.Unlock()
	if mock.CountSentEmailsByDomainFunc == nil {
		var (
			nOut   int64
			errOut error
		)
		return nOut, errOut
	}
	return mock.CountSentEmailsByDomainFunc(ctx, domainID)
}

// CountSentEmailsByDomainCalls gets all the calls that were made to CountSentEmailsByDomain.
// Check the length with:
//
//	len(mockedRepository.CountSentEmailsByDomainCalls())
func (mock *RepositoryMock) CountSentEmailsByDomainCalls() []struct {
	Ctx      context.Context
	DomainID uuid.UUID
} {
	var calls []struct {
		Ctx      context.Context
		DomainID uuid.UUID
	}
	mock.lockCountSentEmailsByDomain.RLock()
	calls = mock.calls.CountSentEmailsByDomain
	mock.lockCountSentEmailsByDomain.RUnlock()
	return calls
}

// CreateSentEmail calls CreateSentEmailFunc.
func (mock *RepositoryMock) CreateSentEmail(ctx context.Context, sentEmail *entities.SentEmail) error {
	callInfo := struct {
		Ctx       context.Context
		SentEmail *entities.SentEmail
	}{
		Ctx:       ctx,
		SentEmail: sentEmail,
	}
	mock.lockCreateSentEmail.Lock()
	mock.calls.CreateSentEmail = append(mock.calls.CreateSentEmail, callInfo)
	mock.lockCreateSentEmail.Unlock()
	if mock.CreateSentEmailFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CreateSentEmailFunc(ctx, sentEmail)
}

// CreateSentEmailCalls gets all the calls that were made to CreateSentEmail.
// Check the length with:
//
//	len(mockedRepository.CreateSentEmailCalls())
func (mock *RepositoryMock) CreateSentEmailCalls() []struct {
	Ctx       context.Context
	SentEmail *entities.SentEmail
} {
	var calls []struct {
		Ctx       context.Context
		SentEmail *entities.SentEmail
	}
	mock.lockCreateSentEmail.RLock()
	calls = mock.calls.CreateSentEmail
	mock.lockCreateSentEmail.RUnlock()
	return calls
}

// DeleteOldSentEmails calls DeleteOldSentEmailsFunc.
func (mock *RepositoryMock) DeleteOldSentEmails(ctx context.Context, olderThan time.Time) (int64, error) {
	callInfo := struct {
		Ctx       context.Context
		OlderThan time.Time
	}{
		Ctx:       ctx,
		OlderThan: olderThan,
	}
	mock.lockDeleteOldSentEmails.Lock()
	mock.calls.DeleteOldSentEmails = append(mock.calls.DeleteOldSentEmails, callInfo)
	mock.lockDeleteOldSentEmails.Unlock()
	if mock.DeleteOldSentEmailsFunc == nil {
		var (
			nOut   int64
			errOut error
		)
		return nOut, errOut
	}
	return mock.DeleteOldSentEmailsFunc(ctx, olderThan)
}

// DeleteOldSentEmailsCalls gets all the calls that were made to DeleteOldSentEmails.
// Check the length with:
//
//	len(mockedRepository.DeleteOldSentEmailsCalls())
func (mock *RepositoryMock) DeleteOldSentEmailsCalls() []struct {
	Ctx       context.Context
	OlderThan time.Time
} {
	var calls []struct {
		Ctx       context.Context
		OlderThan time.Time
	}
	mock.lockDeleteOldSentEmails.RLock()
	calls = mock.calls.DeleteOldSentEmails
	mock.lockDeleteOldSentEmails.RUnlock()
	return calls
}

// DeleteSentEmail calls DeleteSentEmailFunc.
func (mock *RepositoryMock) DeleteSentEmail(ctx context.Context, id uuid.UUID) error {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteSentEmail.Lock()
	mock.calls.DeleteSentEmail = append(mock.calls.DeleteSentEmail, callInfo)
	mock.lockDeleteSentEmail.Unlock()
	if mock.DeleteSentEmailFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteSentEmailFunc(ctx, id)
}

// DeleteSentEmailCalls gets all the calls that were made to DeleteSentEmail.
// Check the length with:
//
//	len(mockedRepository.DeleteSentEmailCalls())
func (mock *RepositoryMock) DeleteSentEmailCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockDeleteSentEmail.RLock()
	calls = mock.calls.DeleteSentEmail
	mock.lockDeleteSentEmail.RUnlock()
	return calls
}

// GetSentEmail calls GetSentEmailFunc.
func (mock *RepositoryMock) GetSentEmail(ctx context.Context, id uuid.UUID) (*entities.SentEmail, error) {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetSentEmail.Lock()
	mock.calls.GetSentEmail = append(mock.calls.GetSentEmail, callInfo)
	mock.lockGetSentEmail.Unlock()
	if mock.GetSentEmailFunc == nil {
		var (
			sentEmailOut *entities.SentEmail
			errOut       error
		)
		return sentEmailOut, errOut
	}
	return mock.GetSentEmailFunc(ctx, id)
}

// GetSentEmailCalls gets all the calls that were made to GetSentEmail.
// Check the length with:
//
//	len(mockedRepository.GetSentEmailCalls())
func (mock *RepositoryMock) GetSentEmailCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetSentEmail.RLock()
	calls = mock.calls.GetSentEmail
	mock.lockGetSentEmail.RUnlock()
	return calls
}

// GetSentEmailByMessageID calls GetSentEmailByMessageIDFunc.
func (mock *RepositoryMock) GetSentEmailByMessageID(ctx context.Context, messageID string) (*entities.SentEmail, error) {
	callInfo := struct {
		Ctx       context.Context
		MessageID string
	}{
		Ctx:       ctx,
		MessageID: messageID,
	}
	mock.lockGetSentEmailByMessageID.Lock()
	mock.calls.GetSentEmailByMessageID = append(mock.calls.GetSentEmailByMessageID, callInfo)
	mock.lockGetSentEmailByMessageID.Unlock()
	if mock.GetSentEmailByMessageIDFunc == nil {
		var (
			sentEmailOut *entities.SentEmail
			errOut       error
		)
		return sentEmailOut, errOut
	}
	return mock.GetSentEmailByMessageIDFunc(ctx, messageID)
}

// GetSentEmailByMessageIDCalls gets all the calls that were made to GetSentEmailByMessageID.
// Check the length with:
//
//	len(mockedRepository.GetSentEmailByMessageIDCalls())
func (mock *RepositoryMock) GetSentEmailByMessageIDCalls() []struct {
	Ctx       context.Context
	MessageID string
} {
	var calls []struct {
		Ctx       context.Context
		MessageID string
	}
	mock.lockGetSentEmailByMessageID.RLock()
	calls = mock.calls.GetSentEmailByMessageID
	mock.lockGetSentEmailByMessageID.RUnlock()
	return calls
}

// GetSentEmailStats calls GetSentEmailStatsFunc.
func (mock *RepositoryMock) GetSentEmailStats(ctx context.Context, filters *email_sending.SentEmailStatsFilters) (*email_sending.SentEmailStats, error) {
	callInfo := struct {
		Ctx     context.Context
		Filters *email_sending.SentEmailStatsFilters
	}{
		Ctx:     ctx,
		Filters: filters,
	}
	mock.lockGetSentEmailStats.Lock()
	mock.calls.GetSentEmailStats = append(mock.calls.GetSentEmailStats, callInfo)
	mock.lockGetSentEmailStats.Unlock()
	if mock.GetSentEmailStatsFunc == nil {
		var (
			sentEmailStatsOut *email_sending.SentEmailStats
			errOut            error
		)
		return sentEmailStatsOut, errOut
	}
	return mock.GetSentEmailStatsFunc(ctx, filters)
}

// GetSentEmailStatsCalls gets all the calls that were made to GetSentEmailStats.
// Check the length with:
//
//	len(mockedRepository.GetSentEmailStatsCalls())
func (mock *RepositoryMock) GetSentEmailStatsCalls() []struct {
	Ctx     context.Context
	Filters *email_sending.SentEmailStatsFilters
} {
	var calls []struct {
		Ctx     context.Context
		Filters *email_sending.SentEmailStatsFilters
	}
	mock.lockGetSentEmailStats.RLock()
	calls = mock.calls.GetSentEmailStats
	mock.lockGetSentEmailStats.RUnlock()
	return calls
}

// GetSentEmailsByDomain calls GetSentEmailsByDomainFunc.
func (mock *RepositoryMock) GetSentEmailsByDomain(ctx context.Context, domainID uuid.UUID, limit int, offset int) ([]*entities.SentEmail, error) {
	callInfo := struct {
		Ctx      context.Context
		DomainID uuid.UUID
		Limit    int
		Offset   int
	}{
		Ctx:      ctx,
		DomainID: domainID,
		Limit:    limit,
		Offset:   offset,
	}
	mock.lockGetSentEmailsByDomain.Lock()
	mock.calls.GetSentEmailsByDomain = append(mock.calls.GetSentEmailsByDomain, callInfo)
	mock.lockGetSentEmailsByDomain.Unlock()
	if mock.GetSentEmailsByDomainFunc == nil {
		var (
			sentEmailsOut []*entities.SentEmail
			errOut        error
		)
		return sentEmailsOut, errOut
	}
	return mock.GetSentEmailsByDomainFunc(ctx, domainID, limit, offset)
}

// GetSentEmailsByDomainCalls gets all the calls that were made to GetSentEmailsByDomain.
// Check the length with:
//
//	len(mockedRepository.GetSentEmailsByDomainCalls())
func (mock *RepositoryMock) GetSentEmailsByDomainCalls() []struct {
	Ctx      context.Context
	DomainID uuid.UUID
	Limit    int
	Offset   int
} {
	var calls []struct {
		Ctx      context.Context
		DomainID uuid.UUID
		Limit    int
		Offset   int
	}
	mock.lockGetSentEmailsByDomain.RLock()
	calls = mock.calls.GetSentEmailsByDomain
	mock.lockGetSentEmailsByDomain.RUnlock()
	return calls
}

// GetSentEmailsForRetry calls GetSentEmailsForRetryFunc.
func (mock *RepositoryMock) GetSentEmailsForRetry(ctx context.Context, limit int) ([]*entities.SentEmail, error) {
	callInfo := struct {
		Ctx   context.Context
		Limit int
	}{
		Ctx:   ctx,
		Limit: limit,
	}
	mock.lockGetSentEmailsForRetry.Lock()
	mock.calls.GetSentEmailsForRetry = append(mock.calls.GetSentEmailsForRetry, callInfo)
	mock.lockGetSentEmailsForRetry.Unlock()
	if mock.GetSentEmailsForRetryFunc == nil {
		var (
			sentEmailsOut []*entities.SentEmail
			errOut        error
		)
		return sentEmailsOut, errOut
	}
	return mock.GetSentEmailsForRetryFunc(ctx, limit)
}

// GetSentEmailsForRetryCalls gets all the calls that were made to GetSentEmailsForRetry.
// Check the length with:
//
//	len(mockedRepository.GetSentEmailsForRetryCalls())
func (mock *RepositoryMock) GetSentEmailsForRetryCalls() []struct {
	Ctx   context.Context
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Limit int
	}
	mock.lockGetSentEmailsForRetry.RLock()
	calls = mock.calls.GetSentEmailsForRetry
	mock.lockGetSentEmailsForRetry.RUnlock()
	return calls
}

// GetSentEmailsNeedingWebhook calls GetSentEmailsNeedingWebhookFunc.
func (mock *RepositoryMock) GetSentEmailsNeedingWebhook(ctx context.Context, limit int) ([]*entities.SentEmail, error) {
	callInfo := struct {
		Ctx   context.Context
		Limit int
	}{
		Ctx:   ctx,
		Limit: limit,
	}
	mock.lockGetSentEmailsNeedingWebhook.Lock()
	mock.calls.GetSentEmailsNeedingWebhook = append(mock.calls.GetSentEmailsNeedingWebhook, callInfo)
	mock.lockGetSentEmailsNeedingWebhook.Unlock()
	if mock.GetSentEmailsNeedingWebhookFunc == nil {
		var (
			sentEmailsOut []*entities.SentEmail
			errOut        error
		)
		return sentEmailsOut, errOut
	}
	return mock.GetSentEmailsNeedingWebhookFunc(ctx, limit)
}

// GetSentEmailsNeedingWebhookCalls gets all the calls that were made to GetSentEmailsNeedingWebhook.
// Check the length with:
//
//	len(mockedRepository.GetSentEmailsNeedingWebhookCalls())
func (mock *RepositoryMock) GetSentEmailsNeedingWebhookCalls() []struct {
	Ctx   context.Context
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Limit int
	}
	mock.lockGetSentEmailsNeedingWebhook.RLock()
	calls = mock.calls.GetSentEmailsNeedingWebhook
	mock.lockGetSentEmailsNeedingWebhook.RUnlock()
	return calls
}

// GetSentEmailsOlderThan calls GetSentEmailsOlderThanFunc.
func (mock *RepositoryMock) GetSentEmailsOlderThan(ctx context.Context, duration time.Duration, limit int) ([]*entities.SentEmail, error) {
	callInfo := struct {
		Ctx      context.Context
		Duration time.Duration
		Limit    int
	}{
		Ctx:      ctx,
		Duration: duration,
		Limit:    limit,
	}
	mock.lockGetSentEmailsOlderThan.Lock()
	mock.calls.GetSentEmailsOlderThan = append(mock.calls.GetSentEmailsOlderThan, callInfo)
	mock.lockGetSentEmailsOlderThan.Unlock()
	if mock.GetSentEmailsOlderThanFunc == nil {
		var (
			sentEmailsOut []*entities.SentEmail
			errOut        error
		)
		return sentEmailsOut, errOut
	}
	return mock.GetSentEmailsOlderThanFunc(ctx, duration, limit)
}

// GetSentEmailsOlderThanCalls gets all the calls that were made to GetSentEmailsOlderThan.
// Check the length with:
//
//	len(mockedRepository.GetSentEmailsOlderThanCalls())
func (mock *RepositoryMock) GetSentEmailsOlderThanCalls() []struct {
	Ctx      context.Context
	Duration time.Duration
	Limit    int
} {
	var calls []struct {
		Ctx      context.Context
		Duration time.Duration
		Limit    int
	}
	mock.lockGetSentEmailsOlderThan.RLock()
	calls = mock.calls.GetSentEmailsOlderThan
	mock.lockGetSentEmailsOlderThan.RUnlock()
	return calls
}

// GetSentEmailsPendingSend calls GetSentEmailsPendingSendFunc.
func (mock *RepositoryMock) GetSentEmailsPendingSend(ctx context.Context, limit int) ([]*entities.SentEmail, error) {
	callInfo := struct {
		Ctx   context.Context
		Limit int
	}{
		Ctx:   ctx,
		Limit: limit,
	}
	mock.lockGetSentEmailsPendingSend.Lock()
	mock.calls.GetSentEmailsPendingSend = append(mock.calls.GetSentEmailsPendingSend, callInfo)
	mock.lockGetSentEmailsPendingSend.Unlock()
	if mock.GetSentEmailsPendingSendFunc == nil {
		var (
			sentEmailsOut []*entities.SentEmail
			errOut        error
		)
		return sentEmailsOut, errOut
	}
	return mock.GetSentEmailsPendingSendFunc(ctx, limit)
}

// GetSentEmailsPendingSendCalls gets all the calls that were made to GetSentEmailsPendingSend.
// Check the length with:
//
//	len(mockedRepository.GetSentEmailsPendingSendCalls())
func (mock *RepositoryMock) GetSentEmailsPendingSendCalls() []struct {
	Ctx   context.Context
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Limit int
	}
	mock.lockGetSentEmailsPendingSend.RLock()
	calls = mock.calls.GetSentEmailsPendingSend
	mock.lockGetSentEmailsPendingSend.RUnlock()
	return calls
}

// ListSentEmails calls ListSentEmailsFunc.
func (mock *RepositoryMock) ListSentEmails(ctx context.Context, filters *email_sending.SentEmailFilters) ([]*entities.SentEmail, int64, error) {
	callInfo := struct {
		Ctx     context.Context
		Filters *email_sending.SentEmailFilters
	}{
		Ctx:     ctx,
		Filters: filters,
	}
	mock.lockListSentEmails.Lock()
	mock.calls.ListSentEmails = append(mock.calls.ListSentEmails, callInfo)
	mock.lockListSentEmails.Unlock()
	if mock.ListSentEmailsFunc == nil {
		var (
			sentEmailsOut []*entities.SentEmail
			nOut          int64
			errOut        error
		)
		return sentEmailsOut, nOut, errOut
	}
	return mock.ListSentEmailsFunc(ctx, filters)
}

// ListSentEmailsCalls gets all the calls that were made to ListSentEmails.
// Check the length with:
//
//	len(mockedRepository.ListSentEmailsCalls())
func (mock *RepositoryMock) ListSentEmailsCalls() []struct {
	Ctx     context.Context
	Filters *email_sending.SentEmailFilters
} {
	var calls []struct {
		Ctx     context.Context
		Filters *email_sending.SentEmailFilters
	}
	mock.lockListSentEmails.RLock()
	calls = mock.calls.ListSentEmails
	mock.lockListSentEmails.RUnlock()
	return calls
}

// UpdateSentEmail calls UpdateSentEmailFunc.
func (mock *RepositoryMock) UpdateSentEmail(ctx context.Context, sentEmail *entities.SentEmail) error {
	callInfo := struct {
		Ctx       context.Context
		SentEmail *entities.SentEmail
	}{
		Ctx:       ctx,
		SentEmail: sentEmail,
	}
	mock.lockUpdateSentEmail.Lock()
	mock.calls.UpdateSentEmail = append(mock.calls.UpdateSentEmail, callInfo)
	mock.lockUpdateSentEmail.Unlock()
	if mock.UpdateSentEmailFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateSentEmailFunc(ctx, sentEmail)
}

// UpdateSentEmailCalls gets all the calls that were made to UpdateSentEmail.
// Check the length with:
//
//	len(mockedRepository.UpdateSentEmailCalls())
func (mock *RepositoryMock) UpdateSentEmailCalls() []struct {
	Ctx       context.Context
	SentEmail *entities.SentEmail
} {
	var calls []struct {
		Ctx       context.Context
		SentEmail *entities.SentEmail
	}
	mock.lockUpdateSentEmail.RLock()
	calls = mock.calls.UpdateSentEmail
	mock.lockUpdateSentEmail.RUnlock()
	return calls
}

// UpdateSentEmailStatus calls UpdateSentEmailStatusFunc.
func (mock *RepositoryMock) UpdateSentEmailStatus(ctx context.Context, id uuid.UUID, status entities.EmailSendStatus, smtpResponse *string, smtpMessageID *string, errorMessage *string) error {
	callInfo := struct {
		Ctx           context.Context
		ID            uuid.UUID
		Status        entities.EmailSendStatus
		SmtpResponse  *string
		SmtpMessageID *string
		ErrorMessage  *string
	}{
		Ctx:           ctx,
		ID:            id,
		Status:        status,
		SmtpResponse:  smtpResponse,
		SmtpMessageID: smtpMessageID,
		ErrorMessage:  errorMessage,
	}
	mock.lockUpdateSentEmailStatus.Lock()
	mock.calls.UpdateSentEmailStatus = append(mock.calls.UpdateSentEmailStatus, callInfo)
	mock.lockUpdateSentEmailStatus.Unlock()
	if mock.UpdateSentEmailStatusFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateSentEmailStatusFunc(ctx, id, status, smtpResponse, smtpMessageID, errorMessage)
}

// UpdateSentEmailStatusCalls gets all the calls that were made to UpdateSentEmailStatus.
// Check the length with:
//
//	len(mockedRepository.UpdateSentEmailStatusCalls())
func (mock *RepositoryMock) UpdateSentEmailStatusCalls() []struct {
	Ctx           context.Context
	ID            uuid.UUID
	Status        entities.EmailSendStatus
	SmtpResponse  *string
	SmtpMessageID *string
	ErrorMessage  *string
} {
	var calls []struct {
		Ctx           context.Context
		ID            uuid.UUID
		Status        entities.EmailSendStatus
		SmtpResponse  *string
		SmtpMessageID *string
		ErrorMessage  *string
	}
	mock.lockUpdateSentEmailStatus.RLock()
	calls = mock.calls.UpdateSentEmailStatus
	mock.lockUpdateSentEmailStatus.RUnlock()
	return calls
}

// UpdateWebhookDelivery calls UpdateWebhookDeliveryFunc.
func (mock *RepositoryMock) UpdateWebhookDelivery(ctx context.Context, id uuid.UUID, delivered bool, attempts int) error {
	callInfo := struct {
		Ctx       context.Context
		ID        uuid.UUID
		Delivered bool
		Attempts  int
	}{
		Ctx:       ctx,
		ID:        id,
		Delivered: delivered,
		Attempts:  attempts,
	}
	mock.lockUpdateWebhookDelivery.Lock()
	mock.calls.UpdateWebhookDelivery = append(mock.calls.UpdateWebhookDelivery, callInfo)
	mock.lockUpdateWebhookDelivery.Unlock()
	if mock.UpdateWebhookDeliveryFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateWebhookDeliveryFunc(ctx, id, delivered, attempts)
}

// UpdateWebhookDeliveryCalls gets all the calls that were made to UpdateWebhookDelivery.
// Check the length with:
//
//	len(mockedRepository.UpdateWebhookDeliveryCalls())
func (mock *RepositoryMock) UpdateWebhookDeliveryCalls() []struct {
	Ctx       context.Context
	ID        uuid.UUID
	Delivered bool
	Attempts  int
} {
	var calls []struct {
		Ctx       context.Context
		ID        uuid.UUID
		Delivered bool
		Attempts  int
	}
	mock.lockUpdateWebhookDelivery.RLock()
	calls = mock.calls.UpdateWebhookDelivery
	mock.lockUpdateWebhookDelivery.RUnlock()
	return calls
}
