// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/gofrs/uuid/v5"
	"mailvault/domain/email"
	"mailvault/domain/entities"
	"sync"
)

// UseCaseMock is a mock implementation of emails.UseCase.
//
//	func TestSomethingThatUsesUseCase(t *testing.T) {
//
//		// make and configure a mocked emails.UseCase
//		mockedUseCase := &UseCaseMock{
//			CreateEmailAddressFromInputFunc: func(ctx context.Context, req email.CreateEmailAddressInput) (*entities.EmailAddress, error) {
//				panic("mock out the CreateEmailAddressFromInput method")
//			},
//			DeleteEmailAddressFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the DeleteEmailAddress method")
//			},
//			DeleteReceivedEmailFunc: func(ctx context.Context, receivedEmailID uuid.UUID, userID uuid.UUID) error {
//				panic("mock out the DeleteReceivedEmail method")
//			},
//			GetDomainByIDFunc: func(ctx context.Context, domainID uuid.UUID) (*entities.Domain, error) {
//				panic("mock out the GetDomainByID method")
//			},
//			GetEmailAddressByAddressFunc: func(ctx context.Context, address string) (*entities.EmailAddress, error) {
//				panic("mock out the GetEmailAddressByAddress method")
//			},
//			GetEmailAddressByIDFunc: func(ctx context.Context, id uuid.UUID) (*entities.EmailAddress, error) {
//				panic("mock out the GetEmailAddressByID method")
//			},
//			GetEmailAddressesByDomainIDFunc: func(ctx context.Context, domainID uuid.UUID) ([]*entities.EmailAddress, error) {
//				panic("mock out the GetEmailAddressesByDomainID method")
//			},
//			GetReceivedEmailByIDFunc: func(ctx context.Context, receivedEmailID uuid.UUID, userID uuid.UUID) (*entities.ReceivedEmail, error) {
//				panic("mock out the GetReceivedEmailByID method")
//			},
//			GetReceivedEmailsFunc: func(ctx context.Context, emailID uuid.UUID, limit int, offset int) ([]*entities.ReceivedEmail, error) {
//				panic("mock out the GetReceivedEmails method")
//			},
//			GetReceivedEmailsByUserFunc: func(ctx context.Context, userID uuid.UUID, limit int, offset int, domain string) ([]*entities.ReceivedEmail, int, error) {
//				panic("mock out the GetReceivedEmailsByUser method")
//			},
//			UpdateEmailAddressFunc: func(ctx context.Context, id uuid.UUID, req email.UpdateEmailAddressInput) (*entities.EmailAddress, error) {
//				panic("mock out the UpdateEmailAddress method")
//			},
//		}
//
//		// use mockedUseCase in code that requires emails.UseCase
//		// and then make assertions.
//
//	}
type UseCaseMock struct {
	// CreateEmailAddressFromInputFunc mocks the CreateEmailAddressFromInput method.
	CreateEmailAddressFromInputFunc func(ctx context.Context, req email.CreateEmailAddressInput) (*entities.EmailAddress, error)

	// DeleteEmailAddressFunc mocks the DeleteEmailAddress method.
	DeleteEmailAddressFunc func(ctx context.Context, id uuid.UUID) error

	// DeleteReceivedEmailFunc mocks the DeleteReceivedEmail method.
	DeleteReceivedEmailFunc func(ctx context.Context, receivedEmailID uuid.UUID, userID uuid.UUID) error

	// GetDomainByIDFunc mocks the GetDomainByID method.
	GetDomainByIDFunc func(ctx context.Context, domainID uuid.UUID) (*entities.Domain, error)

	// GetEmailAddressByAddressFunc mocks the GetEmailAddressByAddress method.
	GetEmailAddressByAddressFunc func(ctx context.Context, address string) (*entities.EmailAddress, error)

	// GetEmailAddressByIDFunc mocks the GetEmailAddressByID method.
	GetEmailAddressByIDFunc func(ctx context.Context, id uuid.UUID) (*entities.EmailAddress, error)

	// GetEmailAddressesByDomainIDFunc mocks the GetEmailAddressesByDomainID method.
	GetEmailAddressesByDomainIDFunc func(ctx context.Context, domainID uuid.UUID) ([]*entities.EmailAddress, error)

	// GetReceivedEmailByIDFunc mocks the GetReceivedEmailByID method.
	GetReceivedEmailByIDFunc func(ctx context.Context, receivedEmailID uuid.UUID, userID uuid.UUID) (*entities.ReceivedEmail, error)

	// GetReceivedEmailsFunc mocks the GetReceivedEmails method.
	GetReceivedEmailsFunc func(ctx context.Context, emailID uuid.UUID, limit int, offset int) ([]*entities.ReceivedEmail, error)

	// GetReceivedEmailsByUserFunc mocks the GetReceivedEmailsByUser method.
	GetReceivedEmailsByUserFunc func(ctx context.Context, userID uuid.UUID, limit int, offset int, domain string) ([]*entities.ReceivedEmail, int, error)

	// UpdateEmailAddressFunc mocks the UpdateEmailAddress method.
	UpdateEmailAddressFunc func(ctx context.Context, id uuid.UUID, req email.UpdateEmailAddressInput) (*entities.EmailAddress, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateEmailAddressFromInput holds details about calls to the CreateEmailAddressFromInput method.
		CreateEmailAddressFromInput []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req email.CreateEmailAddressInput
		}
		// DeleteEmailAddress holds details about calls to the DeleteEmailAddress method.
		DeleteEmailAddress []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// DeleteReceivedEmail holds details about calls to the DeleteReceivedEmail method.
		DeleteReceivedEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReceivedEmailID is the receivedEmailID argument value.
			ReceivedEmailID uuid.UUID
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// GetDomainByID holds details about calls to the GetDomainByID method.
		GetDomainByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DomainID is the domainID argument value.
			DomainID uuid.UUID
		}
		// GetEmailAddressByAddress holds details about calls to the GetEmailAddressByAddress method.
		GetEmailAddressByAddress []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Address is the address argument value.
			Address string
		}
		// GetEmailAddressByID holds details about calls to the GetEmailAddressByID method.
		GetEmailAddressByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetEmailAddressesByDomainID holds details about calls to the GetEmailAddressesByDomainID method.
		GetEmailAddressesByDomainID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DomainID is the domainID argument value.
			DomainID uuid.UUID
		}
		// GetReceivedEmailByID holds details about calls to the GetReceivedEmailByID method.
		GetReceivedEmailByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ReceivedEmailID is the receivedEmailID argument value.
			ReceivedEmailID uuid.UUID
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// GetReceivedEmails holds details about calls to the GetReceivedEmails method.
		GetReceivedEmails []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// EmailID is the emailID argument value.
			EmailID uuid.UUID
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// GetReceivedEmailsByUser holds details about calls to the GetReceivedEmailsByUser method.
		GetReceivedEmailsByUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
			// Domain is the domain argument value.
			Domain string
		}
		// UpdateEmailAddress holds details about calls to the UpdateEmailAddress method.
		UpdateEmailAddress []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// Req is the req argument value.
			Req email.UpdateEmailAddressInput
		}
	}
	lockCreateEmailAddressFromInput sync.RWMutex
	lockDeleteEmailAddress          sync.RWMutex
	lockDeleteReceivedEmail         sync.RWMutex
	lockGetDomainByID               sync.RWMutex
	lockGetEmailAddressByAddress    sync.RWMutex
	lockGetEmailAddressByID         sync.RWMutex
	lockGetEmailAddressesByDomainID sync.RWMutex
	lockGetReceivedEmailByID        sync.RWMutex
	lockGetReceivedEmails           sync.RWMutex
	lockGetReceivedEmailsByUser     sync.RWMutex
	lockUpdateEmailAddress          sync.RWMutex
}

// CreateEmailAddressFromInput calls CreateEmailAddressFromInputFunc.
func (mock *UseCaseMock) CreateEmailAddressFromInput(ctx context.Context, req email.CreateEmailAddressInput) (*entities.EmailAddress, error) {
	callInfo := struct {
		Ctx context.Context
		Req email.CreateEmailAddressInput
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreateEmailAddressFromInput.Lock()
	mock.calls.CreateEmailAddressFromInput = append(mock.calls.CreateEmailAddressFromInput, callInfo)
	mock.lockCreateEmailAddressFromInput.Unlock()
	if mock.CreateEmailAddressFromInputFunc == nil {
		var (
			emailAddressOut *entities.EmailAddress
			errOut          error
		)
		return emailAddressOut, errOut
	}
	return mock.CreateEmailAddressFromInputFunc(ctx, req)
}

// CreateEmailAddressFromInputCalls gets all the calls that were made to CreateEmailAddressFromInput.
// Check the length with:
//
//	len(mockedUseCase.CreateEmailAddressFromInputCalls())
func (mock *UseCaseMock) CreateEmailAddressFromInputCalls() []struct {
	Ctx context.Context
	Req email.CreateEmailAddressInput
} {
	var calls []struct {
		Ctx context.Context
		Req email.CreateEmailAddressInput
	}
	mock.lockCreateEmailAddressFromInput.RLock()
	calls = mock.calls.CreateEmailAddressFromInput
	mock.lockCreateEmailAddressFromInput.RUnlock()
	return calls
}

// DeleteEmailAddress calls DeleteEmailAddressFunc.
func (mock *UseCaseMock) DeleteEmailAddress(ctx context.Context, id uuid.UUID) error {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteEmailAddress.Lock()
	mock.calls.DeleteEmailAddress = append(mock.calls.DeleteEmailAddress, callInfo)
	mock.lockDeleteEmailAddress.Unlock()
	if mock.DeleteEmailAddressFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteEmailAddressFunc(ctx, id)
}

// DeleteEmailAddressCalls gets all the calls that were made to DeleteEmailAddress.
// Check the length with:
//
//	len(mockedUseCase.DeleteEmailAddressCalls())
func (mock *UseCaseMock) DeleteEmailAddressCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockDeleteEmailAddress.RLock()
	calls = mock.calls.DeleteEmailAddress
	mock.lockDeleteEmailAddress.RUnlock()
	return calls
}

// DeleteReceivedEmail calls DeleteReceivedEmailFunc.
func (mock *UseCaseMock) DeleteReceivedEmail(ctx context.Context, receivedEmailID uuid.UUID, userID uuid.UUID) error {
	callInfo := struct {
		Ctx             context.Context
		ReceivedEmailID uuid.UUID
		UserID          uuid.UUID
	}{
		Ctx:             ctx,
		ReceivedEmailID: receivedEmailID,
		UserID:          userID,
	}
	mock.lockDeleteReceivedEmail.Lock()
	mock.calls.DeleteReceivedEmail = append(mock.calls.DeleteReceivedEmail, callInfo)
	mock.lockDeleteReceivedEmail.Unlock()
	if mock.DeleteReceivedEmailFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteReceivedEmailFunc(ctx, receivedEmailID, userID)
}

// DeleteReceivedEmailCalls gets all the calls that were made to DeleteReceivedEmail.
// Check the length with:
//
//	len(mockedUseCase.DeleteReceivedEmailCalls())
func (mock *UseCaseMock) DeleteReceivedEmailCalls() []struct {
	Ctx             context.Context
	ReceivedEmailID uuid.UUID
	UserID          uuid.UUID
} {
	var calls []struct {
		Ctx             context.Context
		ReceivedEmailID uuid.UUID
		UserID          uuid.UUID
	}
	mock.lockDeleteReceivedEmail.RLock()
	calls = mock.calls.DeleteReceivedEmail
	mock.lockDeleteReceivedEmail.RUnlock()
	return calls
}

// GetDomainByID calls GetDomainByIDFunc.
func (mock *UseCaseMock) GetDomainByID(ctx context.Context, domainID uuid.UUID) (*entities.Domain, error) {
	callInfo := struct {
		Ctx      context.Context
		DomainID uuid.UUID
	}{
		Ctx:      ctx,
		DomainID: domainID,
	}
	mock.lockGetDomainByID.Lock()
	mock.calls.GetDomainByID = append(mock.calls.GetDomainByID, callInfo)
	mock.lockGetDomainByID.Unlock()
	if mock.GetDomainByIDFunc == nil {
		var (
			domainOut *entities.Domain
			errOut    error
		)
		return domainOut, errOut
	}
	return mock.GetDomainByIDFunc(ctx, domainID)
}

// GetDomainByIDCalls gets all the calls that were made to GetDomainByID.
// Check the length with:
//
//	len(mockedUseCase.GetDomainByIDCalls())
func (mock *UseCaseMock) GetDomainByIDCalls() []struct {
	Ctx      context.Context
	DomainID uuid.UUID
} {
	var calls []struct {
		Ctx      context.Context
		DomainID uuid.UUID
	}
	mock.lockGetDomainByID.RLock()
	calls = mock.calls.GetDomainByID
	mock.lockGetDomainByID.RUnlock()
	return calls
}

// GetEmailAddressByAddress calls GetEmailAddressByAddressFunc.
func (mock *UseCaseMock) GetEmailAddressByAddress(ctx context.Context, address string) (*entities.EmailAddress, error) {
	callInfo := struct {
		Ctx     context.Context
		Address string
	}{
		Ctx:     ctx,
		Address: address,
	}
	mock.lockGetEmailAddressByAddress.Lock()
	mock.calls.GetEmailAddressByAddress = append(mock.calls.GetEmailAddressByAddress, callInfo)
	mock.lockGetEmailAddressByAddress.Unlock()
	if mock.GetEmailAddressByAddressFunc == nil {
		var (
			emailAddressOut *entities.EmailAddress
			errOut          error
		)
		return emailAddressOut, errOut
	}
	return mock.GetEmailAddressByAddressFunc(ctx, address)
}

// GetEmailAddressByAddressCalls gets all the calls that were made to GetEmailAddressByAddress.
// Check the length with:
//
//	len(mockedUseCase.GetEmailAddressByAddressCalls())
func (mock *UseCaseMock) GetEmailAddressByAddressCalls() []struct {
	Ctx     context.Context
	Address string
} {
	var calls []struct {
		Ctx     context.Context
		Address string
	}
	mock.lockGetEmailAddressByAddress.RLock()
	calls = mock.calls.GetEmailAddressByAddress
	mock.lockGetEmailAddressByAddress.RUnlock()
	return calls
}

// GetEmailAddressByID calls GetEmailAddressByIDFunc.
func (mock *UseCaseMock) GetEmailAddressByID(ctx context.Context, id uuid.UUID) (*entities.EmailAddress, error) {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetEmailAddressByID.Lock()
	mock.calls.GetEmailAddressByID = append(mock.calls.GetEmailAddressByID, callInfo)
	mock.lockGetEmailAddressByID.Unlock()
	if mock.GetEmailAddressByIDFunc == nil {
		var (
			emailAddressOut *entities.EmailAddress
			errOut          error
		)
		return emailAddressOut, errOut
	}
	return mock.GetEmailAddressByIDFunc(ctx, id)
}

// GetEmailAddressByIDCalls gets all the calls that were made to GetEmailAddressByID.
// Check the length with:
//
//	len(mockedUseCase.GetEmailAddressByIDCalls())
func (mock *UseCaseMock) GetEmailAddressByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetEmailAddressByID.RLock()
	calls = mock.calls.GetEmailAddressByID
	mock.lockGetEmailAddressByID.RUnlock()
	return calls
}

// GetEmailAddressesByDomainID calls GetEmailAddressesByDomainIDFunc.
func (mock *UseCaseMock) GetEmailAddressesByDomainID(ctx context.Context, domainID uuid.UUID) ([]*entities.EmailAddress, error) {
	callInfo := struct {
		Ctx      context.Context
		DomainID uuid.UUID
	}{
		Ctx:      ctx,
		DomainID: domainID,
	}
	mock.lockGetEmailAddressesByDomainID.Lock()
	mock.calls.GetEmailAddressesByDomainID = append(mock.calls.GetEmailAddressesByDomainID, callInfo)
	mock.lockGetEmailAddressesByDomainID.Unlock()
	if mock.GetEmailAddressesByDomainIDFunc == nil {
		var (
			emailAddresssOut []*entities.EmailAddress
			errOut           error
		)
		return emailAddresssOut, errOut
	}
	return mock.GetEmailAddressesByDomainIDFunc(ctx, domainID)
}

// GetEmailAddressesByDomainIDCalls gets all the calls that were made to GetEmailAddressesByDomainID.
// Check the length with:
//
//	len(mockedUseCase.GetEmailAddressesByDomainIDCalls())
func (mock *UseCaseMock) GetEmailAddressesByDomainIDCalls() []struct {
	Ctx      context.Context
	DomainID uuid.UUID
} {
	var calls []struct {
		Ctx      context.Context
		DomainID uuid.UUID
	}
	mock.lockGetEmailAddressesByDomainID.RLock()
	calls = mock.calls.GetEmailAddressesByDomainID
	mock.lockGetEmailAddressesByDomainID.RUnlock()
	return calls
}

// GetReceivedEmailByID calls GetReceivedEmailByIDFunc.
func (mock *UseCaseMock) GetReceivedEmailByID(ctx context.Context, receivedEmailID uuid.UUID, userID uuid.UUID) (*entities.ReceivedEmail, error) {
	callInfo := struct {
		Ctx             context.Context
		ReceivedEmailID uuid.UUID
		UserID          uuid.UUID
	}{
		Ctx:             ctx,
		ReceivedEmailID: receivedEmailID,
		UserID:          userID,
	}
	mock.lockGetReceivedEmailByID.Lock()
	mock.calls.GetReceivedEmailByID = append(mock.calls.GetReceivedEmailByID, callInfo)
	mock.lockGetReceivedEmailByID.Unlock()
	if mock.GetReceivedEmailByIDFunc == nil {
		var (
			receivedEmailOut *entities.ReceivedEmail
			errOut           error
		)
		return receivedEmailOut, errOut
	}
	return mock.GetReceivedEmailByIDFunc(ctx, receivedEmailID, userID)
}

// GetReceivedEmailByIDCalls gets all the calls that were made to GetReceivedEmailByID.
// Check the length with:
//
//	len(mockedUseCase.GetReceivedEmailByIDCalls())
func (mock *UseCaseMock) GetReceivedEmailByIDCalls() []struct {
	Ctx             context.Context
	ReceivedEmailID uuid.UUID
	UserID          uuid.UUID
} {
	var calls []struct {
		Ctx             context.Context
		ReceivedEmailID uuid.UUID
		UserID          uuid.UUID
	}
	mock.lockGetReceivedEmailByID.RLock()
	calls = mock.calls.GetReceivedEmailByID
	mock.lockGetReceivedEmailByID.RUnlock()
	return calls
}

// GetReceivedEmails calls GetReceivedEmailsFunc.
func (mock *UseCaseMock) GetReceivedEmails(ctx context.Context, emailID uuid.UUID, limit int, offset int) ([]*entities.ReceivedEmail, error) {
	callInfo := struct {
		Ctx     context.Context
		EmailID uuid.UUID
		Limit   int
		Offset  int
	}{
		Ctx:     ctx,
		EmailID: emailID,
		Limit:   limit,
		Offset:  offset,
	}
	mock.lockGetReceivedEmails.Lock()
	mock.calls.GetReceivedEmails = append(mock.calls.GetReceivedEmails, callInfo)
	mock.lockGetReceivedEmails.Unlock()
	if mock.GetReceivedEmailsFunc == nil {
		var (
			receivedEmailsOut []*entities.ReceivedEmail
			errOut            error
		)
		return receivedEmailsOut, errOut
	}
	return mock.GetReceivedEmailsFunc(ctx, emailID, limit, offset)
}

// GetReceivedEmailsCalls gets all the calls that were made to GetReceivedEmails.
// Check the length with:
//
//	len(mockedUseCase.GetReceivedEmailsCalls())
func (mock *UseCaseMock) GetReceivedEmailsCalls() []struct {
	Ctx     context.Context
	EmailID uuid.UUID
	Limit   int
	Offset  int
} {
	var calls []struct {
		Ctx     context.Context
		EmailID uuid.UUID
		Limit   int
		Offset  int
	}
	mock.lockGetReceivedEmails.RLock()
	calls = mock.calls.GetReceivedEmails
	mock.lockGetReceivedEmails.RUnlock()
	return calls
}

// GetReceivedEmailsByUser calls GetReceivedEmailsByUserFunc.
func (mock *UseCaseMock) GetReceivedEmailsByUser(ctx context.Context, userID uuid.UUID, limit int, offset int, domain string) ([]*entities.ReceivedEmail, int, error) {
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
		Limit  int
		Offset int
		Domain string
	}{
		Ctx:    ctx,
		UserID: userID,
		Limit:  limit,
		Offset: offset,
		Domain: domain,
	}
	mock.lockGetReceivedEmailsByUser.Lock()
	mock.calls.GetReceivedEmailsByUser = append(mock.calls.GetReceivedEmailsByUser, callInfo)
	mock.lockGetReceivedEmailsByUser.Unlock()
	if mock.GetReceivedEmailsByUserFunc == nil {
		var (
			receivedEmailsOut []*entities.ReceivedEmail
			nOut              int
			errOut            error
		)
		return receivedEmailsOut, nOut, errOut
	}
	return mock.GetReceivedEmailsByUserFunc(ctx, userID, limit, offset, domain)
}

// GetReceivedEmailsByUserCalls gets all the calls that were made to GetReceivedEmailsByUser.
// Check the length with:
//
//	len(mockedUseCase.GetReceivedEmailsByUserCalls())
func (mock *UseCaseMock) GetReceivedEmailsByUserCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
	Limit  int
	Offset int
	Domain string
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
		Limit  int
		Offset int
		Domain string
	}
	mock.lockGetReceivedEmailsByUser.RLock()
	calls = mock.calls.GetReceivedEmailsByUser
	mock.lockGetReceivedEmailsByUser.RUnlock()
	return calls
}

// UpdateEmailAddress calls UpdateEmailAddressFunc.
func (mock *UseCaseMock) UpdateEmailAddress(ctx context.Context, id uuid.UUID, req email.UpdateEmailAddressInput) (*entities.EmailAddress, error) {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
		Req email.UpdateEmailAddressInput
	}{
		Ctx: ctx,
		ID:  id,
		Req: req,
	}
	mock.lockUpdateEmailAddress.Lock()
	mock.calls.UpdateEmailAddress = append(mock.calls.UpdateEmailAddress, callInfo)
	mock.lockUpdateEmailAddress.Unlock()
	if mock.UpdateEmailAddressFunc == nil {
		var (
			emailAddressOut *entities.EmailAddress
			errOut          error
		)
		return emailAddressOut, errOut
	}
	return mock.UpdateEmailAddressFunc(ctx, id, req)
}

// UpdateEmailAddressCalls gets all the calls that were made to UpdateEmailAddress.
// Check the length with:
//
//	len(mockedUseCase.UpdateEmailAddressCalls())
func (mock *UseCaseMock) UpdateEmailAddressCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
	Req email.UpdateEmailAddressInput
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
		Req email.UpdateEmailAddressInput
	}
	mock.lockUpdateEmailAddress.RLock()
	calls = mock.calls.UpdateEmailAddress
	mock.lockUpdateEmailAddress.RUnlock()
	return calls
}
