// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/gofrs/uuid/v5"
	"mailvault/domain/email_provider"
	"mailvault/domain/entities"
	"sync"
)

// ProviderUseCaseMock is a mock implementation of admin.ProviderUseCase.
//
//	func TestSomethingThatUsesProviderUseCase(t *testing.T) {
//
//		// make and configure a mocked admin.ProviderUseCase
//		mockedProviderUseCase := &ProviderUseCaseMock{
//			DeleteProviderFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the DeleteProvider method")
//			},
//			GetDomainProvidersFunc: func(ctx context.Context, domainID uuid.UUID) ([]*entities.EmailProvider, error) {
//				panic("mock out the GetDomainProviders method")
//			},
//			GetProviderFunc: func(ctx context.Context, id uuid.UUID) (*entities.EmailProvider, error) {
//				panic("mock out the GetProvider method")
//			},
//			GetProviderStatsFunc: func(ctx context.Context, filters *email_provider.ProviderStatsFilters) ([]*entities.EmailProviderStats, error) {
//				panic("mock out the GetProviderStats method")
//			},
//			ResetProviderHealthFunc: func(ctx context.Context, providerID uuid.UUID) error {
//				panic("mock out the ResetProviderHealth method")
//			},
//			UpdateProviderFunc: func(ctx context.Context, id uuid.UUID, req email_provider.UpdateProviderRequest) (*entities.EmailProvider, error) {
//				panic("mock out the UpdateProvider method")
//			},
//		}
//
//		// use mockedProviderUseCase in code that requires admin.ProviderUseCase
//		// and then make assertions.
//
//	}
type ProviderUseCaseMock struct {
	// DeleteProviderFunc mocks the DeleteProvider method.
	DeleteProviderFunc func(ctx context.Context, id uuid.UUID) error

	// GetDomainProvidersFunc mocks the GetDomainProviders method.
	GetDomainProvidersFunc func(ctx context.Context, domainID uuid.UUID) ([]*entities.EmailProvider, error)

	// GetProviderFunc mocks the GetProvider method.
	GetProviderFunc func(ctx context.Context, id uuid.UUID) (*entities.EmailProvider, error)

	// GetProviderStatsFunc mocks the GetProviderStats method.
	GetProviderStatsFunc func(ctx context.Context, filters *email_provider.ProviderStatsFilters) ([]*entities.EmailProviderStats, error)

	// ResetProviderHealthFunc mocks the ResetProviderHealth method.
	ResetProviderHealthFunc func(ctx context.Context, providerID uuid.UUID) error

	// UpdateProviderFunc mocks the UpdateProvider method.
	UpdateProviderFunc func(ctx context.Context, id uuid.UUID, req email_provider.UpdateProviderRequest) (*entities.EmailProvider, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteProvider holds details about calls to the DeleteProvider method.
		DeleteProvider []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetDomainProviders holds details about calls to the GetDomainProviders method.
		GetDomainProviders []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DomainID is the domainID argument value.
			DomainID uuid.UUID
		}
		// GetProvider holds details about calls to the GetProvider method.
		GetProvider []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetProviderStats holds details about calls to the GetProviderStats method.
		GetProviderStats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filters is the filters argument value.
			Filters *email_provider.ProviderStatsFilters
		}
		// ResetProviderHealth holds details about calls to the ResetProviderHealth method.
		ResetProviderHealth []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ProviderID is the providerID argument value.
			ProviderID uuid.UUID
		}
		// UpdateProvider holds details about calls to the UpdateProvider method.
		UpdateProvider []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// Req is the req argument value.
			Req email_provider.UpdateProviderRequest
		}
	}
	lockDeleteProvider      sync.RWMutex
	lockGetDomainProviders  sync.RWMutex
	lockGetProvider         sync.RWMutex
	lockGetProviderStats    sync.RWMutex
	lockResetProviderHealth sync.RWMutex
	lockUpdateProvider      sync.RWMutex
}

// DeleteProvider calls DeleteProviderFunc.
func (mock *ProviderUseCaseMock) DeleteProvider(ctx context.Context, id uuid.UUID) error {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteProvider.Lock()
	mock.calls.DeleteProvider = append(mock.calls.DeleteProvider, callInfo)
	mock.lockDeleteProvider.Unlock()
	if mock.DeleteProviderFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteProviderFunc(ctx, id)
}

// DeleteProviderCalls gets all the calls that were made to DeleteProvider.
// Check the length with:
//
//	len(mockedProviderUseCase.DeleteProviderCalls())
func (mock *ProviderUseCaseMock) DeleteProviderCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockDeleteProvider.RLock()
	calls = mock.calls.DeleteProvider
	mock.lockDeleteProvider.RUnlock()
	return calls
}

// GetDomainProviders calls GetDomainProvidersFunc.
func (mock *ProviderUseCaseMock) GetDomainProviders(ctx context.Context, domainID uuid.UUID) ([]*entities.EmailProvider, error) {
	callInfo := struct {
		Ctx      context.Context
		DomainID uuid.UUID
	}{
		Ctx:      ctx,
		DomainID: domainID,
	}
	mock.lockGetDomainProviders.Lock()
	mock.calls.GetDomainProviders = append(mock.calls.GetDomainProviders, callInfo)
	mock.lockGetDomainProviders.Unlock()
	if mock.GetDomainProvidersFunc == nil {
		var (
			emailProvidersOut []*entities.EmailProvider
			errOut            error
		)
		return emailProvidersOut, errOut
	}
	return mock.GetDomainProvidersFunc(ctx, domainID)
}

// GetDomainProvidersCalls gets all the calls that were made to GetDomainProviders.
// Check the length with:
//
//	len(mockedProviderUseCase.GetDomainProvidersCalls())
func (mock *ProviderUseCaseMock) GetDomainProvidersCalls() []struct {
	Ctx      context.Context
	DomainID uuid.UUID
} {
	var calls []struct {
		Ctx      context.Context
		DomainID uuid.UUID
	}
	mock.lockGetDomainProviders.RLock()
	calls = mock.calls.GetDomainProviders
	mock.lockGetDomainProviders.RUnlock()
	return calls
}

// GetProvider calls GetProviderFunc.
func (mock *ProviderUseCaseMock) GetProvider(ctx context.Context, id uuid.UUID) (*entities.EmailProvider, error) {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetProvider.Lock()
	mock.calls.GetProvider = append(mock.calls.GetProvider, callInfo)
	mock.lockGetProvider.Unlock()
	if mock.GetProviderFunc == nil {
		var (
			emailProviderOut *entities.EmailProvider
			errOut           error
		)
		return emailProviderOut, errOut
	}
	return mock.GetProviderFunc(ctx, id)
}

// GetProviderCalls gets all the calls that were made to GetProvider.
// Check the length with:
//
//	len(mockedProviderUseCase.GetProviderCalls())
func (mock *ProviderUseCaseMock) GetProviderCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetProvider.RLock()
	calls = mock.calls.GetProvider
	mock.lockGetProvider.RUnlock()
	return calls
}

// GetProviderStats calls GetProviderStatsFunc.
func (mock *ProviderUseCaseMock) GetProviderStats(ctx context.Context, filters *email_provider.ProviderStatsFilters) ([]*entities.EmailProviderStats, error) {
	callInfo := struct {
		Ctx     context.Context
		Filters *email_provider.ProviderStatsFilters
	}{
		Ctx:     ctx,
		Filters: filters,
	}
	mock.lockGetProviderStats.Lock()
	mock.calls.GetProviderStats = append(mock.calls.GetProviderStats, callInfo)
	mock.lockGetProviderStats.Unlock()
	if mock.GetProviderStatsFunc == nil {
		var (
			emailProviderStatssOut []*entities.EmailProviderStats
			errOut                 error
		)
		return emailProviderStatssOut, errOut
	}
	return mock.GetProviderStatsFunc(ctx, filters)
}

// GetProviderStatsCalls gets all the calls that were made to GetProviderStats.
// Check the length with:
//
//	len(mockedProviderUseCase.GetProviderStatsCalls())
func (mock *ProviderUseCaseMock) GetProviderStatsCalls() []struct {
	Ctx     context.Context
	Filters *email_provider.ProviderStatsFilters
} {
	var calls []struct {
		Ctx     context.Context
		Filters *email_provider.ProviderStatsFilters
	}
	mock.lockGetProviderStats.RLock()
	calls = mock.calls.GetProviderStats
	mock.lockGetProviderStats.RUnlock()
	return calls
}

// ResetProviderHealth calls ResetProviderHealthFunc.
func (mock *ProviderUseCaseMock) ResetProviderHealth(ctx context.Context, providerID uuid.UUID) error {
	callInfo := struct {
		Ctx        context.Context
		ProviderID uuid.UUID
	}{
		Ctx:        ctx,
		ProviderID: providerID,
	}
	mock.lockResetProviderHealth.Lock()
	mock.calls.ResetProviderHealth = append(mock.calls.ResetProviderHealth, callInfo)
	mock.lockResetProviderHealth.Unlock()
	if mock.ResetProviderHealthFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.ResetProviderHealthFunc(ctx, providerID)
}

// ResetProviderHealthCalls gets all the calls that were made to ResetProviderHealth.
// Check the length with:
//
//	len(mockedProviderUseCase.ResetProviderHealthCalls())
func (mock *ProviderUseCaseMock) ResetProviderHealthCalls() []struct {
	Ctx        context.Context
	ProviderID uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		ProviderID uuid.UUID
	}
	mock.lockResetProviderHealth.RLock()
	calls = mock.calls.ResetProviderHealth
	mock.lockResetProviderHealth.RUnlock()
	return calls
}

// UpdateProvider calls UpdateProviderFunc.
func (mock *ProviderUseCaseMock) UpdateProvider(ctx context.Context, id uuid.UUID, req email_provider.UpdateProviderRequest) (*entities.EmailProvider, error) {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
		Req email_provider.UpdateProviderRequest
	}{
		Ctx: ctx,
		ID:  id,
		Req: req,
	}
	mock.lockUpdateProvider.Lock()
	mock.calls.UpdateProvider = append(mock.calls.UpdateProvider, callInfo)
	mock.lockUpdateProvider.Unlock()
	if mock.UpdateProviderFunc == nil {
		var (
			emailProviderOut *entities.EmailProvider
			errOut           error
		)
		return emailProviderOut, errOut
	}
	return mock.UpdateProviderFunc(ctx, id, req)
}

// UpdateProviderCalls gets all the calls that were made to UpdateProvider.
// Check the length with:
//
//	len(mockedProviderUseCase.UpdateProviderCalls())
func (mock *ProviderUseCaseMock) UpdateProviderCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
	Req email_provider.UpdateProviderRequest
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
		Req email_provider.UpdateProviderRequest
	}
	mock.lockUpdateProvider.RLock()
	calls = mock.calls.UpdateProvider
	mock.lockUpdateProvider.RUnlock()
	return calls
}
