// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/mailvault/mailvault/domain/entities"
	"sync"

	"github.com/gofrs/uuid/v5"
)

// SMTPStatsUseCaseMock is a mock implementation of admin.SMTPStatsUseCase.
//
//	func TestSomethingThatUsesSMTPStatsUseCase(t *testing.T) {
//
//		// make and configure a mocked admin.SMTPStatsUseCase
//		mockedSMTPStatsUseCase := &SMTPStatsUseCaseMock{
//			GetDistributionsFunc: func(ctx context.Context, filter entities.SMTPStatsFilter) (map[string]interface{}, error) {
//				panic("mock out the GetDistributions method")
//			},
//			GetDomainStatsFunc: func(ctx context.Context, domainID uuid.UUID, filter entities.SMTPStatsFilter, page int, pageSize int) ([]entities.SMTPVerificationStat, int64, error) {
//				panic("mock out the GetDomainStats method")
//			},
//			GetOverviewFunc: func(ctx context.Context, filter entities.SMTPStatsFilter) (*entities.SMTPStatsOverview, error) {
//				panic("mock out the GetOverview method")
//			},
//			GetTimeSeriesDataFunc: func(ctx context.Context, filter entities.SMTPStatsFilter, granularity string) ([]entities.TimeSeriesPoint, error) {
//				panic("mock out the GetTimeSeriesData method")
//			},
//			GetTopSendersFunc: func(ctx context.Context, filter entities.SMTPStatsFilter, limit int) (map[string]interface{}, error) {
//				panic("mock out the GetTopSenders method")
//			},
//		}
//
//		// use mockedSMTPStatsUseCase in code that requires admin.SMTPStatsUseCase
//		// and then make assertions.
//
//	}
type SMTPStatsUseCaseMock struct {
	// GetDistributionsFunc mocks the GetDistributions method.
	GetDistributionsFunc func(ctx context.Context, filter entities.SMTPStatsFilter) (map[string]interface{}, error)

	// GetDomainStatsFunc mocks the GetDomainStats method.
	GetDomainStatsFunc func(ctx context.Context, domainID uuid.UUID, filter entities.SMTPStatsFilter, page int, pageSize int) ([]entities.SMTPVerificationStat, int64, error)

	// GetOverviewFunc mocks the GetOverview method.
	GetOverviewFunc func(ctx context.Context, filter entities.SMTPStatsFilter) (*entities.SMTPStatsOverview, error)

	// GetTimeSeriesDataFunc mocks the GetTimeSeriesData method.
	GetTimeSeriesDataFunc func(ctx context.Context, filter entities.SMTPStatsFilter, granularity string) ([]entities.TimeSeriesPoint, error)

	// GetTopSendersFunc mocks the GetTopSenders method.
	GetTopSendersFunc func(ctx context.Context, filter entities.SMTPStatsFilter, limit int) (map[string]interface{}, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetDistributions holds details about calls to the GetDistributions method.
		GetDistributions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter entities.SMTPStatsFilter
		}
		// GetDomainStats holds details about calls to the GetDomainStats method.
		GetDomainStats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DomainID is the domainID argument value.
			DomainID uuid.UUID
			// Filter is the filter argument value.
			Filter entities.SMTPStatsFilter
			// Page is the page argument value.
			Page int
			// PageSize is the pageSize argument value.
			PageSize int
		}
		// GetOverview holds details about calls to the GetOverview method.
		GetOverview []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter entities.SMTPStatsFilter
		}
		// GetTimeSeriesData holds details about calls to the GetTimeSeriesData method.
		GetTimeSeriesData []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter entities.SMTPStatsFilter
			// Granularity is the granularity argument value.
			Granularity string
		}
		// GetTopSenders holds details about calls to the GetTopSenders method.
		GetTopSenders []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Filter is the filter argument value.
			Filter entities.SMTPStatsFilter
			// Limit is the limit argument value.
			Limit int
		}
	}
	lockGetDistributions  sync.RWMutex
	lockGetDomainStats    sync.RWMutex
	lockGetOverview       sync.RWMutex
	lockGetTimeSeriesData sync.RWMutex
	lockGetTopSenders     sync.RWMutex
}

// GetDistributions calls GetDistributionsFunc.
func (mock *SMTPStatsUseCaseMock) GetDistributions(ctx context.Context, filter entities.SMTPStatsFilter) (map[string]interface{}, error) {
	callInfo := struct {
		Ctx    context.Context
		Filter entities.SMTPStatsFilter
	}{
		Ctx:    ctx,
		Filter: filter,
	}
	mock.lockGetDistributions.Lock()
	mock.calls.GetDistributions = append(mock.calls.GetDistributions, callInfo)
	mock.lockGetDistributions.Unlock()
	if mock.GetDistributionsFunc == nil {
		var (
			stringToIfaceValOut map[string]interface{}
			errOut              error
		)
		return stringToIfaceValOut, errOut
	}
	return mock.GetDistributionsFunc(ctx, filter)
}

// GetDistributionsCalls gets all the calls that were made to GetDistributions.
// Check the length with:
//
//	len(mockedSMTPStatsUseCase.GetDistributionsCalls())
func (mock *SMTPStatsUseCaseMock) GetDistributionsCalls() []struct {
	Ctx    context.Context
	Filter entities.SMTPStatsFilter
} {
	var calls []struct {
		Ctx    context.Context
		Filter entities.SMTPStatsFilter
	}
	mock.lockGetDistributions.RLock()
	calls = mock.calls.GetDistributions
	mock.lockGetDistributions.RUnlock()
	return calls
}

// GetDomainStats calls GetDomainStatsFunc.
func (mock *SMTPStatsUseCaseMock) GetDomainStats(ctx context.Context, domainID uuid.UUID, filter entities.SMTPStatsFilter, page int, pageSize int) ([]entities.SMTPVerificationStat, int64, error) {
	callInfo := struct {
		Ctx      context.Context
		DomainID uuid.UUID
		Filter   entities.SMTPStatsFilter
		Page     int
		PageSize int
	}{
		Ctx:      ctx,
		DomainID: domainID,
		Filter:   filter,
		Page:     page,
		PageSize: pageSize,
	}
	mock.lockGetDomainStats.Lock()
	mock.calls.GetDomainStats = append(mock.calls.GetDomainStats, callInfo)
	mock.lockGetDomainStats.Unlock()
	if mock.GetDomainStatsFunc == nil {
		var (
			sMTPVerificationStatsOut []entities.SMTPVerificationStat
			nOut                     int64
			errOut                   error
		)
		return sMTPVerificationStatsOut, nOut, errOut
	}
	return mock.GetDomainStatsFunc(ctx, domainID, filter, page, pageSize)
}

// GetDomainStatsCalls gets all the calls that were made to GetDomainStats.
// Check the length with:
//
//	len(mockedSMTPStatsUseCase.GetDomainStatsCalls())
func (mock *SMTPStatsUseCaseMock) GetDomainStatsCalls() []struct {
	Ctx      context.Context
	DomainID uuid.UUID
	Filter   entities.SMTPStatsFilter
	Page     int
	PageSize int
} {
	var calls []struct {
		Ctx      context.Context
		DomainID uuid.UUID
		Filter   entities.SMTPStatsFilter
		Page     int
		PageSize int
	}
	mock.lockGetDomainStats.RLock()
	calls = mock.calls.GetDomainStats
	mock.lockGetDomainStats.RUnlock()
	return calls
}

// GetOverview calls GetOverviewFunc.
func (mock *SMTPStatsUseCaseMock) GetOverview(ctx context.Context, filter entities.SMTPStatsFilter) (*entities.SMTPStatsOverview, error) {
	callInfo := struct {
		Ctx    context.Context
		Filter entities.SMTPStatsFilter
	}{
		Ctx:    ctx,
		Filter: filter,
	}
	mock.lockGetOverview.Lock()
	mock.calls.GetOverview = append(mock.calls.GetOverview, callInfo)
	mock.lockGetOverview.Unlock()
	if mock.GetOverviewFunc == nil {
		var (
			sMTPStatsOverviewOut *entities.SMTPStatsOverview
			errOut               error
		)
		return sMTPStatsOverviewOut, errOut
	}
	return mock.GetOverviewFunc(ctx, filter)
}

// GetOverviewCalls gets all the calls that were made to GetOverview.
// Check the length with:
//
//	len(mockedSMTPStatsUseCase.GetOverviewCalls())
func (mock *SMTPStatsUseCaseMock) GetOverviewCalls() []struct {
	Ctx    context.Context
	Filter entities.SMTPStatsFilter
} {
	var calls []struct {
		Ctx    context.Context
		Filter entities.SMTPStatsFilter
	}
	mock.lockGetOverview.RLock()
	calls = mock.calls.GetOverview
	mock.lockGetOverview.RUnlock()
	return calls
}

// GetTimeSeriesData calls GetTimeSeriesDataFunc.
func (mock *SMTPStatsUseCaseMock) GetTimeSeriesData(ctx context.Context, filter entities.SMTPStatsFilter, granularity string) ([]entities.TimeSeriesPoint, error) {
	callInfo := struct {
		Ctx         context.Context
		Filter      entities.SMTPStatsFilter
		Granularity string
	}{
		Ctx:         ctx,
		Filter:      filter,
		Granularity: granularity,
	}
	mock.lockGetTimeSeriesData.Lock()
	mock.calls.GetTimeSeriesData = append(mock.calls.GetTimeSeriesData, callInfo)
	mock.lockGetTimeSeriesData.Unlock()
	if mock.GetTimeSeriesDataFunc == nil {
		var (
			timeSeriesPointsOut []entities.TimeSeriesPoint
			errOut              error
		)
		return timeSeriesPointsOut, errOut
	}
	return mock.GetTimeSeriesDataFunc(ctx, filter, granularity)
}

// GetTimeSeriesDataCalls gets all the calls that were made to GetTimeSeriesData.
// Check the length with:
//
//	len(mockedSMTPStatsUseCase.GetTimeSeriesDataCalls())
func (mock *SMTPStatsUseCaseMock) GetTimeSeriesDataCalls() []struct {
	Ctx         context.Context
	Filter      entities.SMTPStatsFilter
	Granularity string
} {
	var calls []struct {
		Ctx         context.Context
		Filter      entities.SMTPStatsFilter
		Granularity string
	}
	mock.lockGetTimeSeriesData.RLock()
	calls = mock.calls.GetTimeSeriesData
	mock.lockGetTimeSeriesData.RUnlock()
	return calls
}

// GetTopSenders calls GetTopSendersFunc.
func (mock *SMTPStatsUseCaseMock) GetTopSenders(ctx context.Context, filter entities.SMTPStatsFilter, limit int) (map[string]interface{}, error) {
	callInfo := struct {
		Ctx    context.Context
		Filter entities.SMTPStatsFilter
		Limit  int
	}{
		Ctx:    ctx,
		Filter: filter,
		Limit:  limit,
	}
	mock.lockGetTopSenders.Lock()
	mock.calls.GetTopSenders = append(mock.calls.GetTopSenders, callInfo)
	mock.lockGetTopSenders.Unlock()
	if mock.GetTopSendersFunc == nil {
		var (
			stringToIfaceValOut map[string]interface{}
			errOut              error
		)
		return stringToIfaceValOut, errOut
	}
	return mock.GetTopSendersFunc(ctx, filter, limit)
}

// GetTopSendersCalls gets all the calls that were made to GetTopSenders.
// Check the length with:
//
//	len(mockedSMTPStatsUseCase.GetTopSendersCalls())
func (mock *SMTPStatsUseCaseMock) GetTopSendersCalls() []struct {
	Ctx    context.Context
	Filter entities.SMTPStatsFilter
	Limit  int
} {
	var calls []struct {
		Ctx    context.Context
		Filter entities.SMTPStatsFilter
		Limit  int
	}
	mock.lockGetTopSenders.RLock()
	calls = mock.calls.GetTopSenders
	mock.lockGetTopSenders.RUnlock()
	return calls
}
