// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"mailvault/domain/entities"
	"sync"

	"github.com/gofrs/uuid/v5"
)

// RepositoryMock is a mock implementation of webhook_config.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked webhook_config.Repository
//		mockedRepository := &RepositoryMock{
//			CreateFunc: func(ctx context.Context, config *entities.WebhookConfiguration) error {
//				panic("mock out the Create method")
//			},
//			CreateAuditFunc: func(ctx context.Context, audit *entities.WebhookConfigurationAudit) error {
//				panic("mock out the CreateAudit method")
//			},
//			CreateHealthCheckFunc: func(ctx context.Context, check *entities.WebhookHealthCheck) error {
//				panic("mock out the CreateHealthCheck method")
//			},
//			CreateTemplateFunc: func(ctx context.Context, template *entities.WebhookConfigurationTemplate) error {
//				panic("mock out the CreateTemplate method")
//			},
//			DeleteFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the Delete method")
//			},
//			GetActiveByDomainIDFunc: func(ctx context.Context, domainID uuid.UUID) ([]*entities.WebhookConfiguration, error) {
//				panic("mock out the GetActiveByDomainID method")
//			},
//			GetAuditByConfigIDFunc: func(ctx context.Context, configID uuid.UUID, limit int, offset int) ([]*entities.WebhookConfigurationAudit, error) {
//				panic("mock out the GetAuditByConfigID method")
//			},
//			GetByDomainIDFunc: func(ctx context.Context, domainID uuid.UUID) ([]*entities.WebhookConfiguration, error) {
//				panic("mock out the GetByDomainID method")
//			},
//			GetByDomainIDAndNameFunc: func(ctx context.Context, domainID uuid.UUID, name string) (*entities.WebhookConfiguration, error) {
//				panic("mock out the GetByDomainIDAndName method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*entities.WebhookConfiguration, error) {
//				panic("mock out the GetByID method")
//			},
//			GetHealthChecksByConfigIDFunc: func(ctx context.Context, configID uuid.UUID, limit int, offset int) ([]*entities.WebhookHealthCheck, error) {
//				panic("mock out the GetHealthChecksByConfigID method")
//			},
//			GetLatestHealthCheckFunc: func(ctx context.Context, configID uuid.UUID) (*entities.WebhookHealthCheck, error) {
//				panic("mock out the GetLatestHealthCheck method")
//			},
//			GetTemplateByIDFunc: func(ctx context.Context, id uuid.UUID) (*entities.WebhookConfigurationTemplate, error) {
//				panic("mock out the GetTemplateByID method")
//			},
//			GetTemplateByNameFunc: func(ctx context.Context, name string) (*entities.WebhookConfigurationTemplate, error) {
//				panic("mock out the GetTemplateByName method")
//			},
//			GetTemplatesFunc: func(ctx context.Context) ([]*entities.WebhookConfigurationTemplate, error) {
//				panic("mock out the GetTemplates method")
//			},
//			IncrementTemplateUsageFunc: func(ctx context.Context, templateID uuid.UUID) error {
//				panic("mock out the IncrementTemplateUsage method")
//			},
//			ListUnhealthyWebhooksFunc: func(ctx context.Context, limit int) ([]*entities.WebhookConfiguration, error) {
//				panic("mock out the ListUnhealthyWebhooks method")
//			},
//			ListWebhooksForHealthCheckFunc: func(ctx context.Context, olderThan int) ([]*entities.WebhookConfiguration, error) {
//				panic("mock out the ListWebhooksForHealthCheck method")
//			},
//			UpdateFunc: func(ctx context.Context, config *entities.WebhookConfiguration) error {
//				panic("mock out the Update method")
//			},
//			UpdateTemplateFunc: func(ctx context.Context, template *entities.WebhookConfigurationTemplate) error {
//				panic("mock out the UpdateTemplate method")
//			},
//		}
//
//		// use mockedRepository in code that requires webhook_config.Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, config *entities.WebhookConfiguration) error

	// CreateAuditFunc mocks the CreateAudit method.
	CreateAuditFunc func(ctx context.Context, audit *entities.WebhookConfigurationAudit) error

	// CreateHealthCheckFunc mocks the CreateHealthCheck method.
	CreateHealthCheckFunc func(ctx context.Context, check *entities.WebhookHealthCheck) error

	// CreateTemplateFunc mocks the CreateTemplate method.
	CreateTemplateFunc func(ctx context.Context, template *entities.WebhookConfigurationTemplate) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id uuid.UUID) error

	// GetActiveByDomainIDFunc mocks the GetActiveByDomainID method.
	GetActiveByDomainIDFunc func(ctx context.Context, domainID uuid.UUID) ([]*entities.WebhookConfiguration, error)

	// GetAuditByConfigIDFunc mocks the GetAuditByConfigID method.
	GetAuditByConfigIDFunc func(ctx context.Context, configID uuid.UUID, limit int, offset int) ([]*entities.WebhookConfigurationAudit, error)

	// GetByDomainIDFunc mocks the GetByDomainID method.
	GetByDomainIDFunc func(ctx context.Context, domainID uuid.UUID) ([]*entities.WebhookConfiguration, error)

	// GetByDomainIDAndNameFunc mocks the GetByDomainIDAndName method.
	GetByDomainIDAndNameFunc func(ctx context.Context, domainID uuid.UUID, name string) (*entities.WebhookConfiguration, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*entities.WebhookConfiguration, error)

	// GetHealthChecksByConfigIDFunc mocks the GetHealthChecksByConfigID method.
	GetHealthChecksByConfigIDFunc func(ctx context.Context, configID uuid.UUID, limit int, offset int) ([]*entities.WebhookHealthCheck, error)

	// GetLatestHealthCheckFunc mocks the GetLatestHealthCheck method.
	GetLatestHealthCheckFunc func(ctx context.Context, configID uuid.UUID) (*entities.WebhookHealthCheck, error)

	// GetTemplateByIDFunc mocks the GetTemplateByID method.
	GetTemplateByIDFunc func(ctx context.Context, id uuid.UUID) (*entities.WebhookConfigurationTemplate, error)

	// GetTemplateByNameFunc mocks the GetTemplateByName method.
	GetTemplateByNameFunc func(ctx context.Context, name string) (*entities.WebhookConfigurationTemplate, error)

	// GetTemplatesFunc mocks the GetTemplates method.
	GetTemplatesFunc func(ctx context.Context) ([]*entities.WebhookConfigurationTemplate, error)

	// IncrementTemplateUsageFunc mocks the IncrementTemplateUsage method.
	IncrementTemplateUsageFunc func(ctx context.Context, templateID uuid.UUID) error

	// ListUnhealthyWebhooksFunc mocks the ListUnhealthyWebhooks method.
	ListUnhealthyWebhooksFunc func(ctx context.Context, limit int) ([]*entities.WebhookConfiguration, error)

	// ListWebhooksForHealthCheckFunc mocks the ListWebhooksForHealthCheck method.
	ListWebhooksForHealthCheckFunc func(ctx context.Context, olderThan int) ([]*entities.WebhookConfiguration, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, config *entities.WebhookConfiguration) error

	// UpdateTemplateFunc mocks the UpdateTemplate method.
	UpdateTemplateFunc func(ctx context.Context, template *entities.WebhookConfigurationTemplate) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Config is the config argument value.
			Config *entities.WebhookConfiguration
		}
		// CreateAudit holds details about calls to the CreateAudit method.
		CreateAudit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Audit is the audit argument value.
			Audit *entities.WebhookConfigurationAudit
		}
		// CreateHealthCheck holds details about calls to the CreateHealthCheck method.
		CreateHealthCheck []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Check is the check argument value.
			Check *entities.WebhookHealthCheck
		}
		// CreateTemplate holds details about calls to the CreateTemplate method.
		CreateTemplate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Template is the template argument value.
			Template *entities.WebhookConfigurationTemplate
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetActiveByDomainID holds details about calls to the GetActiveByDomainID method.
		GetActiveByDomainID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DomainID is the domainID argument value.
			DomainID uuid.UUID
		}
		// GetAuditByConfigID holds details about calls to the GetAuditByConfigID method.
		GetAuditByConfigID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConfigID is the configID argument value.
			ConfigID uuid.UUID
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// GetByDomainID holds details about calls to the GetByDomainID method.
		GetByDomainID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DomainID is the domainID argument value.
			DomainID uuid.UUID
		}
		// GetByDomainIDAndName holds details about calls to the GetByDomainIDAndName method.
		GetByDomainIDAndName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DomainID is the domainID argument value.
			DomainID uuid.UUID
			// Name is the name argument value.
			Name string
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetHealthChecksByConfigID holds details about calls to the GetHealthChecksByConfigID method.
		GetHealthChecksByConfigID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConfigID is the configID argument value.
			ConfigID uuid.UUID
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// GetLatestHealthCheck holds details about calls to the GetLatestHealthCheck method.
		GetLatestHealthCheck []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConfigID is the configID argument value.
			ConfigID uuid.UUID
		}
		// GetTemplateByID holds details about calls to the GetTemplateByID method.
		GetTemplateByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetTemplateByName holds details about calls to the GetTemplateByName method.
		GetTemplateByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// GetTemplates holds details about calls to the GetTemplates method.
		GetTemplates []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// IncrementTemplateUsage holds details about calls to the IncrementTemplateUsage method.
		IncrementTemplateUsage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TemplateID is the templateID argument value.
			TemplateID uuid.UUID
		}
		// ListUnhealthyWebhooks holds details about calls to the ListUnhealthyWebhooks method.
		ListUnhealthyWebhooks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
		}
		// ListWebhooksForHealthCheck holds details about calls to the ListWebhooksForHealthCheck method.
		ListWebhooksForHealthCheck []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// OlderThan is the olderThan argument value.
			OlderThan int
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Config is the config argument value.
			Config *entities.WebhookConfiguration
		}
		// UpdateTemplate holds details about calls to the UpdateTemplate method.
		UpdateTemplate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Template is the template argument value.
			Template *entities.WebhookConfigurationTemplate
		}
	}
	lockCreate                     sync.RWMutex
	lockCreateAudit                sync.RWMutex
	lockCreateHealthCheck          sync.RWMutex
	lockCreateTemplate             sync.RWMutex
	lockDelete                     sync.RWMutex
	lockGetActiveByDomainID        sync.RWMutex
	lockGetAuditByConfigID         sync.RWMutex
	lockGetByDomainID              sync.RWMutex
	lockGetByDomainIDAndName       sync.RWMutex
	lockGetByID                    sync.RWMutex
	lockGetHealthChecksByConfigID  sync.RWMutex
	lockGetLatestHealthCheck       sync.RWMutex
	lockGetTemplateByID            sync.RWMutex
	lockGetTemplateByName          sync.RWMutex
	lockGetTemplates               sync.RWMutex
	lockIncrementTemplateUsage     sync.RWMutex
	lockListUnhealthyWebhooks      sync.RWMutex
	lockListWebhooksForHealthCheck sync.RWMutex
	lockUpdate                     sync.RWMutex
	lockUpdateTemplate             sync.RWMutex
}

// Create calls CreateFunc.
func (mock *RepositoryMock) Create(ctx context.Context, config *entities.WebhookConfiguration) error {
	callInfo := struct {
		Ctx    context.Context
		Config *entities.WebhookConfiguration
	}{
		Ctx:    ctx,
		Config: config,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CreateFunc(ctx, config)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedRepository.CreateCalls())
func (mock *RepositoryMock) CreateCalls() []struct {
	Ctx    context.Context
	Config *entities.WebhookConfiguration
} {
	var calls []struct {
		Ctx    context.Context
		Config *entities.WebhookConfiguration
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// CreateAudit calls CreateAuditFunc.
func (mock *RepositoryMock) CreateAudit(ctx context.Context, audit *entities.WebhookConfigurationAudit) error {
	callInfo := struct {
		Ctx   context.Context
		Audit *entities.WebhookConfigurationAudit
	}{
		Ctx:   ctx,
		Audit: audit,
	}
	mock.lockCreateAudit.Lock()
	mock.calls.CreateAudit = append(mock.calls.CreateAudit, callInfo)
	mock.lockCreateAudit.Unlock()
	if mock.CreateAuditFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CreateAuditFunc(ctx, audit)
}

// CreateAuditCalls gets all the calls that were made to CreateAudit.
// Check the length with:
//
//	len(mockedRepository.CreateAuditCalls())
func (mock *RepositoryMock) CreateAuditCalls() []struct {
	Ctx   context.Context
	Audit *entities.WebhookConfigurationAudit
} {
	var calls []struct {
		Ctx   context.Context
		Audit *entities.WebhookConfigurationAudit
	}
	mock.lockCreateAudit.RLock()
	calls = mock.calls.CreateAudit
	mock.lockCreateAudit.RUnlock()
	return calls
}

// CreateHealthCheck calls CreateHealthCheckFunc.
func (mock *RepositoryMock) CreateHealthCheck(ctx context.Context, check *entities.WebhookHealthCheck) error {
	callInfo := struct {
		Ctx   context.Context
		Check *entities.WebhookHealthCheck
	}{
		Ctx:   ctx,
		Check: check,
	}
	mock.lockCreateHealthCheck.Lock()
	mock.calls.CreateHealthCheck = append(mock.calls.CreateHealthCheck, callInfo)
	mock.lockCreateHealthCheck.Unlock()
	if mock.CreateHealthCheckFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CreateHealthCheckFunc(ctx, check)
}

// CreateHealthCheckCalls gets all the calls that were made to CreateHealthCheck.
// Check the length with:
//
//	len(mockedRepository.CreateHealthCheckCalls())
func (mock *RepositoryMock) CreateHealthCheckCalls() []struct {
	Ctx   context.Context
	Check *entities.WebhookHealthCheck
} {
	var calls []struct {
		Ctx   context.Context
		Check *entities.WebhookHealthCheck
	}
	mock.lockCreateHealthCheck.RLock()
	calls = mock.calls.CreateHealthCheck
	mock.lockCreateHealthCheck.RUnlock()
	return calls
}

// CreateTemplate calls CreateTemplateFunc.
func (mock *RepositoryMock) CreateTemplate(ctx context.Context, template *entities.WebhookConfigurationTemplate) error {
	callInfo := struct {
		Ctx      context.Context
		Template *entities.WebhookConfigurationTemplate
	}{
		Ctx:      ctx,
		Template: template,
	}
	mock.lockCreateTemplate.Lock()
	mock.calls.CreateTemplate = append(mock.calls.CreateTemplate, callInfo)
	mock.lockCreateTemplate.Unlock()
	if mock.CreateTemplateFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CreateTemplateFunc(ctx, template)
}

// CreateTemplateCalls gets all the calls that were made to CreateTemplate.
// Check the length with:
//
//	len(mockedRepository.CreateTemplateCalls())
func (mock *RepositoryMock) CreateTemplateCalls() []struct {
	Ctx      context.Context
	Template *entities.WebhookConfigurationTemplate
} {
	var calls []struct {
		Ctx      context.Context
		Template *entities.WebhookConfigurationTemplate
	}
	mock.lockCreateTemplate.RLock()
	calls = mock.calls.CreateTemplate
	mock.lockCreateTemplate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *RepositoryMock) Delete(ctx context.Context, id uuid.UUID) error {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedRepository.DeleteCalls())
func (mock *RepositoryMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetActiveByDomainID calls GetActiveByDomainIDFunc.
func (mock *RepositoryMock) GetActiveByDomainID(ctx context.Context, domainID uuid.UUID) ([]*entities.WebhookConfiguration, error) {
	callInfo := struct {
		Ctx      context.Context
		DomainID uuid.UUID
	}{
		Ctx:      ctx,
		DomainID: domainID,
	}
	mock.lockGetActiveByDomainID.Lock()
	mock.calls.GetActiveByDomainID = append(mock.calls.GetActiveByDomainID, callInfo)
	mock.lockGetActiveByDomainID.Unlock()
	if mock.GetActiveByDomainIDFunc == nil {
		var (
			webhookConfigurationsOut []*entities.WebhookConfiguration
			errOut                   error
		)
		return webhookConfigurationsOut, errOut
	}
	return mock.GetActiveByDomainIDFunc(ctx, domainID)
}

// GetActiveByDomainIDCalls gets all the calls that were made to GetActiveByDomainID.
// Check the length with:
//
//	len(mockedRepository.GetActiveByDomainIDCalls())
func (mock *RepositoryMock) GetActiveByDomainIDCalls() []struct {
	Ctx      context.Context
	DomainID uuid.UUID
} {
	var calls []struct {
		Ctx      context.Context
		DomainID uuid.UUID
	}
	mock.lockGetActiveByDomainID.RLock()
	calls = mock.calls.GetActiveByDomainID
	mock.lockGetActiveByDomainID.RUnlock()
	return calls
}

// GetAuditByConfigID calls GetAuditByConfigIDFunc.
func (mock *RepositoryMock) GetAuditByConfigID(ctx context.Context, configID uuid.UUID, limit int, offset int) ([]*entities.WebhookConfigurationAudit, error) {
	callInfo := struct {
		Ctx      context.Context
		ConfigID uuid.UUID
		Limit    int
		Offset   int
	}{
		Ctx:      ctx,
		ConfigID: configID,
		Limit:    limit,
		Offset:   offset,
	}
	mock.lockGetAuditByConfigID.Lock()
	mock.calls.GetAuditByConfigID = append(mock.calls.GetAuditByConfigID, callInfo)
	mock.lockGetAuditByConfigID.Unlock()
	if mock.GetAuditByConfigIDFunc == nil {
		var (
			webhookConfigurationAuditsOut []*entities.WebhookConfigurationAudit
			errOut                        error
		)
		return webhookConfigurationAuditsOut, errOut
	}
	return mock.GetAuditByConfigIDFunc(ctx, configID, limit, offset)
}

// GetAuditByConfigIDCalls gets all the calls that were made to GetAuditByConfigID.
// Check the length with:
//
//	len(mockedRepository.GetAuditByConfigIDCalls())
func (mock *RepositoryMock) GetAuditByConfigIDCalls() []struct {
	Ctx      context.Context
	ConfigID uuid.UUID
	Limit    int
	Offset   int
} {
	var calls []struct {
		Ctx      context.Context
		ConfigID uuid.UUID
		Limit    int
		Offset   int
	}
	mock.lockGetAuditByConfigID.RLock()
	calls = mock.calls.GetAuditByConfigID
	mock.lockGetAuditByConfigID.RUnlock()
	return calls
}

// GetByDomainID calls GetByDomainIDFunc.
func (mock *RepositoryMock) GetByDomainID(ctx context.Context, domainID uuid.UUID) ([]*entities.WebhookConfiguration, error) {
	callInfo := struct {
		Ctx      context.Context
		DomainID uuid.UUID
	}{
		Ctx:      ctx,
		DomainID: domainID,
	}
	mock.lockGetByDomainID.Lock()
	mock.calls.GetByDomainID = append(mock.calls.GetByDomainID, callInfo)
	mock.lockGetByDomainID.Unlock()
	if mock.GetByDomainIDFunc == nil {
		var (
			webhookConfigurationsOut []*entities.WebhookConfiguration
			errOut                   error
		)
		return webhookConfigurationsOut, errOut
	}
	return mock.GetByDomainIDFunc(ctx, domainID)
}

// GetByDomainIDCalls gets all the calls that were made to GetByDomainID.
// Check the length with:
//
//	len(mockedRepository.GetByDomainIDCalls())
func (mock *RepositoryMock) GetByDomainIDCalls() []struct {
	Ctx      context.Context
	DomainID uuid.UUID
} {
	var calls []struct {
		Ctx      context.Context
		DomainID uuid.UUID
	}
	mock.lockGetByDomainID.RLock()
	calls = mock.calls.GetByDomainID
	mock.lockGetByDomainID.RUnlock()
	return calls
}

// GetByDomainIDAndName calls GetByDomainIDAndNameFunc.
func (mock *RepositoryMock) GetByDomainIDAndName(ctx context.Context, domainID uuid.UUID, name string) (*entities.WebhookConfiguration, error) {
	callInfo := struct {
		Ctx      context.Context
		DomainID uuid.UUID
		Name     string
	}{
		Ctx:      ctx,
		DomainID: domainID,
		Name:     name,
	}
	mock.lockGetByDomainIDAndName.Lock()
	mock.calls.GetByDomainIDAndName = append(mock.calls.GetByDomainIDAndName, callInfo)
	mock.lockGetByDomainIDAndName.Unlock()
	if mock.GetByDomainIDAndNameFunc == nil {
		var (
			webhookConfigurationOut *entities.WebhookConfiguration
			errOut                  error
		)
		return webhookConfigurationOut, errOut
	}
	return mock.GetByDomainIDAndNameFunc(ctx, domainID, name)
}

// GetByDomainIDAndNameCalls gets all the calls that were made to GetByDomainIDAndName.
// Check the length with:
//
//	len(mockedRepository.GetByDomainIDAndNameCalls())
func (mock *RepositoryMock) GetByDomainIDAndNameCalls() []struct {
	Ctx      context.Context
	DomainID uuid.UUID
	Name     string
} {
	var calls []struct {
		Ctx      context.Context
		DomainID uuid.UUID
		Name     string
	}
	mock.lockGetByDomainIDAndName.RLock()
	calls = mock.calls.GetByDomainIDAndName
	mock.lockGetByDomainIDAndName.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *RepositoryMock) GetByID(ctx context.Context, id uuid.UUID) (*entities.WebhookConfiguration, error) {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	if mock.GetByIDFunc == nil {
		var (
			webhookConfigurationOut *entities.WebhookConfiguration
			errOut                  error
		)
		return webhookConfigurationOut, errOut
	}
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedRepository.GetByIDCalls())
func (mock *RepositoryMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetHealthChecksByConfigID calls GetHealthChecksByConfigIDFunc.
func (mock *RepositoryMock) GetHealthChecksByConfigID(ctx context.Context, configID uuid.UUID, limit int, offset int) ([]*entities.WebhookHealthCheck, error) {
	callInfo := struct {
		Ctx      context.Context
		ConfigID uuid.UUID
		Limit    int
		Offset   int
	}{
		Ctx:      ctx,
		ConfigID: configID,
		Limit:    limit,
		Offset:   offset,
	}
	mock.lockGetHealthChecksByConfigID.Lock()
	mock.calls.GetHealthChecksByConfigID = append(mock.calls.GetHealthChecksByConfigID, callInfo)
	mock.lockGetHealthChecksByConfigID.Unlock()
	if mock.GetHealthChecksByConfigIDFunc == nil {
		var (
			webhookHealthChecksOut []*entities.WebhookHealthCheck
			errOut                 error
		)
		return webhookHealthChecksOut, errOut
	}
	return mock.GetHealthChecksByConfigIDFunc(ctx, configID, limit, offset)
}

// GetHealthChecksByConfigIDCalls gets all the calls that were made to GetHealthChecksByConfigID.
// Check the length with:
//
//	len(mockedRepository.GetHealthChecksByConfigIDCalls())
func (mock *RepositoryMock) GetHealthChecksByConfigIDCalls() []struct {
	Ctx      context.Context
	ConfigID uuid.UUID
	Limit    int
	Offset   int
} {
	var calls []struct {
		Ctx      context.Context
		ConfigID uuid.UUID
		Limit    int
		Offset   int
	}
	mock.lockGetHealthChecksByConfigID.RLock()
	calls = mock.calls.GetHealthChecksByConfigID
	mock.lockGetHealthChecksByConfigID.RUnlock()
	return calls
}

// GetLatestHealthCheck calls GetLatestHealthCheckFunc.
func (mock *RepositoryMock) GetLatestHealthCheck(ctx context.Context, configID uuid.UUID) (*entities.WebhookHealthCheck, error) {
	callInfo := struct {
		Ctx      context.Context
		ConfigID uuid.UUID
	}{
		Ctx:      ctx,
		ConfigID: configID,
	}
	mock.lockGetLatestHealthCheck.Lock()
	mock.calls.GetLatestHealthCheck = append(mock.calls.GetLatestHealthCheck, callInfo)
	mock.lockGetLatestHealthCheck.Unlock()
	if mock.GetLatestHealthCheckFunc == nil {
		var (
			webhookHealthCheckOut *entities.WebhookHealthCheck
			errOut                error
		)
		return webhookHealthCheckOut, errOut
	}
	return mock.GetLatestHealthCheckFunc(ctx, configID)
}

// GetLatestHealthCheckCalls gets all the calls that were made to GetLatestHealthCheck.
// Check the length with:
//
//	len(mockedRepository.GetLatestHealthCheckCalls())
func (mock *RepositoryMock) GetLatestHealthCheckCalls() []struct {
	Ctx      context.Context
	ConfigID uuid.UUID
} {
	var calls []struct {
		Ctx      context.Context
		ConfigID uuid.UUID
	}
	mock.lockGetLatestHealthCheck.RLock()
	calls = mock.calls.GetLatestHealthCheck
	mock.lockGetLatestHealthCheck.RUnlock()
	return calls
}

// GetTemplateByID calls GetTemplateByIDFunc.
func (mock *RepositoryMock) GetTemplateByID(ctx context.Context, id uuid.UUID) (*entities.WebhookConfigurationTemplate, error) {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetTemplateByID.Lock()
	mock.calls.GetTemplateByID = append(mock.calls.GetTemplateByID, callInfo)
	mock.lockGetTemplateByID.Unlock()
	if mock.GetTemplateByIDFunc == nil {
		var (
			webhookConfigurationTemplateOut *entities.WebhookConfigurationTemplate
			errOut                          error
		)
		return webhookConfigurationTemplateOut, errOut
	}
	return mock.GetTemplateByIDFunc(ctx, id)
}

// GetTemplateByIDCalls gets all the calls that were made to GetTemplateByID.
// Check the length with:
//
//	len(mockedRepository.GetTemplateByIDCalls())
func (mock *RepositoryMock) GetTemplateByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetTemplateByID.RLock()
	calls = mock.calls.GetTemplateByID
	mock.lockGetTemplateByID.RUnlock()
	return calls
}

// GetTemplateByName calls GetTemplateByNameFunc.
func (mock *RepositoryMock) GetTemplateByName(ctx context.Context, name string) (*entities.WebhookConfigurationTemplate, error) {
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockGetTemplateByName.Lock()
	mock.calls.GetTemplateByName = append(mock.calls.GetTemplateByName, callInfo)
	mock.lockGetTemplateByName.Unlock()
	if mock.GetTemplateByNameFunc == nil {
		var (
			webhookConfigurationTemplateOut *entities.WebhookConfigurationTemplate
			errOut                          error
		)
		return webhookConfigurationTemplateOut, errOut
	}
	return mock.GetTemplateByNameFunc(ctx, name)
}

// GetTemplateByNameCalls gets all the calls that were made to GetTemplateByName.
// Check the length with:
//
//	len(mockedRepository.GetTemplateByNameCalls())
func (mock *RepositoryMock) GetTemplateByNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockGetTemplateByName.RLock()
	calls = mock.calls.GetTemplateByName
	mock.lockGetTemplateByName.RUnlock()
	return calls
}

// GetTemplates calls GetTemplatesFunc.
func (mock *RepositoryMock) GetTemplates(ctx context.Context) ([]*entities.WebhookConfigurationTemplate, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetTemplates.Lock()
	mock.calls.GetTemplates = append(mock.calls.GetTemplates, callInfo)
	mock.lockGetTemplates.Unlock()
	if mock.GetTemplatesFunc == nil {
		var (
			webhookConfigurationTemplatesOut []*entities.WebhookConfigurationTemplate
			errOut                           error
		)
		return webhookConfigurationTemplatesOut, errOut
	}
	return mock.GetTemplatesFunc(ctx)
}

// GetTemplatesCalls gets all the calls that were made to GetTemplates.
// Check the length with:
//
//	len(mockedRepository.GetTemplatesCalls())
func (mock *RepositoryMock) GetTemplatesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetTemplates.RLock()
	calls = mock.calls.GetTemplates
	mock.lockGetTemplates.RUnlock()
	return calls
}

// IncrementTemplateUsage calls IncrementTemplateUsageFunc.
func (mock *RepositoryMock) IncrementTemplateUsage(ctx context.Context, templateID uuid.UUID) error {
	callInfo := struct {
		Ctx        context.Context
		TemplateID uuid.UUID
	}{
		Ctx:        ctx,
		TemplateID: templateID,
	}
	mock.lockIncrementTemplateUsage.Lock()
	mock.calls.IncrementTemplateUsage = append(mock.calls.IncrementTemplateUsage, callInfo)
	mock.lockIncrementTemplateUsage.Unlock()
	if mock.IncrementTemplateUsageFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.IncrementTemplateUsageFunc(ctx, templateID)
}

// IncrementTemplateUsageCalls gets all the calls that were made to IncrementTemplateUsage.
// Check the length with:
//
//	len(mockedRepository.IncrementTemplateUsageCalls())
func (mock *RepositoryMock) IncrementTemplateUsageCalls() []struct {
	Ctx        context.Context
	TemplateID uuid.UUID
} {
	var calls []struct {
		Ctx        context.Context
		TemplateID uuid.UUID
	}
	mock.lockIncrementTemplateUsage.RLock()
	calls = mock.calls.IncrementTemplateUsage
	mock.lockIncrementTemplateUsage.RUnlock()
	return calls
}

// ListUnhealthyWebhooks calls ListUnhealthyWebhooksFunc.
func (mock *RepositoryMock) ListUnhealthyWebhooks(ctx context.Context, limit int) ([]*entities.WebhookConfiguration, error) {
	callInfo := struct {
		Ctx   context.Context
		Limit int
	}{
		Ctx:   ctx,
		Limit: limit,
	}
	mock.lockListUnhealthyWebhooks.Lock()
	mock.calls.ListUnhealthyWebhooks = append(mock.calls.ListUnhealthyWebhooks, callInfo)
	mock.lockListUnhealthyWebhooks.Unlock()
	if mock.ListUnhealthyWebhooksFunc == nil {
		var (
			webhookConfigurationsOut []*entities.WebhookConfiguration
			errOut                   error
		)
		return webhookConfigurationsOut, errOut
	}
	return mock.ListUnhealthyWebhooksFunc(ctx, limit)
}

// ListUnhealthyWebhooksCalls gets all the calls that were made to ListUnhealthyWebhooks.
// Check the length with:
//
//	len(mockedRepository.ListUnhealthyWebhooksCalls())
func (mock *RepositoryMock) ListUnhealthyWebhooksCalls() []struct {
	Ctx   context.Context
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Limit int
	}
	mock.lockListUnhealthyWebhooks.RLock()
	calls = mock.calls.ListUnhealthyWebhooks
	mock.lockListUnhealthyWebhooks.RUnlock()
	return calls
}

// ListWebhooksForHealthCheck calls ListWebhooksForHealthCheckFunc.
func (mock *RepositoryMock) ListWebhooksForHealthCheck(ctx context.Context, olderThan int) ([]*entities.WebhookConfiguration, error) {
	callInfo := struct {
		Ctx       context.Context
		OlderThan int
	}{
		Ctx:       ctx,
		OlderThan: olderThan,
	}
	mock.lockListWebhooksForHealthCheck.Lock()
	mock.calls.ListWebhooksForHealthCheck = append(mock.calls.ListWebhooksForHealthCheck, callInfo)
	mock.lockListWebhooksForHealthCheck.Unlock()
	if mock.ListWebhooksForHealthCheckFunc == nil {
		var (
			webhookConfigurationsOut []*entities.WebhookConfiguration
			errOut                   error
		)
		return webhookConfigurationsOut, errOut
	}
	return mock.ListWebhooksForHealthCheckFunc(ctx, olderThan)
}

// ListWebhooksForHealthCheckCalls gets all the calls that were made to ListWebhooksForHealthCheck.
// Check the length with:
//
//	len(mockedRepository.ListWebhooksForHealthCheckCalls())
func (mock *RepositoryMock) ListWebhooksForHealthCheckCalls() []struct {
	Ctx       context.Context
	OlderThan int
} {
	var calls []struct {
		Ctx       context.Context
		OlderThan int
	}
	mock.lockListWebhooksForHealthCheck.RLock()
	calls = mock.calls.ListWebhooksForHealthCheck
	mock.lockListWebhooksForHealthCheck.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *RepositoryMock) Update(ctx context.Context, config *entities.WebhookConfiguration) error {
	callInfo := struct {
		Ctx    context.Context
		Config *entities.WebhookConfiguration
	}{
		Ctx:    ctx,
		Config: config,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateFunc(ctx, config)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedRepository.UpdateCalls())
func (mock *RepositoryMock) UpdateCalls() []struct {
	Ctx    context.Context
	Config *entities.WebhookConfiguration
} {
	var calls []struct {
		Ctx    context.Context
		Config *entities.WebhookConfiguration
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// UpdateTemplate calls UpdateTemplateFunc.
func (mock *RepositoryMock) UpdateTemplate(ctx context.Context, template *entities.WebhookConfigurationTemplate) error {
	callInfo := struct {
		Ctx      context.Context
		Template *entities.WebhookConfigurationTemplate
	}{
		Ctx:      ctx,
		Template: template,
	}
	mock.lockUpdateTemplate.Lock()
	mock.calls.UpdateTemplate = append(mock.calls.UpdateTemplate, callInfo)
	mock.lockUpdateTemplate.Unlock()
	if mock.UpdateTemplateFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateTemplateFunc(ctx, template)
}

// UpdateTemplateCalls gets all the calls that were made to UpdateTemplate.
// Check the length with:
//
//	len(mockedRepository.UpdateTemplateCalls())
func (mock *RepositoryMock) UpdateTemplateCalls() []struct {
	Ctx      context.Context
	Template *entities.WebhookConfigurationTemplate
} {
	var calls []struct {
		Ctx      context.Context
		Template *entities.WebhookConfigurationTemplate
	}
	mock.lockUpdateTemplate.RLock()
	calls = mock.calls.UpdateTemplate
	mock.lockUpdateTemplate.RUnlock()
	return calls
}
