// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"mailvault/domain/entities"
	"mailvault/domain/webhook_config"
	"sync"

	"github.com/gofrs/uuid/v5"
)

// UseCaseMock is a mock implementation of webhook_config.UseCase.
//
//	func TestSomethingThatUsesUseCase(t *testing.T) {
//
//		// make and configure a mocked webhook_config.UseCase
//		mockedUseCase := &UseCaseMock{
//			CheckWebhookHealthFunc: func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entities.WebhookHealthCheck, error) {
//				panic("mock out the CheckWebhookHealth method")
//			},
//			CreateFromTemplateFunc: func(ctx context.Context, input webhook_config.CreateFromTemplateInput) (*entities.WebhookConfiguration, error) {
//				panic("mock out the CreateFromTemplate method")
//			},
//			CreateWebhookConfigurationFunc: func(ctx context.Context, input webhook_config.CreateWebhookConfigInput) (*entities.WebhookConfiguration, error) {
//				panic("mock out the CreateWebhookConfiguration method")
//			},
//			DeleteWebhookConfigurationFunc: func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
//				panic("mock out the DeleteWebhookConfiguration method")
//			},
//			DisableWebhookConfigurationFunc: func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
//				panic("mock out the DisableWebhookConfiguration method")
//			},
//			EnableWebhookConfigurationFunc: func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
//				panic("mock out the EnableWebhookConfiguration method")
//			},
//			GetWebhookAuditLogFunc: func(ctx context.Context, id uuid.UUID, userID uuid.UUID, limit int, offset int) ([]*entities.WebhookConfigurationAudit, error) {
//				panic("mock out the GetWebhookAuditLog method")
//			},
//			GetWebhookConfigurationFunc: func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entities.WebhookConfiguration, error) {
//				panic("mock out the GetWebhookConfiguration method")
//			},
//			GetWebhookHealthHistoryFunc: func(ctx context.Context, id uuid.UUID, userID uuid.UUID, limit int, offset int) ([]*entities.WebhookHealthCheck, error) {
//				panic("mock out the GetWebhookHealthHistory method")
//			},
//			GetWebhookMetricsFunc: func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*webhook_config.WebhookMetrics, error) {
//				panic("mock out the GetWebhookMetrics method")
//			},
//			GetWebhookTemplateFunc: func(ctx context.Context, id uuid.UUID) (*entities.WebhookConfigurationTemplate, error) {
//				panic("mock out the GetWebhookTemplate method")
//			},
//			ListWebhookConfigurationsFunc: func(ctx context.Context, domainID uuid.UUID, userID uuid.UUID) ([]*entities.WebhookConfiguration, error) {
//				panic("mock out the ListWebhookConfigurations method")
//			},
//			ListWebhookTemplatesFunc: func(ctx context.Context) ([]*entities.WebhookConfigurationTemplate, error) {
//				panic("mock out the ListWebhookTemplates method")
//			},
//			TestWebhookConfigurationFunc: func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*webhook_config.TestWebhookResult, error) {
//				panic("mock out the TestWebhookConfiguration method")
//			},
//			UpdateWebhookConfigurationFunc: func(ctx context.Context, input webhook_config.UpdateWebhookConfigInput) (*entities.WebhookConfiguration, error) {
//				panic("mock out the UpdateWebhookConfiguration method")
//			},
//		}
//
//		// use mockedUseCase in code that requires webhook_config.UseCase
//		// and then make assertions.
//
//	}
type UseCaseMock struct {
	// CheckWebhookHealthFunc mocks the CheckWebhookHealth method.
	CheckWebhookHealthFunc func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entities.WebhookHealthCheck, error)

	// CreateFromTemplateFunc mocks the CreateFromTemplate method.
	CreateFromTemplateFunc func(ctx context.Context, input webhook_config.CreateFromTemplateInput) (*entities.WebhookConfiguration, error)

	// CreateWebhookConfigurationFunc mocks the CreateWebhookConfiguration method.
	CreateWebhookConfigurationFunc func(ctx context.Context, input webhook_config.CreateWebhookConfigInput) (*entities.WebhookConfiguration, error)

	// DeleteWebhookConfigurationFunc mocks the DeleteWebhookConfiguration method.
	DeleteWebhookConfigurationFunc func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error

	// DisableWebhookConfigurationFunc mocks the DisableWebhookConfiguration method.
	DisableWebhookConfigurationFunc func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error

	// EnableWebhookConfigurationFunc mocks the EnableWebhookConfiguration method.
	EnableWebhookConfigurationFunc func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error

	// GetWebhookAuditLogFunc mocks the GetWebhookAuditLog method.
	GetWebhookAuditLogFunc func(ctx context.Context, id uuid.UUID, userID uuid.UUID, limit int, offset int) ([]*entities.WebhookConfigurationAudit, error)

	// GetWebhookConfigurationFunc mocks the GetWebhookConfiguration method.
	GetWebhookConfigurationFunc func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entities.WebhookConfiguration, error)

	// GetWebhookHealthHistoryFunc mocks the GetWebhookHealthHistory method.
	GetWebhookHealthHistoryFunc func(ctx context.Context, id uuid.UUID, userID uuid.UUID, limit int, offset int) ([]*entities.WebhookHealthCheck, error)

	// GetWebhookMetricsFunc mocks the GetWebhookMetrics method.
	GetWebhookMetricsFunc func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*webhook_config.WebhookMetrics, error)

	// GetWebhookTemplateFunc mocks the GetWebhookTemplate method.
	GetWebhookTemplateFunc func(ctx context.Context, id uuid.UUID) (*entities.WebhookConfigurationTemplate, error)

	// ListWebhookConfigurationsFunc mocks the ListWebhookConfigurations method.
	ListWebhookConfigurationsFunc func(ctx context.Context, domainID uuid.UUID, userID uuid.UUID) ([]*entities.WebhookConfiguration, error)

	// ListWebhookTemplatesFunc mocks the ListWebhookTemplates method.
	ListWebhookTemplatesFunc func(ctx context.Context) ([]*entities.WebhookConfigurationTemplate, error)

	// TestWebhookConfigurationFunc mocks the TestWebhookConfiguration method.
	TestWebhookConfigurationFunc func(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*webhook_config.TestWebhookResult, error)

	// UpdateWebhookConfigurationFunc mocks the UpdateWebhookConfiguration method.
	UpdateWebhookConfigurationFunc func(ctx context.Context, input webhook_config.UpdateWebhookConfigInput) (*entities.WebhookConfiguration, error)

	// calls tracks calls to the methods.
	calls struct {
		// CheckWebhookHealth holds details about calls to the CheckWebhookHealth method.
		CheckWebhookHealth []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// CreateFromTemplate holds details about calls to the CreateFromTemplate method.
		CreateFromTemplate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input webhook_config.CreateFromTemplateInput
		}
		// CreateWebhookConfiguration holds details about calls to the CreateWebhookConfiguration method.
		CreateWebhookConfiguration []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input webhook_config.CreateWebhookConfigInput
		}
		// DeleteWebhookConfiguration holds details about calls to the DeleteWebhookConfiguration method.
		DeleteWebhookConfiguration []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// DisableWebhookConfiguration holds details about calls to the DisableWebhookConfiguration method.
		DisableWebhookConfiguration []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// EnableWebhookConfiguration holds details about calls to the EnableWebhookConfiguration method.
		EnableWebhookConfiguration []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// GetWebhookAuditLog holds details about calls to the GetWebhookAuditLog method.
		GetWebhookAuditLog []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// UserID is the userID argument value.
			UserID uuid.UUID
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// GetWebhookConfiguration holds details about calls to the GetWebhookConfiguration method.
		GetWebhookConfiguration []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// GetWebhookHealthHistory holds details about calls to the GetWebhookHealthHistory method.
		GetWebhookHealthHistory []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// UserID is the userID argument value.
			UserID uuid.UUID
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// GetWebhookMetrics holds details about calls to the GetWebhookMetrics method.
		GetWebhookMetrics []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// GetWebhookTemplate holds details about calls to the GetWebhookTemplate method.
		GetWebhookTemplate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// ListWebhookConfigurations holds details about calls to the ListWebhookConfigurations method.
		ListWebhookConfigurations []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// DomainID is the domainID argument value.
			DomainID uuid.UUID
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// ListWebhookTemplates holds details about calls to the ListWebhookTemplates method.
		ListWebhookTemplates []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// TestWebhookConfiguration holds details about calls to the TestWebhookConfiguration method.
		TestWebhookConfiguration []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// UpdateWebhookConfiguration holds details about calls to the UpdateWebhookConfiguration method.
		UpdateWebhookConfiguration []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input webhook_config.UpdateWebhookConfigInput
		}
	}
	lockCheckWebhookHealth          sync.RWMutex
	lockCreateFromTemplate          sync.RWMutex
	lockCreateWebhookConfiguration  sync.RWMutex
	lockDeleteWebhookConfiguration  sync.RWMutex
	lockDisableWebhookConfiguration sync.RWMutex
	lockEnableWebhookConfiguration  sync.RWMutex
	lockGetWebhookAuditLog          sync.RWMutex
	lockGetWebhookConfiguration     sync.RWMutex
	lockGetWebhookHealthHistory     sync.RWMutex
	lockGetWebhookMetrics           sync.RWMutex
	lockGetWebhookTemplate          sync.RWMutex
	lockListWebhookConfigurations   sync.RWMutex
	lockListWebhookTemplates        sync.RWMutex
	lockTestWebhookConfiguration    sync.RWMutex
	lockUpdateWebhookConfiguration  sync.RWMutex
}

// CheckWebhookHealth calls CheckWebhookHealthFunc.
func (mock *UseCaseMock) CheckWebhookHealth(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entities.WebhookHealthCheck, error) {
	callInfo := struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		ID:     id,
		UserID: userID,
	}
	mock.lockCheckWebhookHealth.Lock()
	mock.calls.CheckWebhookHealth = append(mock.calls.CheckWebhookHealth, callInfo)
	mock.lockCheckWebhookHealth.Unlock()
	if mock.CheckWebhookHealthFunc == nil {
		var (
			webhookHealthCheckOut *entities.WebhookHealthCheck
			errOut                error
		)
		return webhookHealthCheckOut, errOut
	}
	return mock.CheckWebhookHealthFunc(ctx, id, userID)
}

// CheckWebhookHealthCalls gets all the calls that were made to CheckWebhookHealth.
// Check the length with:
//
//	len(mockedUseCase.CheckWebhookHealthCalls())
func (mock *UseCaseMock) CheckWebhookHealthCalls() []struct {
	Ctx    context.Context
	ID     uuid.UUID
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}
	mock.lockCheckWebhookHealth.RLock()
	calls = mock.calls.CheckWebhookHealth
	mock.lockCheckWebhookHealth.RUnlock()
	return calls
}

// CreateFromTemplate calls CreateFromTemplateFunc.
func (mock *UseCaseMock) CreateFromTemplate(ctx context.Context, input webhook_config.CreateFromTemplateInput) (*entities.WebhookConfiguration, error) {
	callInfo := struct {
		Ctx   context.Context
		Input webhook_config.CreateFromTemplateInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockCreateFromTemplate.Lock()
	mock.calls.CreateFromTemplate = append(mock.calls.CreateFromTemplate, callInfo)
	mock.lockCreateFromTemplate.Unlock()
	if mock.CreateFromTemplateFunc == nil {
		var (
			webhookConfigurationOut *entities.WebhookConfiguration
			errOut                  error
		)
		return webhookConfigurationOut, errOut
	}
	return mock.CreateFromTemplateFunc(ctx, input)
}

// CreateFromTemplateCalls gets all the calls that were made to CreateFromTemplate.
// Check the length with:
//
//	len(mockedUseCase.CreateFromTemplateCalls())
func (mock *UseCaseMock) CreateFromTemplateCalls() []struct {
	Ctx   context.Context
	Input webhook_config.CreateFromTemplateInput
} {
	var calls []struct {
		Ctx   context.Context
		Input webhook_config.CreateFromTemplateInput
	}
	mock.lockCreateFromTemplate.RLock()
	calls = mock.calls.CreateFromTemplate
	mock.lockCreateFromTemplate.RUnlock()
	return calls
}

// CreateWebhookConfiguration calls CreateWebhookConfigurationFunc.
func (mock *UseCaseMock) CreateWebhookConfiguration(ctx context.Context, input webhook_config.CreateWebhookConfigInput) (*entities.WebhookConfiguration, error) {
	callInfo := struct {
		Ctx   context.Context
		Input webhook_config.CreateWebhookConfigInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockCreateWebhookConfiguration.Lock()
	mock.calls.CreateWebhookConfiguration = append(mock.calls.CreateWebhookConfiguration, callInfo)
	mock.lockCreateWebhookConfiguration.Unlock()
	if mock.CreateWebhookConfigurationFunc == nil {
		var (
			webhookConfigurationOut *entities.WebhookConfiguration
			errOut                  error
		)
		return webhookConfigurationOut, errOut
	}
	return mock.CreateWebhookConfigurationFunc(ctx, input)
}

// CreateWebhookConfigurationCalls gets all the calls that were made to CreateWebhookConfiguration.
// Check the length with:
//
//	len(mockedUseCase.CreateWebhookConfigurationCalls())
func (mock *UseCaseMock) CreateWebhookConfigurationCalls() []struct {
	Ctx   context.Context
	Input webhook_config.CreateWebhookConfigInput
} {
	var calls []struct {
		Ctx   context.Context
		Input webhook_config.CreateWebhookConfigInput
	}
	mock.lockCreateWebhookConfiguration.RLock()
	calls = mock.calls.CreateWebhookConfiguration
	mock.lockCreateWebhookConfiguration.RUnlock()
	return calls
}

// DeleteWebhookConfiguration calls DeleteWebhookConfigurationFunc.
func (mock *UseCaseMock) DeleteWebhookConfiguration(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	callInfo := struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		ID:     id,
		UserID: userID,
	}
	mock.lockDeleteWebhookConfiguration.Lock()
	mock.calls.DeleteWebhookConfiguration = append(mock.calls.DeleteWebhookConfiguration, callInfo)
	mock.lockDeleteWebhookConfiguration.Unlock()
	if mock.DeleteWebhookConfigurationFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteWebhookConfigurationFunc(ctx, id, userID)
}

// DeleteWebhookConfigurationCalls gets all the calls that were made to DeleteWebhookConfiguration.
// Check the length with:
//
//	len(mockedUseCase.DeleteWebhookConfigurationCalls())
func (mock *UseCaseMock) DeleteWebhookConfigurationCalls() []struct {
	Ctx    context.Context
	ID     uuid.UUID
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}
	mock.lockDeleteWebhookConfiguration.RLock()
	calls = mock.calls.DeleteWebhookConfiguration
	mock.lockDeleteWebhookConfiguration.RUnlock()
	return calls
}

// DisableWebhookConfiguration calls DisableWebhookConfigurationFunc.
func (mock *UseCaseMock) DisableWebhookConfiguration(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	callInfo := struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		ID:     id,
		UserID: userID,
	}
	mock.lockDisableWebhookConfiguration.Lock()
	mock.calls.DisableWebhookConfiguration = append(mock.calls.DisableWebhookConfiguration, callInfo)
	mock.lockDisableWebhookConfiguration.Unlock()
	if mock.DisableWebhookConfigurationFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DisableWebhookConfigurationFunc(ctx, id, userID)
}

// DisableWebhookConfigurationCalls gets all the calls that were made to DisableWebhookConfiguration.
// Check the length with:
//
//	len(mockedUseCase.DisableWebhookConfigurationCalls())
func (mock *UseCaseMock) DisableWebhookConfigurationCalls() []struct {
	Ctx    context.Context
	ID     uuid.UUID
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}
	mock.lockDisableWebhookConfiguration.RLock()
	calls = mock.calls.DisableWebhookConfiguration
	mock.lockDisableWebhookConfiguration.RUnlock()
	return calls
}

// EnableWebhookConfiguration calls EnableWebhookConfigurationFunc.
func (mock *UseCaseMock) EnableWebhookConfiguration(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	callInfo := struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		ID:     id,
		UserID: userID,
	}
	mock.lockEnableWebhookConfiguration.Lock()
	mock.calls.EnableWebhookConfiguration = append(mock.calls.EnableWebhookConfiguration, callInfo)
	mock.lockEnableWebhookConfiguration.Unlock()
	if mock.EnableWebhookConfigurationFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.EnableWebhookConfigurationFunc(ctx, id, userID)
}

// EnableWebhookConfigurationCalls gets all the calls that were made to EnableWebhookConfiguration.
// Check the length with:
//
//	len(mockedUseCase.EnableWebhookConfigurationCalls())
func (mock *UseCaseMock) EnableWebhookConfigurationCalls() []struct {
	Ctx    context.Context
	ID     uuid.UUID
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}
	mock.lockEnableWebhookConfiguration.RLock()
	calls = mock.calls.EnableWebhookConfiguration
	mock.lockEnableWebhookConfiguration.RUnlock()
	return calls
}

// GetWebhookAuditLog calls GetWebhookAuditLogFunc.
func (mock *UseCaseMock) GetWebhookAuditLog(ctx context.Context, id uuid.UUID, userID uuid.UUID, limit int, offset int) ([]*entities.WebhookConfigurationAudit, error) {
	callInfo := struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		ID:     id,
		UserID: userID,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockGetWebhookAuditLog.Lock()
	mock.calls.GetWebhookAuditLog = append(mock.calls.GetWebhookAuditLog, callInfo)
	mock.lockGetWebhookAuditLog.Unlock()
	if mock.GetWebhookAuditLogFunc == nil {
		var (
			webhookConfigurationAuditsOut []*entities.WebhookConfigurationAudit
			errOut                        error
		)
		return webhookConfigurationAuditsOut, errOut
	}
	return mock.GetWebhookAuditLogFunc(ctx, id, userID, limit, offset)
}

// GetWebhookAuditLogCalls gets all the calls that were made to GetWebhookAuditLog.
// Check the length with:
//
//	len(mockedUseCase.GetWebhookAuditLogCalls())
func (mock *UseCaseMock) GetWebhookAuditLogCalls() []struct {
	Ctx    context.Context
	ID     uuid.UUID
	UserID uuid.UUID
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
		Limit  int
		Offset int
	}
	mock.lockGetWebhookAuditLog.RLock()
	calls = mock.calls.GetWebhookAuditLog
	mock.lockGetWebhookAuditLog.RUnlock()
	return calls
}

// GetWebhookConfiguration calls GetWebhookConfigurationFunc.
func (mock *UseCaseMock) GetWebhookConfiguration(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*entities.WebhookConfiguration, error) {
	callInfo := struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		ID:     id,
		UserID: userID,
	}
	mock.lockGetWebhookConfiguration.Lock()
	mock.calls.GetWebhookConfiguration = append(mock.calls.GetWebhookConfiguration, callInfo)
	mock.lockGetWebhookConfiguration.Unlock()
	if mock.GetWebhookConfigurationFunc == nil {
		var (
			webhookConfigurationOut *entities.WebhookConfiguration
			errOut                  error
		)
		return webhookConfigurationOut, errOut
	}
	return mock.GetWebhookConfigurationFunc(ctx, id, userID)
}

// GetWebhookConfigurationCalls gets all the calls that were made to GetWebhookConfiguration.
// Check the length with:
//
//	len(mockedUseCase.GetWebhookConfigurationCalls())
func (mock *UseCaseMock) GetWebhookConfigurationCalls() []struct {
	Ctx    context.Context
	ID     uuid.UUID
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}
	mock.lockGetWebhookConfiguration.RLock()
	calls = mock.calls.GetWebhookConfiguration
	mock.lockGetWebhookConfiguration.RUnlock()
	return calls
}

// GetWebhookHealthHistory calls GetWebhookHealthHistoryFunc.
func (mock *UseCaseMock) GetWebhookHealthHistory(ctx context.Context, id uuid.UUID, userID uuid.UUID, limit int, offset int) ([]*entities.WebhookHealthCheck, error) {
	callInfo := struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		ID:     id,
		UserID: userID,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockGetWebhookHealthHistory.Lock()
	mock.calls.GetWebhookHealthHistory = append(mock.calls.GetWebhookHealthHistory, callInfo)
	mock.lockGetWebhookHealthHistory.Unlock()
	if mock.GetWebhookHealthHistoryFunc == nil {
		var (
			webhookHealthChecksOut []*entities.WebhookHealthCheck
			errOut                 error
		)
		return webhookHealthChecksOut, errOut
	}
	return mock.GetWebhookHealthHistoryFunc(ctx, id, userID, limit, offset)
}

// GetWebhookHealthHistoryCalls gets all the calls that were made to GetWebhookHealthHistory.
// Check the length with:
//
//	len(mockedUseCase.GetWebhookHealthHistoryCalls())
func (mock *UseCaseMock) GetWebhookHealthHistoryCalls() []struct {
	Ctx    context.Context
	ID     uuid.UUID
	UserID uuid.UUID
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
		Limit  int
		Offset int
	}
	mock.lockGetWebhookHealthHistory.RLock()
	calls = mock.calls.GetWebhookHealthHistory
	mock.lockGetWebhookHealthHistory.RUnlock()
	return calls
}

// GetWebhookMetrics calls GetWebhookMetricsFunc.
func (mock *UseCaseMock) GetWebhookMetrics(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*webhook_config.WebhookMetrics, error) {
	callInfo := struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		ID:     id,
		UserID: userID,
	}
	mock.lockGetWebhookMetrics.Lock()
	mock.calls.GetWebhookMetrics = append(mock.calls.GetWebhookMetrics, callInfo)
	mock.lockGetWebhookMetrics.Unlock()
	if mock.GetWebhookMetricsFunc == nil {
		var (
			webhookMetricsOut *webhook_config.WebhookMetrics
			errOut            error
		)
		return webhookMetricsOut, errOut
	}
	return mock.GetWebhookMetricsFunc(ctx, id, userID)
}

// GetWebhookMetricsCalls gets all the calls that were made to GetWebhookMetrics.
// Check the length with:
//
//	len(mockedUseCase.GetWebhookMetricsCalls())
func (mock *UseCaseMock) GetWebhookMetricsCalls() []struct {
	Ctx    context.Context
	ID     uuid.UUID
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}
	mock.lockGetWebhookMetrics.RLock()
	calls = mock.calls.GetWebhookMetrics
	mock.lockGetWebhookMetrics.RUnlock()
	return calls
}

// GetWebhookTemplate calls GetWebhookTemplateFunc.
func (mock *UseCaseMock) GetWebhookTemplate(ctx context.Context, id uuid.UUID) (*entities.WebhookConfigurationTemplate, error) {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetWebhookTemplate.Lock()
	mock.calls.GetWebhookTemplate = append(mock.calls.GetWebhookTemplate, callInfo)
	mock.lockGetWebhookTemplate.Unlock()
	if mock.GetWebhookTemplateFunc == nil {
		var (
			webhookConfigurationTemplateOut *entities.WebhookConfigurationTemplate
			errOut                          error
		)
		return webhookConfigurationTemplateOut, errOut
	}
	return mock.GetWebhookTemplateFunc(ctx, id)
}

// GetWebhookTemplateCalls gets all the calls that were made to GetWebhookTemplate.
// Check the length with:
//
//	len(mockedUseCase.GetWebhookTemplateCalls())
func (mock *UseCaseMock) GetWebhookTemplateCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetWebhookTemplate.RLock()
	calls = mock.calls.GetWebhookTemplate
	mock.lockGetWebhookTemplate.RUnlock()
	return calls
}

// ListWebhookConfigurations calls ListWebhookConfigurationsFunc.
func (mock *UseCaseMock) ListWebhookConfigurations(ctx context.Context, domainID uuid.UUID, userID uuid.UUID) ([]*entities.WebhookConfiguration, error) {
	callInfo := struct {
		Ctx      context.Context
		DomainID uuid.UUID
		UserID   uuid.UUID
	}{
		Ctx:      ctx,
		DomainID: domainID,
		UserID:   userID,
	}
	mock.lockListWebhookConfigurations.Lock()
	mock.calls.ListWebhookConfigurations = append(mock.calls.ListWebhookConfigurations, callInfo)
	mock.lockListWebhookConfigurations.Unlock()
	if mock.ListWebhookConfigurationsFunc == nil {
		var (
			webhookConfigurationsOut []*entities.WebhookConfiguration
			errOut                   error
		)
		return webhookConfigurationsOut, errOut
	}
	return mock.ListWebhookConfigurationsFunc(ctx, domainID, userID)
}

// ListWebhookConfigurationsCalls gets all the calls that were made to ListWebhookConfigurations.
// Check the length with:
//
//	len(mockedUseCase.ListWebhookConfigurationsCalls())
func (mock *UseCaseMock) ListWebhookConfigurationsCalls() []struct {
	Ctx      context.Context
	DomainID uuid.UUID
	UserID   uuid.UUID
} {
	var calls []struct {
		Ctx      context.Context
		DomainID uuid.UUID
		UserID   uuid.UUID
	}
	mock.lockListWebhookConfigurations.RLock()
	calls = mock.calls.ListWebhookConfigurations
	mock.lockListWebhookConfigurations.RUnlock()
	return calls
}

// ListWebhookTemplates calls ListWebhookTemplatesFunc.
func (mock *UseCaseMock) ListWebhookTemplates(ctx context.Context) ([]*entities.WebhookConfigurationTemplate, error) {
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListWebhookTemplates.Lock()
	mock.calls.ListWebhookTemplates = append(mock.calls.ListWebhookTemplates, callInfo)
	mock.lockListWebhookTemplates.Unlock()
	if mock.ListWebhookTemplatesFunc == nil {
		var (
			webhookConfigurationTemplatesOut []*entities.WebhookConfigurationTemplate
			errOut                           error
		)
		return webhookConfigurationTemplatesOut, errOut
	}
	return mock.ListWebhookTemplatesFunc(ctx)
}

// ListWebhookTemplatesCalls gets all the calls that were made to ListWebhookTemplates.
// Check the length with:
//
//	len(mockedUseCase.ListWebhookTemplatesCalls())
func (mock *UseCaseMock) ListWebhookTemplatesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListWebhookTemplates.RLock()
	calls = mock.calls.ListWebhookTemplates
	mock.lockListWebhookTemplates.RUnlock()
	return calls
}

// TestWebhookConfiguration calls TestWebhookConfigurationFunc.
func (mock *UseCaseMock) TestWebhookConfiguration(ctx context.Context, id uuid.UUID, userID uuid.UUID) (*webhook_config.TestWebhookResult, error) {
	callInfo := struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		ID:     id,
		UserID: userID,
	}
	mock.lockTestWebhookConfiguration.Lock()
	mock.calls.TestWebhookConfiguration = append(mock.calls.TestWebhookConfiguration, callInfo)
	mock.lockTestWebhookConfiguration.Unlock()
	if mock.TestWebhookConfigurationFunc == nil {
		var (
			testWebhookResultOut *webhook_config.TestWebhookResult
			errOut               error
		)
		return testWebhookResultOut, errOut
	}
	return mock.TestWebhookConfigurationFunc(ctx, id, userID)
}

// TestWebhookConfigurationCalls gets all the calls that were made to TestWebhookConfiguration.
// Check the length with:
//
//	len(mockedUseCase.TestWebhookConfigurationCalls())
func (mock *UseCaseMock) TestWebhookConfigurationCalls() []struct {
	Ctx    context.Context
	ID     uuid.UUID
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		ID     uuid.UUID
		UserID uuid.UUID
	}
	mock.lockTestWebhookConfiguration.RLock()
	calls = mock.calls.TestWebhookConfiguration
	mock.lockTestWebhookConfiguration.RUnlock()
	return calls
}

// UpdateWebhookConfiguration calls UpdateWebhookConfigurationFunc.
func (mock *UseCaseMock) UpdateWebhookConfiguration(ctx context.Context, input webhook_config.UpdateWebhookConfigInput) (*entities.WebhookConfiguration, error) {
	callInfo := struct {
		Ctx   context.Context
		Input webhook_config.UpdateWebhookConfigInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockUpdateWebhookConfiguration.Lock()
	mock.calls.UpdateWebhookConfiguration = append(mock.calls.UpdateWebhookConfiguration, callInfo)
	mock.lockUpdateWebhookConfiguration.Unlock()
	if mock.UpdateWebhookConfigurationFunc == nil {
		var (
			webhookConfigurationOut *entities.WebhookConfiguration
			errOut                  error
		)
		return webhookConfigurationOut, errOut
	}
	return mock.UpdateWebhookConfigurationFunc(ctx, input)
}

// UpdateWebhookConfigurationCalls gets all the calls that were made to UpdateWebhookConfiguration.
// Check the length with:
//
//	len(mockedUseCase.UpdateWebhookConfigurationCalls())
func (mock *UseCaseMock) UpdateWebhookConfigurationCalls() []struct {
	Ctx   context.Context
	Input webhook_config.UpdateWebhookConfigInput
} {
	var calls []struct {
		Ctx   context.Context
		Input webhook_config.UpdateWebhookConfigInput
	}
	mock.lockUpdateWebhookConfiguration.RLock()
	calls = mock.calls.UpdateWebhookConfiguration
	mock.lockUpdateWebhookConfiguration.RUnlock()
	return calls
}
