// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"mailvault/domain/entities"
	"sync"

	"github.com/gofrs/uuid/v5"
)

// RepositoryMock is a mock implementation of domain.Repository.
//
//	func TestSomethingThatUsesRepository(t *testing.T) {
//
//		// make and configure a mocked domain.Repository
//		mockedRepository := &RepositoryMock{
//			CreateFunc: func(ctx context.Context, domain *entities.Domain) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id uuid.UUID) error {
//				panic("mock out the Delete method")
//			},
//			GetByAPIKeyFunc: func(ctx context.Context, apiKey string) (*entities.Domain, error) {
//				panic("mock out the GetByAPIKey method")
//			},
//			GetByDomainFunc: func(ctx context.Context, domain string) (*entities.Domain, error) {
//				panic("mock out the GetByDomain method")
//			},
//			GetByIDFunc: func(ctx context.Context, id uuid.UUID) (*entities.Domain, error) {
//				panic("mock out the GetByID method")
//			},
//			GetByUserIDFunc: func(ctx context.Context, userID uuid.UUID) ([]*entities.Domain, error) {
//				panic("mock out the GetByUserID method")
//			},
//			UpdateFunc: func(ctx context.Context, domain *entities.Domain) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedRepository in code that requires domain.Repository
//		// and then make assertions.
//
//	}
type RepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, domain *entities.Domain) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id uuid.UUID) error

	// GetByAPIKeyFunc mocks the GetByAPIKey method.
	GetByAPIKeyFunc func(ctx context.Context, apiKey string) (*entities.Domain, error)

	// GetByDomainFunc mocks the GetByDomain method.
	GetByDomainFunc func(ctx context.Context, domain string) (*entities.Domain, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id uuid.UUID) (*entities.Domain, error)

	// GetByUserIDFunc mocks the GetByUserID method.
	GetByUserIDFunc func(ctx context.Context, userID uuid.UUID) ([]*entities.Domain, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, domain *entities.Domain) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Domain is the domain argument value.
			Domain *entities.Domain
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetByAPIKey holds details about calls to the GetByAPIKey method.
		GetByAPIKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ApiKey is the apiKey argument value.
			ApiKey string
		}
		// GetByDomain holds details about calls to the GetByDomain method.
		GetByDomain []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Domain is the domain argument value.
			Domain string
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uuid.UUID
		}
		// GetByUserID holds details about calls to the GetByUserID method.
		GetByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID uuid.UUID
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Domain is the domain argument value.
			Domain *entities.Domain
		}
	}
	lockCreate      sync.RWMutex
	lockDelete      sync.RWMutex
	lockGetByAPIKey sync.RWMutex
	lockGetByDomain sync.RWMutex
	lockGetByID     sync.RWMutex
	lockGetByUserID sync.RWMutex
	lockUpdate      sync.RWMutex
}

// Create calls CreateFunc.
func (mock *RepositoryMock) Create(ctx context.Context, domain *entities.Domain) error {
	callInfo := struct {
		Ctx    context.Context
		Domain *entities.Domain
	}{
		Ctx:    ctx,
		Domain: domain,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	if mock.CreateFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.CreateFunc(ctx, domain)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedRepository.CreateCalls())
func (mock *RepositoryMock) CreateCalls() []struct {
	Ctx    context.Context
	Domain *entities.Domain
} {
	var calls []struct {
		Ctx    context.Context
		Domain *entities.Domain
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *RepositoryMock) Delete(ctx context.Context, id uuid.UUID) error {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	if mock.DeleteFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedRepository.DeleteCalls())
func (mock *RepositoryMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetByAPIKey calls GetByAPIKeyFunc.
func (mock *RepositoryMock) GetByAPIKey(ctx context.Context, apiKey string) (*entities.Domain, error) {
	callInfo := struct {
		Ctx    context.Context
		ApiKey string
	}{
		Ctx:    ctx,
		ApiKey: apiKey,
	}
	mock.lockGetByAPIKey.Lock()
	mock.calls.GetByAPIKey = append(mock.calls.GetByAPIKey, callInfo)
	mock.lockGetByAPIKey.Unlock()
	if mock.GetByAPIKeyFunc == nil {
		var (
			domainOut *entities.Domain
			errOut    error
		)
		return domainOut, errOut
	}
	return mock.GetByAPIKeyFunc(ctx, apiKey)
}

// GetByAPIKeyCalls gets all the calls that were made to GetByAPIKey.
// Check the length with:
//
//	len(mockedRepository.GetByAPIKeyCalls())
func (mock *RepositoryMock) GetByAPIKeyCalls() []struct {
	Ctx    context.Context
	ApiKey string
} {
	var calls []struct {
		Ctx    context.Context
		ApiKey string
	}
	mock.lockGetByAPIKey.RLock()
	calls = mock.calls.GetByAPIKey
	mock.lockGetByAPIKey.RUnlock()
	return calls
}

// GetByDomain calls GetByDomainFunc.
func (mock *RepositoryMock) GetByDomain(ctx context.Context, domain string) (*entities.Domain, error) {
	callInfo := struct {
		Ctx    context.Context
		Domain string
	}{
		Ctx:    ctx,
		Domain: domain,
	}
	mock.lockGetByDomain.Lock()
	mock.calls.GetByDomain = append(mock.calls.GetByDomain, callInfo)
	mock.lockGetByDomain.Unlock()
	if mock.GetByDomainFunc == nil {
		var (
			domainOut *entities.Domain
			errOut    error
		)
		return domainOut, errOut
	}
	return mock.GetByDomainFunc(ctx, domain)
}

// GetByDomainCalls gets all the calls that were made to GetByDomain.
// Check the length with:
//
//	len(mockedRepository.GetByDomainCalls())
func (mock *RepositoryMock) GetByDomainCalls() []struct {
	Ctx    context.Context
	Domain string
} {
	var calls []struct {
		Ctx    context.Context
		Domain string
	}
	mock.lockGetByDomain.RLock()
	calls = mock.calls.GetByDomain
	mock.lockGetByDomain.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *RepositoryMock) GetByID(ctx context.Context, id uuid.UUID) (*entities.Domain, error) {
	callInfo := struct {
		Ctx context.Context
		ID  uuid.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	mock.lockGetByID.Unlock()
	if mock.GetByIDFunc == nil {
		var (
			domainOut *entities.Domain
			errOut    error
		)
		return domainOut, errOut
	}
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//
//	len(mockedRepository.GetByIDCalls())
func (mock *RepositoryMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  uuid.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  uuid.UUID
	}
	mock.lockGetByID.RLock()
	calls = mock.calls.GetByID
	mock.lockGetByID.RUnlock()
	return calls
}

// GetByUserID calls GetByUserIDFunc.
func (mock *RepositoryMock) GetByUserID(ctx context.Context, userID uuid.UUID) ([]*entities.Domain, error) {
	callInfo := struct {
		Ctx    context.Context
		UserID uuid.UUID
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockGetByUserID.Lock()
	mock.calls.GetByUserID = append(mock.calls.GetByUserID, callInfo)
	mock.lockGetByUserID.Unlock()
	if mock.GetByUserIDFunc == nil {
		var (
			domainsOut []*entities.Domain
			errOut     error
		)
		return domainsOut, errOut
	}
	return mock.GetByUserIDFunc(ctx, userID)
}

// GetByUserIDCalls gets all the calls that were made to GetByUserID.
// Check the length with:
//
//	len(mockedRepository.GetByUserIDCalls())
func (mock *RepositoryMock) GetByUserIDCalls() []struct {
	Ctx    context.Context
	UserID uuid.UUID
} {
	var calls []struct {
		Ctx    context.Context
		UserID uuid.UUID
	}
	mock.lockGetByUserID.RLock()
	calls = mock.calls.GetByUserID
	mock.lockGetByUserID.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *RepositoryMock) Update(ctx context.Context, domain *entities.Domain) error {
	callInfo := struct {
		Ctx    context.Context
		Domain *entities.Domain
	}{
		Ctx:    ctx,
		Domain: domain,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	if mock.UpdateFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.UpdateFunc(ctx, domain)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedRepository.UpdateCalls())
func (mock *RepositoryMock) UpdateCalls() []struct {
	Ctx    context.Context
	Domain *entities.Domain
} {
	var calls []struct {
		Ctx    context.Context
		Domain *entities.Domain
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
