// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate user with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app_api_v1_auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "$ref": "#/definitions/auth.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get information about the currently authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "Current user information",
                        "schema": {
                            "$ref": "#/definitions/users.UserResult"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Create a new user account with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User created successfully",
                        "schema": {
                            "$ref": "#/definitions/auth.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            }
        },
        "/domains": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all domains belonging to the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Domains"
                ],
                "summary": "Get user domains",
                "responses": {
                    "200": {
                        "description": "List of user domains",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domains.DomainResult"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Register a new domain for the authenticated user with user-provided encryption public key and optional webhook configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Domains"
                ],
                "summary": "Create a new domain",
                "parameters": [
                    {
                        "description": "Domain creation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domains.CreateDomainRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Domain created successfully",
                        "schema": {
                            "$ref": "#/definitions/domains.DomainResult"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            }
        },
        "/domains/{domainId}/emails": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all email addresses configured for a specific domain",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Emails"
                ],
                "summary": "Get domain email addresses",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Domain ID",
                        "name": "domainId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of email addresses",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/emails.EmailAddressResult"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new email address for a specific domain with optional forwarding settings",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Emails"
                ],
                "summary": "Create email address",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Domain ID",
                        "name": "domainId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Email address creation details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/emails.CreateEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Email address created successfully",
                        "schema": {
                            "$ref": "#/definitions/emails.EmailAddressResult"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            }
        },
        "/domains/{domainId}/emails/{emailId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a specific email address by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Emails"
                ],
                "summary": "Get email address by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Domain ID",
                        "name": "domainId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Email Address ID",
                        "name": "emailId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email address details",
                        "schema": {
                            "$ref": "#/definitions/emails.EmailAddressResult"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "404": {
                        "description": "Email address not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update email address settings such as forwarding configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Emails"
                ],
                "summary": "Update email address",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Domain ID",
                        "name": "domainId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Email Address ID",
                        "name": "emailId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Email address update details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/emails.UpdateEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email address updated successfully",
                        "schema": {
                            "$ref": "#/definitions/emails.EmailAddressResult"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an email address and all associated received emails",
                "tags": [
                    "Emails"
                ],
                "summary": "Delete email address",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Domain ID",
                        "name": "domainId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Email Address ID",
                        "name": "emailId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Email address deleted successfully"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            }
        },
        "/domains/{domainId}/emails/{emailId}/received": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve received emails for a specific email address with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Emails"
                ],
                "summary": "Get received emails",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Domain ID",
                        "name": "domainId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Email Address ID",
                        "name": "emailId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of emails per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Number of emails to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of received emails",
                        "schema": {
                            "$ref": "#/definitions/models.PaginatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            }
        },
        "/domains/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a specific domain by its ID (must belong to authenticated user)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Domains"
                ],
                "summary": "Get domain by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Domain ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Domain details",
                        "schema": {
                            "$ref": "#/definitions/domains.DomainResult"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid domain ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden - domain does not belong to user",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "404": {
                        "description": "Domain not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update domain settings including public key, verification status, and webhook configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Domains"
                ],
                "summary": "Update domain",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Domain ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Domain update details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domains.UpdateDomainRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Domain updated successfully",
                        "schema": {
                            "$ref": "#/definitions/domains.DomainResult"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden - domain does not belong to user",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "404": {
                        "description": "Domain not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a domain and all associated email addresses and received emails",
                "tags": [
                    "Domains"
                ],
                "summary": "Delete domain",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Domain ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Domain deleted successfully"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "404": {
                        "description": "Domain not found or does not belong to user",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            }
        },
        "/domains/{id}/validate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manually trigger domain validation for DNS records",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domains"
                ],
                "summary": "Validate domain",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Domain ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DomainValidationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            }
        },
        "/domains/{id}/validation/instructions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get detailed instructions for setting up DNS records for domain validation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domains"
                ],
                "summary": "Get domain validation instructions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Domain ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ValidationInstructionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            }
        },
        "/domains/{id}/validation/retry": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manually retry domain validation, resetting the status and attempting validation again",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domains"
                ],
                "summary": "Retry domain validation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Domain ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DomainValidationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            }
        },
        "/domains/{id}/validation/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get the current validation status and history for a domain",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "domains"
                ],
                "summary": "Get domain validation status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Domain ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DomainValidationStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            }
        },
        "/emails/received": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all received emails for the authenticated user across all domains with advanced filtering",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Emails"
                ],
                "summary": "List user's received emails",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Maximum number of emails to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Number of emails to skip",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by domain",
                        "name": "domain",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "received_at",
                        "description": "Sort field: received_at, sequence_number, from_address, subject",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "desc",
                        "description": "Sort order: asc, desc",
                        "name": "sort_order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by recipient email address",
                        "name": "email_address",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by sender email address",
                        "name": "from_address",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter from date (YYYY-MM-DD)",
                        "name": "date_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to date (YYYY-MM-DD)",
                        "name": "date_to",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum spam score (0-1)",
                        "name": "spam_min",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum spam score (0-1)",
                        "name": "spam_max",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Security status: clean, suspicious, quarantined, high_risk",
                        "name": "security_status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Full-text search in subject and from address",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of received emails",
                        "schema": {
                            "$ref": "#/definitions/models.PaginatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the API is running and healthy, including database connectivity",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "API is healthy",
                        "schema": {
                            "$ref": "#/definitions/v1.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "API is unhealthy",
                        "schema": {
                            "$ref": "#/definitions/v1.HealthResponse"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Check if the API is ready to accept traffic (focused on critical dependencies)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "API is ready",
                        "schema": {
                            "$ref": "#/definitions/v1.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "API is not ready",
                        "schema": {
                            "$ref": "#/definitions/v1.HealthResponse"
                        }
                    }
                }
            }
        },
        "/received/{receivedEmailId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a specific received email by its ID (must belong to authenticated user)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Emails"
                ],
                "summary": "Get received email by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Received Email ID",
                        "name": "receivedEmailId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Received email details",
                        "schema": {
                            "$ref": "#/definitions/emails.ReceivedEmailResult"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "404": {
                        "description": "Received email not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a specific received email by its ID (must belong to authenticated user)",
                "tags": [
                    "Emails"
                ],
                "summary": "Delete received email by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Received Email ID",
                        "name": "receivedEmailId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Received email deleted successfully"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "404": {
                        "description": "Received email not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            }
        },
        "/received/{receivedEmailId}/parsed": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a specific received email with parsed content in multiple formats",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Emails"
                ],
                "summary": "Get parsed received email by ID",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Received Email ID",
                        "name": "receivedEmailId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Base64 encoded private key for decryption",
                        "name": "private_key",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "auto",
                        "description": "Content format preference: auto, plain, html, markdown, raw",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Parsed received email details",
                        "schema": {
                            "$ref": "#/definitions/emails.ParsedEmailResult"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "404": {
                        "description": "Received email not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            }
        },
        "/send": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Send an email using domain API key authentication. The from address must belong to the authenticated domain.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Email Sending"
                ],
                "summary": "Send email",
                "parameters": [
                    {
                        "description": "Email sending details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/send.SendEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Email queued for delivery",
                        "schema": {
                            "$ref": "#/definitions/send.SendEmailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid email data",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or missing API key",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponseBody"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app_api_v1_auth.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/auth.UserResult"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "auth.UserResult": {
            "type": "object",
            "properties": {
                "auth_provider": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "domains.CreateDomainRequest": {
            "type": "object",
            "required": [
                "domain",
                "public_key"
            ],
            "properties": {
                "auto_create_address": {
                    "type": "boolean"
                },
                "domain": {
                    "type": "string",
                    "maxLength": 253,
                    "minLength": 1
                },
                "public_key": {
                    "type": "string",
                    "minLength": 100
                },
                "storage_enabled": {
                    "type": "boolean"
                },
                "webhook_config": {
                    "$ref": "#/definitions/domains.WebhookConfigRequest"
                }
            }
        },
        "domains.DomainResult": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "auto_create_address": {
                    "type": "boolean"
                },
                "created_at": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_verification_attempt": {
                    "type": "string"
                },
                "next_verification_attempt": {
                    "type": "string"
                },
                "public_key": {
                    "type": "string"
                },
                "storage_enabled": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                },
                "verification_attempts": {
                    "type": "integer"
                },
                "verification_error": {
                    "type": "string"
                },
                "verification_status": {
                    "description": "Verification fields",
                    "type": "string"
                },
                "verification_token": {
                    "type": "string"
                },
                "webhook_config": {
                    "$ref": "#/definitions/domains.WebhookConfigResult"
                }
            }
        },
        "domains.UpdateDomainRequest": {
            "type": "object",
            "properties": {
                "auto_create_address": {
                    "type": "boolean"
                },
                "public_key": {
                    "type": "string"
                },
                "storage_enabled": {
                    "type": "boolean"
                },
                "webhook_config": {
                    "$ref": "#/definitions/domains.WebhookConfigRequest"
                }
            }
        },
        "domains.WebhookConfigRequest": {
            "type": "object",
            "required": [
                "url"
            ],
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "secret": {
                    "type": "string",
                    "maxLength": 256,
                    "minLength": 16
                },
                "url": {
                    "type": "string",
                    "maxLength": 2048
                }
            }
        },
        "domains.WebhookConfigResult": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "secret": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "emailrender.AttachmentInfo": {
            "type": "object",
            "properties": {
                "cid": {
                    "type": "string"
                },
                "content_type": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_inline": {
                    "type": "boolean"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "emailrender.ContentFormat": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "type": {
                    "description": "\"text/plain\", \"text/html\", \"text/markdown\"",
                    "type": "string"
                }
            }
        },
        "emailrender.EmailResponse": {
            "type": "object",
            "properties": {
                "attachment_count": {
                    "type": "integer"
                },
                "attachments": {
                    "description": "Attachments metadata (content served separately)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/emailrender.AttachmentInfo"
                    }
                },
                "available_formats": {
                    "description": "Available content formats",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/emailrender.ContentFormat"
                    }
                },
                "date": {
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "has_attachments": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "inline_image_count": {
                    "type": "integer"
                },
                "is_multipart": {
                    "description": "Metadata",
                    "type": "boolean"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "emails.CreateEmailRequest": {
            "type": "object",
            "required": [
                "local_part"
            ],
            "properties": {
                "forward_addresses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "local_part": {
                    "type": "string"
                }
            }
        },
        "emails.EmailAddressResult": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "domain_id": {
                    "type": "string"
                },
                "forward_addresses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "full_address": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "local_part": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "emails.ParsedEmailResult": {
            "type": "object",
            "properties": {
                "available_formats": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "domain_name": {
                    "type": "string"
                },
                "email_address": {
                    "type": "string"
                },
                "from_address": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "parsed_content": {
                    "$ref": "#/definitions/emailrender.EmailResponse"
                },
                "received_at": {
                    "type": "string"
                },
                "rendering_error": {
                    "type": "string"
                },
                "sequence_number": {
                    "type": "integer"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "emails.ReceivedEmailResult": {
            "type": "object",
            "properties": {
                "domain_name": {
                    "type": "string"
                },
                "email_address": {
                    "type": "string"
                },
                "encrypted_body": {
                    "type": "string"
                },
                "from_address": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "received_at": {
                    "type": "string"
                },
                "sequence_number": {
                    "type": "integer"
                },
                "smtp_verification": {
                    "$ref": "#/definitions/emails.SMTPVerificationResult"
                },
                "subject": {
                    "type": "string"
                }
            }
        },
        "emails.SMTPVerificationResult": {
            "type": "object",
            "properties": {
                "content_verdict": {
                    "type": "string"
                },
                "dkim_domain": {
                    "type": "string"
                },
                "dkim_selector": {
                    "type": "string"
                },
                "dkim_valid": {
                    "type": "boolean"
                },
                "dmarc_alignment_dkim": {
                    "type": "boolean"
                },
                "dmarc_alignment_spf": {
                    "type": "boolean"
                },
                "dmarc_policy": {
                    "type": "string"
                },
                "dmarc_result": {
                    "type": "string"
                },
                "final_action": {
                    "type": "string"
                },
                "is_blacklisted": {
                    "type": "boolean"
                },
                "is_quarantined": {
                    "type": "boolean"
                },
                "reputation_score": {
                    "type": "number"
                },
                "sender_domain": {
                    "type": "string"
                },
                "sender_ip": {
                    "type": "string"
                },
                "spam_score": {
                    "type": "number"
                },
                "spf_mechanism": {
                    "type": "string"
                },
                "spf_result": {
                    "type": "string"
                },
                "verified_at": {
                    "type": "string"
                }
            }
        },
        "emails.UpdateEmailRequest": {
            "type": "object",
            "properties": {
                "forward_addresses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.DomainValidationResponse": {
            "description": "Domain validation response with instructions and status",
            "type": "object",
            "properties": {
                "attempts": {
                    "type": "integer",
                    "example": 1
                },
                "domain_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "domain_name": {
                    "type": "string",
                    "example": "example.com"
                },
                "error": {
                    "type": "string",
                    "example": "DNS records not found"
                },
                "instructions": {
                    "$ref": "#/definitions/models.ValidationInstructions"
                },
                "last_attempt": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "next_attempt": {
                    "type": "string",
                    "example": "2023-01-01T01:00:00Z"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "verification_token": {
                    "type": "string",
                    "example": "abc123def456"
                }
            }
        },
        "models.DomainValidationStatusResponse": {
            "description": "Detailed domain validation status with history",
            "type": "object",
            "properties": {
                "attempts": {
                    "type": "integer",
                    "example": 2
                },
                "can_retry": {
                    "type": "boolean",
                    "example": false
                },
                "domain_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "domain_name": {
                    "type": "string",
                    "example": "example.com"
                },
                "error": {
                    "type": "string",
                    "example": "TXT record validation failed"
                },
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ValidationRecord"
                    }
                },
                "is_verified": {
                    "type": "boolean",
                    "example": true
                },
                "last_attempt": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "next_attempt": {
                    "type": "string",
                    "example": "2023-01-01T01:00:00Z"
                },
                "status": {
                    "type": "string",
                    "example": "verified"
                },
                "txt_record": {
                    "type": "string",
                    "example": "mailvault-verification=abc123def456"
                },
                "verification_token": {
                    "type": "string",
                    "example": "abc123def456"
                }
            }
        },
        "models.ErrorResponseBody": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid request"
                }
            }
        },
        "models.MXRecordInfo": {
            "description": "MX record information",
            "type": "object",
            "properties": {
                "host": {
                    "type": "string",
                    "example": "mail.mailvault.sh"
                },
                "priority": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "models.MXRecordInstructions": {
            "description": "MX record setup instructions",
            "type": "object",
            "properties": {
                "example": {
                    "type": "string"
                },
                "instructions": {
                    "type": "string",
                    "example": "Add these MX records to your DNS configuration"
                },
                "required_records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MXRecordInfo"
                    }
                }
            }
        },
        "models.PaginatedResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "pagination": {
                    "type": "object",
                    "properties": {
                        "limit": {
                            "type": "integer",
                            "example": 10
                        },
                        "offset": {
                            "type": "integer",
                            "example": 0
                        },
                        "total": {
                            "type": "integer",
                            "example": 100
                        }
                    }
                }
            }
        },
        "models.TXTRecordInstructions": {
            "description": "TXT record setup instructions for domain verification",
            "type": "object",
            "properties": {
                "example": {
                    "type": "string"
                },
                "instructions": {
                    "type": "string",
                    "example": "Add this TXT record to verify domain ownership"
                },
                "record_name": {
                    "type": "string",
                    "example": "example.com"
                },
                "record_value": {
                    "type": "string",
                    "example": "mailvault-verification=abc123def456"
                }
            }
        },
        "models.ValidationDetails": {
            "description": "Detailed validation results including DNS records found",
            "type": "object",
            "properties": {
                "dns_server": {
                    "type": "string",
                    "example": "8.8.8.8:53"
                },
                "error_details": {
                    "type": "string",
                    "example": "Connection timeout"
                },
                "expected_mx_servers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"mail.mailvault.sh\"",
                        " \"mail2.mailvault.sh\"]"
                    ]
                },
                "expected_txt_record": {
                    "type": "string",
                    "example": "mailvault-verification=abc123def456"
                },
                "found_mx_records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MXRecordInfo"
                    }
                },
                "found_txt_records": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "[\"mailvault-verification=abc123def456\"]"
                    ]
                },
                "mx_validation_passed": {
                    "type": "boolean",
                    "example": true
                },
                "query_time": {
                    "type": "string",
                    "example": "250ms"
                },
                "retry_count": {
                    "type": "integer",
                    "example": 0
                },
                "txt_validation_passed": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.ValidationInstructions": {
            "description": "DNS setup instructions for domain validation",
            "type": "object",
            "properties": {
                "mx_records": {
                    "$ref": "#/definitions/models.MXRecordInstructions"
                },
                "txt_record": {
                    "$ref": "#/definitions/models.TXTRecordInstructions"
                }
            }
        },
        "models.ValidationInstructionsResponse": {
            "description": "Complete validation instructions for domain setup",
            "type": "object",
            "properties": {
                "domain_id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "domain_name": {
                    "type": "string",
                    "example": "example.com"
                },
                "instructions": {
                    "$ref": "#/definitions/models.ValidationInstructions"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "troubleshooting_tips": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "verification_steps": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "verification_token": {
                    "type": "string",
                    "example": "abc123def456"
                }
            }
        },
        "models.ValidationRecord": {
            "description": "Individual validation attempt record",
            "type": "object",
            "properties": {
                "completed_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:30Z"
                },
                "created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "details": {
                    "$ref": "#/definitions/models.ValidationDetails"
                },
                "error_message": {
                    "type": "string",
                    "example": "DNS timeout"
                },
                "id": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "started_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "validation_type": {
                    "type": "string",
                    "example": "full_validation"
                }
            }
        },
        "send.SendEmailRequest": {
            "type": "object",
            "required": [
                "from",
                "subject",
                "to"
            ],
            "properties": {
                "bcc": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "cc": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "from": {
                    "type": "string"
                },
                "html_body": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "text_body": {
                    "type": "string"
                },
                "to": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "send.SendEmailResponse": {
            "type": "object",
            "properties": {
                "message_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "users.UserResult": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "v1.HealthCheck": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "v1.HealthResponse": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/v1.HealthCheck"
                    }
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
